import Mathlib
import LeanUrat.Moves.Defs
import LeanUrat.Moves.DefsT
import LeanUrat.Moves.DefsCore
import LeanUrat.Moves.DefsL
import LeanUrat.MovesGr.Defs

open Polynomial LeanUrat.Moves LeanUrat.MovesGr LeanUrat.MovesGr.SideVal

variable {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]

set_option linter.style.longLine false
set_option linter.style.header false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 800000

namespace LeanUrat.MovesGr

/-- The homogeneous multiplicative set `⟨U ∪ {Y}⟩` (`M.homMon`, generated by the `initialForm`s of
`σ.reps` and `σ.Φ`) consists of HOMOGENEOUS elements: each generator is a single-degree
`initialForm = of _ (deg ·) (mkPiece ·)`, `1 = of _ (deg 1) (mkPiece 1)`, and the product of
two single-degree elements is single-degree via `mul_of`/`pmul`. `Submonoid.closure_induction`. -/
theorem L2_homMon_homogeneous (σ : Stage p F) (M : GenuineStageModel σ) : letI := M.Rg.ring; ∀ x ∈ M.homMon, ∃ (γ : ℤ) (c : M.S.grPiece γ), x = DirectSum.of _ γ c := by
  letI := M.Rg.ring
  intro x hx
  rw [M.homMon_gen] at hx
  induction hx using Submonoid.closure_induction with
  | mem g hg =>
      rcases hg with hg | hg
      · rcases hg with ⟨ũ, _, rfl⟩
        exact ⟨_, _, rfl⟩
      · simp only [Set.mem_singleton_iff] at hg
        subst hg
        exact ⟨_, _, rfl⟩
  | one => exact ⟨M.S.deg 1, M.S.mkPiece 1, M.Rg.one_def⟩
  | mul a b _ _ iha ihb =>
      obtain ⟨γ, c, rfl⟩ := iha
      obtain ⟨δ, d, rfl⟩ := ihb
      exact ⟨γ + δ, M.S.pmul γ δ c d, M.Rg.mul_of γ δ c d⟩

end LeanUrat.MovesGr

#print axioms LeanUrat.MovesGr.L2_homMon_homogeneous
