/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib
import LeanUrat.MovesU.Defs
import LeanUrat.MovesS.PowSubst

/-!
# MovesU/O12PoleFree — U-B: the O-12 pole-free theorem's Lean layer

Lean unit U-B of SYNTH4 (`lean/notes/SYNTHESIS_PASS4_2026-08-01.md` §4), dispatched
2026-08-01 (LEANW6).  Source of truth: the VERIFIED O-12 brief
`lean/notes/openmath/O12_phaseB_verifybrief_rev4.md` (V19 + Fable pass 2 clean at the
honest scope).  This module formalizes the brief's ABSTRACT layer — the subring/unit
discipline and the pole-free mechanism — over the corpus vocabulary
(`DefinedAt`, MovesU/Defs.lean:115; `MovesS.powSubst`, the (g5) base change):

* `cycS` — **L7's multiplicative set 𝒮** ⊂ ℚ[q], generated by `q` and `q^c − 1`
  (c ≥ 1); `cycS_eval_pos` = **Lemma L5**'s quantitative form (every member is
  strictly positive at every rational x ≥ 2 — prime powers p^δ included).
* `MemRcyc` — **membership in ℛ := ℚ[q][𝒮⁻¹]** (L7), with the ring-closure lemmas
  (`.add`/`.mul`/`.neg`/`.sub`, `memRcyc_algebraMap`, `memRcyc_inv_cycS`) and
  **L7(ii)** closure under the base change q ↦ q^δ (`MemRcyc.powSubst`, via
  `cycS_expand`: generators map to generators).
* `MemRcyc.definedAt` — **L7(i)**: no member of ℛ has a pole at any rational
  x ≥ 2 (reduced denominator divides an element of 𝒮 — `RatFunc.denom_div_dvd` —
  and 𝒮 is positive there).  `MemRcyc.eval_ne_zero_of_inv` — **L7(iii)'s
  consumption shape**: an ℛ-UNIT evaluates to a NONZERO value at every x ≥ 2.
* `Gram` / `Gram.memRcyc` — **the grammar 𝒢** ((g1)–(g6) of §2.3; (g2)–(g4) are
  `poly`/`invS` composites, (g5) = `subst`, (g6) = `add`/`mul`) and **Theorem 2's
  absorption step**: everything 𝒢 generates lies in ℛ.
* `marginO1/O2/O3` — **Corollary D's margins** as exact-rational arithmetic
  (3/4, 7/8, 6/7 at E ≥ 3, x ≥ 2), plus `eval_ratio` (evaluation of a
  polynomial ratio) tying them to the displayed booking determinants
  `phiO1/phiO2/phiO3` (`phiO*_margin`).
* `AbsSolveTable` — the abstract solve-table family (§1: per block a 1×1-kernel
  determinant Φ_e and a finite entry list E(e)); `AbsSolveTable.RegAt` — the
  (REG-p) clauses (r1)+(r2) at one evaluation point; **the pole-free theorem**
  `AbsSolveTable.regAt_of_discipline` (= O12 Theorem 3's mechanism: ℛ-unit
  determinants + ℛ entries ⟹ (REG) at EVERY rational x ≥ 2) and its prime-power
  form `AbsSolveTable.regAt_primePow` (every prime p, every depth δ ≥ 1).

CONSUMERS STAY PARKED (per the dispatch): the identification of the project's
concrete 𝔅_n tables with an `AbsSolveTable` satisfying `RcycDiscipline` is the
instance-pin seam (D-11/OL-O12-1/OL-O12-2, outside the O-12 claim) — nothing here
touches `RegP`/`RegData` or any existing statement.  Value correctness is likewise
outside (V7-F1 on record).  Lean-core axioms only.
-/

set_option linter.style.longLine false
set_option linter.style.header false
set_option maxHeartbeats 1000000

namespace LeanUrat.MovesU
open Polynomial

/-! ## L7's multiplicative set 𝒮 and Lemma L5's positivity -/

/-- The generator set of 𝒮: the polynomial `q` and the cyclotomic-type binomials
`q^c − 1`, `c ≥ 1` (O12 brief, Lemma L7). -/
noncomputable def cycGens : Set (Polynomial ℚ) :=
  {Polynomial.X} ∪ {P | ∃ c : ℕ, 1 ≤ c ∧ P = Polynomial.X ^ c - 1}

/-- **𝒮** (L7): the multiplicative set generated by `q` and `{q^c − 1 : c ≥ 1}`. -/
noncomputable def cycS : Submonoid (Polynomial ℚ) := Submonoid.closure cycGens

theorem X_mem_cycS : (Polynomial.X : Polynomial ℚ) ∈ cycS :=
  Submonoid.subset_closure (Or.inl rfl)

theorem Xpow_sub_one_mem_cycS {c : ℕ} (hc : 1 ≤ c) :
    (Polynomial.X ^ c - 1 : Polynomial ℚ) ∈ cycS :=
  Submonoid.subset_closure (Or.inr ⟨c, hc, rfl⟩)

theorem Xpow_mem_cycS (b : ℕ) : (Polynomial.X ^ b : Polynomial ℚ) ∈ cycS :=
  pow_mem X_mem_cycS b

/-- **Lemma L5, quantitative form**: every member of 𝒮 is strictly positive at every
rational `x ≥ 2` (each generator is: `x > 0`; `x^c − 1 ≥ 2^c − 1 ≥ 1`). -/
theorem cycS_eval_pos {s : Polynomial ℚ} (hs : s ∈ cycS) {x : ℚ} (hx : 2 ≤ x) :
    0 < s.eval x := by
  induction hs using Submonoid.closure_induction with
  | mem P hP =>
      rcases hP with hX | ⟨c, hc, rfl⟩
      · rw [Set.mem_singleton_iff] at hX
        subst hX
        rw [Polynomial.eval_X]
        linarith
      · simp only [Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X,
          Polynomial.eval_one]
        have h2 : (2 : ℚ) ^ c ≤ x ^ c := by gcongr
        have h3 : (2 : ℚ) ≤ 2 ^ c := by
          calc (2 : ℚ) = 2 ^ 1 := (pow_one 2).symm
          _ ≤ 2 ^ c := by gcongr; norm_num
        linarith
  | one => simp
  | mul a b _ _ ha hb =>
      rw [Polynomial.eval_mul]
      exact mul_pos ha hb

theorem cycS_ne_zero {s : Polynomial ℚ} (hs : s ∈ cycS) : s ≠ 0 := by
  intro h0
  have := cycS_eval_pos hs (le_refl (2 : ℚ))
  rw [h0, Polynomial.eval_zero] at this
  exact lt_irrefl 0 this

/-! ## ℛ = ℚ[q][𝒮⁻¹] (L7) and its ring closure -/

/-- **Membership in L7's subring ℛ = ℚ[q][𝒮⁻¹] ⊂ ℚ(q)**: some 𝒮-multiple of `f` is a
polynomial. -/
def MemRcyc (f : RatFunc ℚ) : Prop :=
  ∃ (P s : Polynomial ℚ), s ∈ cycS ∧
    (algebraMap (Polynomial ℚ) (RatFunc ℚ) s) * f = algebraMap (Polynomial ℚ) (RatFunc ℚ) P

theorem memRcyc_algebraMap (P : Polynomial ℚ) :
    MemRcyc (algebraMap (Polynomial ℚ) (RatFunc ℚ) P) :=
  ⟨P, 1, one_mem cycS, by rw [map_one, one_mul]⟩

theorem memRcyc_zero : MemRcyc 0 := by
  simpa using memRcyc_algebraMap 0

theorem memRcyc_one : MemRcyc 1 := by
  simpa using memRcyc_algebraMap 1

theorem MemRcyc.add {f g : RatFunc ℚ} (hf : MemRcyc f) (hg : MemRcyc g) :
    MemRcyc (f + g) := by
  obtain ⟨P, s, hs, hP⟩ := hf
  obtain ⟨Q, t, ht, hQ⟩ := hg
  refine ⟨t * P + s * Q, s * t, mul_mem hs ht, ?_⟩
  rw [map_mul, map_add, map_mul, map_mul]
  calc algebraMap (Polynomial ℚ) (RatFunc ℚ) s * algebraMap (Polynomial ℚ) (RatFunc ℚ) t * (f + g)
      = algebraMap (Polynomial ℚ) (RatFunc ℚ) t * (algebraMap (Polynomial ℚ) (RatFunc ℚ) s * f)
        + algebraMap (Polynomial ℚ) (RatFunc ℚ) s * (algebraMap (Polynomial ℚ) (RatFunc ℚ) t * g) := by
        ring
    _ = _ := by rw [hP, hQ]

theorem MemRcyc.mul {f g : RatFunc ℚ} (hf : MemRcyc f) (hg : MemRcyc g) :
    MemRcyc (f * g) := by
  obtain ⟨P, s, hs, hP⟩ := hf
  obtain ⟨Q, t, ht, hQ⟩ := hg
  refine ⟨P * Q, s * t, mul_mem hs ht, ?_⟩
  rw [map_mul, map_mul]
  calc algebraMap (Polynomial ℚ) (RatFunc ℚ) s * algebraMap (Polynomial ℚ) (RatFunc ℚ) t * (f * g)
      = (algebraMap (Polynomial ℚ) (RatFunc ℚ) s * f)
        * (algebraMap (Polynomial ℚ) (RatFunc ℚ) t * g) := by ring
    _ = _ := by rw [hP, hQ]

theorem MemRcyc.neg {f : RatFunc ℚ} (hf : MemRcyc f) : MemRcyc (-f) := by
  obtain ⟨P, s, hs, hP⟩ := hf
  exact ⟨-P, s, hs, by rw [map_neg, mul_neg, hP]⟩

theorem MemRcyc.sub {f g : RatFunc ℚ} (hf : MemRcyc f) (hg : MemRcyc g) :
    MemRcyc (f - g) := by
  rw [sub_eq_add_neg]
  exact hf.add hg.neg

/-- Inverses of 𝒮 members lie in ℛ (the localization's defining property). -/
theorem memRcyc_inv_cycS {s : Polynomial ℚ} (hs : s ∈ cycS) :
    MemRcyc (algebraMap (Polynomial ℚ) (RatFunc ℚ) s)⁻¹ :=
  ⟨1, s, hs, by
    rw [mul_inv_cancel₀ (RatFunc.algebraMap_ne_zero (cycS_ne_zero hs)), map_one]⟩

/-! ## L7(i): no poles at rational x ≥ 2 -/

/-- Every ℛ member is a ratio of a polynomial by an 𝒮 member. -/
theorem MemRcyc.eq_div {f : RatFunc ℚ} (hf : MemRcyc f) :
    ∃ (P s : Polynomial ℚ), s ∈ cycS ∧
      f = algebraMap (Polynomial ℚ) (RatFunc ℚ) P / algebraMap (Polynomial ℚ) (RatFunc ℚ) s := by
  obtain ⟨P, s, hs, hP⟩ := hf
  have hsne : algebraMap (Polynomial ℚ) (RatFunc ℚ) s ≠ 0 :=
    RatFunc.algebraMap_ne_zero (cycS_ne_zero hs)
  exact ⟨P, s, hs, by rw [eq_div_iff hsne, mul_comm]; exact hP⟩

/-- **L7(i)** at the corpus vocabulary: an ℛ member is `DefinedAt` every rational
`x ≥ 2` — its reduced denominator divides an 𝒮 member (`RatFunc.denom_div_dvd`),
which is strictly positive there (L5). -/
theorem MemRcyc.definedAt {f : RatFunc ℚ} (hf : MemRcyc f) {x : ℚ} (hx : 2 ≤ x) :
    DefinedAt f x := by
  obtain ⟨P, s, hs, rfl⟩ := hf.eq_div
  obtain ⟨u, hu⟩ := RatFunc.denom_div_dvd P s
  have hpos := cycS_eval_pos hs hx
  rw [hu, Polynomial.eval_mul] at hpos
  intro h0
  rw [h0, zero_mul] at hpos
  exact lt_irrefl 0 hpos

/-- **L7(iii)'s consumption shape (the (r1) channel)**: a nonzero `f` with BOTH
`f` and `f⁻¹` in ℛ (an ℛ-unit) evaluates to a NONZERO value at every rational
`x ≥ 2` (its value times the inverse's value is 1). -/
theorem MemRcyc.eval_ne_zero_of_inv {f : RatFunc ℚ} (hf : MemRcyc f)
    (hfi : MemRcyc f⁻¹) (hf0 : f ≠ 0) {x : ℚ} (hx : 2 ≤ x) :
    f.eval (RingHom.id ℚ) x ≠ 0 := by
  have h1 : Polynomial.eval₂ (RingHom.id ℚ) x f.denom ≠ 0 := by
    rw [Polynomial.eval₂_id]
    exact hf.definedAt hx
  have h2 : Polynomial.eval₂ (RingHom.id ℚ) x (f⁻¹).denom ≠ 0 := by
    rw [Polynomial.eval₂_id]
    exact hfi.definedAt hx
  have hmul := RatFunc.eval_mul (f := RingHom.id ℚ) (a := x) h1 h2
  rw [mul_inv_cancel₀ hf0] at hmul
  intro h0
  rw [h0, zero_mul, RatFunc.eval_one] at hmul
  exact one_ne_zero hmul

/-! ## L7(ii): closure under the base change q ↦ q^δ ((g5), `MovesS.powSubst`) -/

/-- 𝒮 is closed under `q ↦ q^d` for `d ≥ 1`: generators map to generators
(`q ↦ q^d`; `q^c − 1 ↦ q^{cd} − 1`). -/
theorem cycS_expand {s : Polynomial ℚ} (hs : s ∈ cycS) {d : ℕ} (hd : 1 ≤ d) :
    Polynomial.expand ℚ d s ∈ cycS := by
  induction hs using Submonoid.closure_induction with
  | mem P hP =>
      rcases hP with hX | ⟨c, hc, rfl⟩
      · rw [Set.mem_singleton_iff] at hX
        subst hX
        rw [Polynomial.expand_X]
        exact Xpow_mem_cycS d
      · rw [map_sub, map_one, map_pow, Polynomial.expand_X, ← pow_mul]
        exact Xpow_sub_one_mem_cycS (Nat.one_le_iff_ne_zero.mpr
          (Nat.mul_ne_zero (by omega) (by omega)))
  | one => rw [map_one]; exact one_mem cycS
  | mul a b _ _ ha hb => rw [map_mul]; exact mul_mem ha hb

/-- `powSubst` acts on polynomial images as `Polynomial.expand` (the defining
equation of the (g5) base change). -/
theorem powSubst_algebraMap (δ : ℕ+) (P : Polynomial ℚ) :
    MovesS.powSubst δ (algebraMap (Polynomial ℚ) (RatFunc ℚ) P)
      = algebraMap (Polynomial ℚ) (RatFunc ℚ) (Polynomial.expand ℚ (δ : ℕ) P) := by
  rw [MovesS.powSubst, IsFractionRing.lift_algebraMap]
  rfl

/-- **L7(ii)**: ℛ is closed under every base change q ↦ q^δ, δ ≥ 1. -/
theorem MemRcyc.powSubst {f : RatFunc ℚ} (hf : MemRcyc f) (δ : ℕ+) :
    MemRcyc (MovesS.powSubst δ f) := by
  obtain ⟨P, s, hs, hP⟩ := hf
  refine ⟨Polynomial.expand ℚ (δ : ℕ) P, Polynomial.expand ℚ (δ : ℕ) s,
    cycS_expand hs δ.pos, ?_⟩
  have h := congrArg (MovesS.powSubst δ) hP
  rw [map_mul, powSubst_algebraMap, powSubst_algebraMap] at h
  exact h

/-! ## The grammar 𝒢 ((g1)–(g6) of §2.3) and Theorem 2's absorption step -/

/-- **The generation grammar 𝒢** (O12 brief §2.3, the proof device of Theorem 2):
(g1) = `poly`; the (g2)/(g3)/(g4) normalizations, volumes and geometric depth
closures are `poly`/`invS` composites under (g6) (each is `A · P · s⁻¹` with
`s ∈ 𝒮` — e.g. `q^{-b} = 1·(X^b)⁻¹`, `(q^d − q^{d-1})⁻¹ = (X^{d-1}·(X−1))⁻¹`,
`A·q^c/(q^c−1) = A·X^c·((X^c−1))⁻¹`); (g5) = `subst`; (g6) = `add`/`mul` (+ `neg`
for signed bookkeeping).  The block solve (g7) divides by the UNIT
`u ∈ {1 − q^{1−E}, 1 − q^{−E}}`, i.e. multiplies by `u⁻¹` whose ℛ-membership is
`memRcyc_inv_cycS`-shaped — consumed at the theorem layer, not a constructor. -/
inductive Gram : RatFunc ℚ → Prop
  | poly (P : Polynomial ℚ) : Gram (algebraMap (Polynomial ℚ) (RatFunc ℚ) P)
  | invS {s : Polynomial ℚ} (hs : s ∈ cycS) :
      Gram (algebraMap (Polynomial ℚ) (RatFunc ℚ) s)⁻¹
  | add {f g : RatFunc ℚ} : Gram f → Gram g → Gram (f + g)
  | mul {f g : RatFunc ℚ} : Gram f → Gram g → Gram (f * g)
  | neg {f : RatFunc ℚ} : Gram f → Gram (-f)
  | subst {f : RatFunc ℚ} (δ : ℕ+) : Gram f → Gram (MovesS.powSubst δ f)

/-- **Theorem 2's absorption step**: everything the grammar generates lies in ℛ.
(The instance content of Theorem 2 — that every E(e) member of every 𝔅_n booking
is 𝒢-generated — is the brief's §2.3 bracketed exhibitions, parked with the
instance pin.) -/
theorem Gram.memRcyc {f : RatFunc ℚ} (h : Gram f) : MemRcyc f := by
  induction h with
  | poly P => exact memRcyc_algebraMap P
  | invS hs => exact memRcyc_inv_cycS hs
  | add _ _ ha hb => exact ha.add hb
  | mul _ _ ha hb => exact ha.mul hb
  | neg _ ha => exact ha.neg
  | subst δ _ ha => exact ha.powSubst δ

/-! ## Corollary D's margins (exact rationals) and the ratio-evaluation helper -/

/-- Evaluation of a polynomial ratio at a point where the denominator polynomial is
nonzero: `(P/s)(x) = P(x)/s(x)` (the `RatFunc.eval` junk at poles never fires). -/
theorem eval_ratio {P s : Polynomial ℚ} {x : ℚ} (hsx : s.eval x ≠ 0) :
    (algebraMap (Polynomial ℚ) (RatFunc ℚ) P
        / algebraMap (Polynomial ℚ) (RatFunc ℚ) s).eval (RingHom.id ℚ) x
      = P.eval x / s.eval x := by
  have hs0 : s ≠ 0 := fun h => hsx (by rw [h, Polynomial.eval_zero])
  have hsne : algebraMap (Polynomial ℚ) (RatFunc ℚ) s ≠ 0 :=
    RatFunc.algebraMap_ne_zero hs0
  set f := algebraMap (Polynomial ℚ) (RatFunc ℚ) P
    / algebraMap (Polynomial ℚ) (RatFunc ℚ) s with hf
  -- the ratio's denominator does not vanish at x (it divides s)
  have hdvd : f.denom ∣ s := RatFunc.denom_div_dvd P s
  have hfden : Polynomial.eval₂ (RingHom.id ℚ) x f.denom ≠ 0 := by
    rw [Polynomial.eval₂_id]
    obtain ⟨u, hu⟩ := hdvd
    intro h0
    rw [hu, Polynomial.eval_mul, h0, zero_mul] at hsx
    exact hsx rfl
  have hsden : Polynomial.eval₂ (RingHom.id ℚ) x
      (algebraMap (Polynomial ℚ) (RatFunc ℚ) s).denom ≠ 0 := by
    rw [RatFunc.denom_algebraMap, Polynomial.eval₂_id, Polynomial.eval_one]
    exact one_ne_zero
  -- multiply back: f · s = P, evaluate both sides
  have hmulf : f * algebraMap (Polynomial ℚ) (RatFunc ℚ) s
      = algebraMap (Polynomial ℚ) (RatFunc ℚ) P := by
    rw [hf, div_mul_cancel₀ _ hsne]
  have := RatFunc.eval_mul (f := RingHom.id ℚ) (a := x) hfden hsden
  rw [hmulf, RatFunc.eval_algebraMap, RatFunc.eval_algebraMap,
    Polynomial.eval₂_id, Polynomial.eval₂_id] at this
  simp only [Algebra.algebraMap_self_apply] at this
  rw [eq_div_iff hsx]
  exact this.symm

/-- **Corollary D margin, (O1) shape**: `1 − x^{-m} ≥ 3/4` at `x ≥ 2`, `m ≥ 2`
(the O1 determinant at `m = E − 1`, `E ≥ 3`). -/
theorem marginO1 {x : ℚ} (hx : 2 ≤ x) {m : ℕ} (hm : 2 ≤ m) :
    (3 : ℚ) / 4 ≤ 1 - (x ^ m)⁻¹ := by
  have h4 : (4 : ℚ) ≤ x ^ m := by
    calc (4 : ℚ) = 2 ^ 2 := by norm_num
    _ ≤ 2 ^ m := pow_le_pow_right₀ (by norm_num) hm
    _ ≤ x ^ m := by gcongr
  have hpos : (0 : ℚ) < x ^ m := by positivity
  have hinv : (x ^ m)⁻¹ ≤ (4 : ℚ)⁻¹ := by gcongr
  linarith

/-- **Corollary D margin, (O2)/(O2′) shape**: `1 − x^{-E} ≥ 7/8` at `x ≥ 2`, `E ≥ 3`. -/
theorem marginO2 {x : ℚ} (hx : 2 ≤ x) {E : ℕ} (hE : 3 ≤ E) :
    (7 : ℚ) / 8 ≤ 1 - (x ^ E)⁻¹ := by
  have h8 : (8 : ℚ) ≤ x ^ E := by
    calc (8 : ℚ) = 2 ^ 3 := by norm_num
    _ ≤ 2 ^ E := pow_le_pow_right₀ (by norm_num) hE
    _ ≤ x ^ E := by gcongr
  have hinv : (x ^ E)⁻¹ ≤ (8 : ℚ)⁻¹ := by gcongr
  linarith

/-- **Corollary D margin, (O3) shape**: `1 − (x−1)/(x^E−1) ≥ 6/7` at `x ≥ 2`, `E ≥ 3`
(the brief's chain `(x−1)/(x^E−1) ≤ (x−1)/(x³−1) = 1/(x²+x+1) ≤ 1/7`). -/
theorem marginO3 {x : ℚ} (hx : 2 ≤ x) {E : ℕ} (hE : 3 ≤ E) :
    (6 : ℚ) / 7 ≤ 1 - (x - 1) / (x ^ E - 1) := by
  have hx1 : (0 : ℚ) < x - 1 := by linarith
  have hx3 : x ^ 3 ≤ x ^ E := pow_le_pow_right₀ (by linarith) hE
  have hcube : (x - 1) * (x ^ 2 + x + 1) = x ^ 3 - 1 := by ring
  have h7 : (7 : ℚ) ≤ x ^ 2 + x + 1 := by nlinarith
  have hden : (0 : ℚ) < x ^ E - 1 := by
    have : (8 : ℚ) ≤ x ^ 3 := by nlinarith
    linarith
  have hfrac : (x - 1) / (x ^ E - 1) ≤ 1 / 7 := by
    rw [div_le_div_iff₀ hden (by norm_num)]
    nlinarith
  linarith

/-! ## The four bookings' determinants (Theorem 1(2)/L7(iii)): units with margins -/

/-- A ratio of 𝒮 members is a nonzero ℛ-unit (L7(iii)'s mechanism). -/
theorem unit_of_cycS_ratio {s t : Polynomial ℚ} (hs : s ∈ cycS) (ht : t ∈ cycS) :
    (algebraMap (Polynomial ℚ) (RatFunc ℚ) t / algebraMap (Polynomial ℚ) (RatFunc ℚ) s) ≠ 0
      ∧ MemRcyc (algebraMap (Polynomial ℚ) (RatFunc ℚ) t
          / algebraMap (Polynomial ℚ) (RatFunc ℚ) s)
      ∧ MemRcyc (algebraMap (Polynomial ℚ) (RatFunc ℚ) t
          / algebraMap (Polynomial ℚ) (RatFunc ℚ) s)⁻¹ := by
  have hsne : algebraMap (Polynomial ℚ) (RatFunc ℚ) s ≠ 0 :=
    RatFunc.algebraMap_ne_zero (cycS_ne_zero hs)
  have htne : algebraMap (Polynomial ℚ) (RatFunc ℚ) t ≠ 0 :=
    RatFunc.algebraMap_ne_zero (cycS_ne_zero ht)
  refine ⟨div_ne_zero htne hsne, ⟨t, s, hs, ?_⟩, ?_⟩
  · rw [mul_div_assoc', mul_comm, mul_div_assoc, div_self hsne, mul_one]
  · rw [inv_div]
    exact ⟨s, t, ht, by rw [mul_div_assoc', mul_comm, mul_div_assoc, div_self htne, mul_one]⟩

/-- The (O1) determinant `Φ^{(O1)} = (q^{E−1} − 1)/q^{E−1}` at `m := E − 1`. -/
noncomputable def detO1 (m : ℕ) : RatFunc ℚ :=
  algebraMap (Polynomial ℚ) (RatFunc ℚ) (Polynomial.X ^ m - 1)
    / algebraMap (Polynomial ℚ) (RatFunc ℚ) (Polynomial.X ^ m)

/-- The (O2)/(O2′) determinant `Φ^{(O2)} = (q^E − 1)/q^E`. -/
noncomputable def detO2 (E : ℕ) : RatFunc ℚ := detO1 E

/-- The (O3) determinant `Φ^{(O3)} = (q^E − q)/(q^E − 1)` (`q^E − q = q·(q^{E−1} − 1)`). -/
noncomputable def detO3 (E : ℕ) : RatFunc ℚ :=
  algebraMap (Polynomial ℚ) (RatFunc ℚ) (Polynomial.X * (Polynomial.X ^ (E - 1) - 1))
    / algebraMap (Polynomial ℚ) (RatFunc ℚ) (Polynomial.X ^ E - 1)

/-- L7(iii) for (O1)/(O2)/(O2′): the determinant is a nonzero ℛ-unit (`m ≥ 1`). -/
theorem detO1_unit {m : ℕ} (hm : 1 ≤ m) :
    detO1 m ≠ 0 ∧ MemRcyc (detO1 m) ∧ MemRcyc (detO1 m)⁻¹ :=
  unit_of_cycS_ratio (Xpow_mem_cycS m) (Xpow_sub_one_mem_cycS hm)

/-- L7(iii) for (O3): the determinant is a nonzero ℛ-unit (`E ≥ 2`). -/
theorem detO3_unit {E : ℕ} (hE : 2 ≤ E) :
    detO3 E ≠ 0 ∧ MemRcyc (detO3 E) ∧ MemRcyc (detO3 E)⁻¹ :=
  unit_of_cycS_ratio (Xpow_sub_one_mem_cycS (by omega))
    (mul_mem X_mem_cycS (Xpow_sub_one_mem_cycS (by omega)))

/-- **Corollary D, (O1) row**: `Φ^{(O1)}(x) = 1 − x^{−(E−1)} ≥ 3/4` at `x ≥ 2`,
`E − 1 = m ≥ 2`. -/
theorem detO1_margin {x : ℚ} (hx : 2 ≤ x) {m : ℕ} (hm : 2 ≤ m) :
    (3 : ℚ) / 4 ≤ (detO1 m).eval (RingHom.id ℚ) x := by
  have hxpos : (0 : ℚ) < x ^ m := by positivity
  have heval : (detO1 m).eval (RingHom.id ℚ) x = (x ^ m - 1) / x ^ m := by
    rw [detO1, eval_ratio (by simpa using ne_of_gt hxpos)]
    simp
  rw [heval]
  have h1 : (x ^ m - 1) / x ^ m = 1 - (x ^ m)⁻¹ := by
    field_simp
  rw [h1]
  exact marginO1 hx hm

/-- **Corollary D, (O2)/(O2′) row**: `Φ^{(O2)}(x) = 1 − x^{−E} ≥ 7/8` at `x ≥ 2`, `E ≥ 3`. -/
theorem detO2_margin {x : ℚ} (hx : 2 ≤ x) {E : ℕ} (hE : 3 ≤ E) :
    (7 : ℚ) / 8 ≤ (detO2 E).eval (RingHom.id ℚ) x := by
  have hxpos : (0 : ℚ) < x ^ E := by positivity
  have heval : (detO2 E).eval (RingHom.id ℚ) x = (x ^ E - 1) / x ^ E := by
    rw [detO2, detO1, eval_ratio (by simpa using ne_of_gt hxpos)]
    simp
  rw [heval]
  have h1 : (x ^ E - 1) / x ^ E = 1 - (x ^ E)⁻¹ := by field_simp
  rw [h1]
  exact marginO2 hx hE

/-- **Corollary D, (O3) row**: `Φ^{(O3)}(x) = 1 − (x−1)/(x^E−1) ≥ 6/7` at `x ≥ 2`, `E ≥ 3`. -/
theorem detO3_margin {x : ℚ} (hx : 2 ≤ x) {E : ℕ} (hE : 3 ≤ E) :
    (6 : ℚ) / 7 ≤ (detO3 E).eval (RingHom.id ℚ) x := by
  have hden : (0 : ℚ) < x ^ E - 1 := by
    have h2 : (2 : ℚ) ≤ x ^ E := by
      calc (2 : ℚ) = 2 ^ 1 := (pow_one 2).symm
      _ ≤ 2 ^ E := pow_le_pow_right₀ (by norm_num) (by omega)
      _ ≤ x ^ E := by gcongr
    linarith
  have heval : (detO3 E).eval (RingHom.id ℚ) x = (x * (x ^ (E - 1) - 1)) / (x ^ E - 1) := by
    rw [detO3, eval_ratio (by simpa using ne_of_gt hden)]
    simp
  rw [heval]
  have hxE : x * x ^ (E - 1) = x ^ E := by
    rw [← pow_succ']
    congr 1
    omega
  have h1 : (x * (x ^ (E - 1) - 1)) / (x ^ E - 1) = 1 - (x - 1) / (x ^ E - 1) := by
    rw [div_eq_iff (ne_of_gt hden)]
    field_simp
    nlinarith [hxE]
  rw [h1]
  exact marginO3 hx hE

/-! ## The abstract solve-table family and THE POLE-FREE THEOREM -/

/-- **The abstract solve table** (O12 brief §1): per block a (1×1-kernel) determinant
`Φ_e ∈ ℚ(q)` and a finite entry list `E(e)`.  The four 𝔅_n bookings, with every
composition and allocation datum, present as members of this shape; the
identification is the parked instance pin (OL-O12-1/2, D-11 seam). -/
structure AbsSolveTable where
  /-- number of blocks -/
  nBlocks : ℕ
  /-- the block determinant Φ_e = det(1 − K_e) (1×1 kernels: a scalar) -/
  Phi : Fin nBlocks → RatFunc ℚ
  /-- the entry list E(e) -/
  entries : Fin nBlocks → Finset (RatFunc ℚ)

/-- The (REG) clauses at one evaluation point (brief §1 (r1)+(r2), the corpus
`DefinedAt` reading of MovesU/Defs.lean): every determinant defined and nonzero,
every entry defined. -/
def AbsSolveTable.RegAt (T : AbsSolveTable) (x : ℚ) : Prop :=
  ∀ e : Fin T.nBlocks,
    (DefinedAt (T.Phi e) x ∧ (T.Phi e).eval (RingHom.id ℚ) x ≠ 0) ∧
      ∀ g ∈ T.entries e, DefinedAt g x

/-- **The ℛ-discipline** (L7(iii) + Theorem 2's conclusion shape): every block
determinant is a nonzero ℛ-UNIT, every entry lies in ℛ. -/
def AbsSolveTable.RcycDiscipline (T : AbsSolveTable) : Prop :=
  (∀ e, T.Phi e ≠ 0 ∧ MemRcyc (T.Phi e) ∧ MemRcyc (T.Phi e)⁻¹) ∧
    ∀ e, ∀ g ∈ T.entries e, MemRcyc g

/-- **THE POLE-FREE THEOREM** (O12 Theorem 3's mechanism at the abstract family):
ℛ-discipline ⟹ (REG) at EVERY rational `x ≥ 2` — clause (r1) from the ℛ-unit
evaluation (`MemRcyc.eval_ne_zero_of_inv`), clause (r2) from L7(i)
(`MemRcyc.definedAt`).  No prime, no depth, no booking enters: the failing set
is empty because every evaluation point of every (REG-p) instance is ≥ 2. -/
theorem AbsSolveTable.regAt_of_discipline (T : AbsSolveTable)
    (hT : T.RcycDiscipline) {x : ℚ} (hx : 2 ≤ x) : T.RegAt x := by
  intro e
  obtain ⟨hPhi, hE⟩ := hT
  obtain ⟨h0, hR, hRi⟩ := hPhi e
  exact ⟨⟨hR.definedAt hx, hR.eval_ne_zero_of_inv hRi h0 hx⟩,
    fun g hg => (hE e g hg).definedAt hx⟩

/-- O12 **Theorem 3** shape: (REG-p) holds at EVERY prime `p` and EVERY depth
`δ ≥ 1` (the evaluation points `q₀ = p^δ` are rationals ≥ 2). -/
theorem AbsSolveTable.regAt_primePow (T : AbsSolveTable) (hT : T.RcycDiscipline)
    {p δ : ℕ} (hp : 2 ≤ p) (hδ : 1 ≤ δ) : T.RegAt ((p ^ δ : ℕ) : ℚ) := by
  refine T.regAt_of_discipline hT ?_
  have h2 : (2 : ℕ) ≤ p ^ δ :=
    le_trans hp (Nat.le_self_pow (by omega) p)
  exact_mod_cast h2

end LeanUrat.MovesU

#print axioms LeanUrat.MovesU.cycS_eval_pos
#print axioms LeanUrat.MovesU.MemRcyc.definedAt
#print axioms LeanUrat.MovesU.MemRcyc.eval_ne_zero_of_inv
#print axioms LeanUrat.MovesU.MemRcyc.powSubst
#print axioms LeanUrat.MovesU.Gram.memRcyc
#print axioms LeanUrat.MovesU.eval_ratio
#print axioms LeanUrat.MovesU.marginO1
#print axioms LeanUrat.MovesU.marginO2
#print axioms LeanUrat.MovesU.marginO3
#print axioms LeanUrat.MovesU.detO1_unit
#print axioms LeanUrat.MovesU.detO3_unit
#print axioms LeanUrat.MovesU.detO1_margin
#print axioms LeanUrat.MovesU.detO2_margin
#print axioms LeanUrat.MovesU.detO3_margin
#print axioms LeanUrat.MovesU.AbsSolveTable.regAt_of_discipline
#print axioms LeanUrat.MovesU.AbsSolveTable.regAt_primePow
