/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib

/-!
# F-B1 — LinearFiber: fiber counts of a linear map over `ZMod (p ^ N)`

For a square matrix `M` over `ZMod (p ^ N)` whose determinant is `p ^ c * u` for a unit `u`
with `c < N` (the "lift-robust" hypothesis: the `p`-valuation of any lift of `det M` is then
exactly `c`), the map `x ↦ M *ᵥ x` on `(Fin n → ZMod (p ^ N))` has

* kernel of size exactly `p ^ c`                       (`card_ker_mulVec_of_det`),
* fibers over image points of size exactly `p ^ c`     (`fiber_card`),
* image of index `p ^ c`                               (`image_index`),

packaged in `mulVec_fiber_card_of_det`, with the degenerate observations
`c = 0 ↔ IsUnit M.det ↔ IsUnit M ↔ Function.Bijective M.mulVec`
(`c_eq_zero_iff_isUnit_det`, `c_eq_zero_iff_isUnit`, `mulVec_bijective_iff_isUnit_det`).

**Route (ii) of the blueprint**: direct Gaussian elimination over the local ring `ZMod (p ^ N)`
(every nonzero element is `p ^ v * unit` with `v < N`; an entry of minimal valuation divides all
entries and can be used as a pivot after row/column swaps; clearing its row and column is
multiplication by explicit square-zero-perturbations of `1`, which are units; then the count
splits off one coordinate and induction applies).  No Smith normal form import is needed.

The per-coordinate atoms (independent of the matrix machinery):

* `card_range_mul_pow : Nat.card (range (p ^ v * ·)) = p ^ (N - min v N)`
* `card_ker_mul_pow   : Nat.card {x // p ^ v * x = 0} = p ^ (min v N)`

This is blueprint item F-B1 (count form; everything is `Nat.card`, no measure theory).
-/

set_option linter.style.longLine false

namespace LeanUrat.OM.LinearFiber

open Matrix

variable {p : ℕ} [hp : Fact p.Prime] {N : ℕ}

instance instNeZeroPPow : NeZero (p ^ N) := ⟨pow_ne_zero N hp.out.ne_zero⟩

/-! ## Valuation toolkit for `ZMod (p ^ N)` -/

/-- `p` is not a unit in `ZMod (p ^ N)` when `0 < N` (it is nilpotent there). -/
theorem not_isUnit_cast_p (hN : 0 < N) : ¬IsUnit (p : ZMod (p ^ N)) := by
  haveI : Fact (1 < p ^ N) := ⟨Nat.one_lt_pow hN.ne' hp.out.one_lt⟩
  intro h
  have hpow : (p : ZMod (p ^ N)) ^ N = 0 := by
    rw [← Nat.cast_pow, ZMod.natCast_self]
  have h0 : IsUnit (0 : ZMod (p ^ N)) := hpow ▸ h.pow N
  exact zero_ne_one (isUnit_zero_iff.mp h0)

/-- No unit of `ZMod (p ^ N)` is divisible by `p` (for `0 < N`). -/
theorem not_dvd_of_isUnit (hN : 0 < N) {x : ZMod (p ^ N)} (hx : IsUnit x) :
    ¬(p : ZMod (p ^ N)) ∣ x := fun hdvd =>
  not_isUnit_cast_p hN (isUnit_of_dvd_unit hdvd hx)

/-- `p ^ c ≠ 0` in `ZMod (p ^ N)` when `c < N`. -/
theorem pow_cast_ne_zero {c : ℕ} (hc : c < N) : ((p : ZMod (p ^ N)) ^ c) ≠ 0 := by
  rw [← Nat.cast_pow, Ne, CharP.cast_eq_zero_iff (ZMod (p ^ N)) (p ^ N)]
  intro hdvd
  have h1 : p ^ N ≤ p ^ c := Nat.le_of_dvd (pow_pos hp.out.pos c) hdvd
  have h2 : p ^ c < p ^ N := (Nat.pow_lt_pow_iff_right hp.out.one_lt).mpr hc
  omega

/-- The annihilator of `p ^ c` in `ZMod (p ^ N)` is generated by `p ^ (N - c)`:
if `p ^ c * x = 0` then `x` is a multiple of `p ^ (N - c)`. -/
theorem exists_mul_pow_of_pow_mul_eq_zero {c : ℕ} (hcN : c ≤ N) {x : ZMod (p ^ N)}
    (h : (p : ZMod (p ^ N)) ^ c * x = 0) :
    ∃ y : ZMod (p ^ N), x = (p : ZMod (p ^ N)) ^ (N - c) * y := by
  have hx : ((x.val : ℕ) : ZMod (p ^ N)) = x := ZMod.natCast_rightInverse x
  rw [← hx, ← Nat.cast_pow, ← Nat.cast_mul,
    CharP.cast_eq_zero_iff (ZMod (p ^ N)) (p ^ N)] at h
  obtain ⟨k, hk⟩ : p ^ (N - c) ∣ x.val := by
    have h' : p ^ c * p ^ (N - c) ∣ p ^ c * x.val := by
      calc p ^ c * p ^ (N - c) = p ^ N := by rw [← pow_add]; congr 1; omega
      _ ∣ p ^ c * x.val := h
    exact (mul_dvd_mul_iff_left (a := p ^ c) (pow_ne_zero _ hp.out.ne_zero)).mp h'
  refine ⟨(k : ZMod (p ^ N)), ?_⟩
  rw [← hx, hk, Nat.cast_mul, Nat.cast_pow]

/-- Auxiliary valuation on `ZMod (p ^ N)`: `N` at `0`, else the `p`-adic valuation of the
canonical (least nonnegative) lift. -/
def pval (x : ZMod (p ^ N)) : ℕ := if x = 0 then N else (x.val).factorization p

omit hp in
@[simp] theorem pval_zero : pval (0 : ZMod (p ^ N)) = N := if_pos rfl

/-- Unit decomposition: every nonzero `x : ZMod (p ^ N)` is `p ^ pval x * u` with `u` a unit
and `pval x < N`. -/
theorem pval_spec {x : ZMod (p ^ N)} (hx : x ≠ 0) :
    pval x < N ∧ ∃ u : (ZMod (p ^ N))ˣ, x = (p : ZMod (p ^ N)) ^ pval x * u := by
  have hval : x.val ≠ 0 := fun h => hx ((ZMod.val_eq_zero x).mp h)
  have hpv : pval x = (x.val).factorization p := if_neg hx
  obtain ⟨m, hpm, hvm⟩ : ∃ m, ¬p ∣ m ∧ p ^ (x.val).factorization p * m = x.val :=
    ⟨x.val / p ^ (x.val).factorization p, Nat.not_dvd_ordCompl hp.out hval,
      Nat.ordProj_mul_ordCompl_eq_self x.val p⟩
  have hcop : Nat.Coprime m (p ^ N) :=
    Nat.Coprime.pow_right N (((Nat.Prime.coprime_iff_not_dvd hp.out).mpr hpm).symm)
  have hxeq : ((x.val : ℕ) : ZMod (p ^ N)) = x := ZMod.natCast_rightInverse x
  constructor
  · have h1 : p ^ (x.val).factorization p ≤ x.val :=
      Nat.le_of_dvd (Nat.pos_of_ne_zero hval) (Nat.ordProj_dvd x.val p)
    have h2 : x.val < p ^ N := ZMod.val_lt x
    rw [hpv]
    exact (Nat.pow_lt_pow_iff_right hp.out.one_lt).mp (lt_of_le_of_lt h1 h2)
  · refine ⟨ZMod.unitOfCoprime m hcop, ?_⟩
    rw [ZMod.coe_unitOfCoprime, hpv]
    calc x = ((x.val : ℕ) : ZMod (p ^ N)) := hxeq.symm
      _ = ((p ^ (x.val).factorization p * m : ℕ) : ZMod (p ^ N)) := by rw [hvm]
      _ = (p : ZMod (p ^ N)) ^ (x.val).factorization p * (m : ZMod (p ^ N)) := by
          push_cast; ring

/-- Divisibility from valuation comparison: a nonzero element of minimal valuation divides. -/
theorem dvd_of_pval_le {x y : ZMod (p ^ N)} (hx : x ≠ 0) (hle : pval x ≤ pval y) : x ∣ y := by
  by_cases hy : y = 0
  · simp [hy]
  obtain ⟨-, ux, hux⟩ := pval_spec hx
  obtain ⟨-, uy, huy⟩ := pval_spec hy
  have h1 : x ∣ (p : ZMod (p ^ N)) ^ pval x := by
    refine ⟨(ux⁻¹ : (ZMod (p ^ N))ˣ), ?_⟩
    calc (p : ZMod (p ^ N)) ^ pval x
        = (p : ZMod (p ^ N)) ^ pval x * ((ux : ZMod (p ^ N)) * (ux⁻¹ : (ZMod (p ^ N))ˣ)) := by
          rw [Units.mul_inv, mul_one]
      _ = ((p : ZMod (p ^ N)) ^ pval x * (ux : ZMod (p ^ N))) * (ux⁻¹ : (ZMod (p ^ N))ˣ) := by
          rw [mul_assoc]
      _ = x * (ux⁻¹ : (ZMod (p ^ N))ˣ) := by rw [← hux]
  have h2 : (p : ZMod (p ^ N)) ^ pval x ∣ (p : ZMod (p ^ N)) ^ pval y := pow_dvd_pow _ hle
  have h3 : (p : ZMod (p ^ N)) ^ pval y ∣ y := ⟨uy, huy⟩
  exact h1.trans (h2.trans h3)

/-- Valuation comparison from a `p ^ v * x = p ^ c * u` relation (with `u` a unit, `c < N`):
necessarily `v ≤ c`. -/
theorem le_of_pow_mul_eq_pow_mul_unit {v c : ℕ} (hcN : c < N) {x : ZMod (p ^ N)}
    {u : (ZMod (p ^ N))ˣ}
    (h : (p : ZMod (p ^ N)) ^ v * x = (p : ZMod (p ^ N)) ^ c * u) : v ≤ c := by
  by_contra hvc
  rw [not_le] at hvc
  have hsplit : (p : ZMod (p ^ N)) ^ v
      = (p : ZMod (p ^ N)) ^ c * (p : ZMod (p ^ N)) ^ (v - c) := by
    rw [← pow_add]; congr 1; omega
  have h0 : (p : ZMod (p ^ N)) ^ c * ((p : ZMod (p ^ N)) ^ (v - c) * x - u) = 0 := by
    rw [mul_sub, ← mul_assoc, ← hsplit, h, sub_self]
  obtain ⟨y, hy⟩ := exists_mul_pow_of_pow_mul_eq_zero hcN.le h0
  have hu : (u : ZMod (p ^ N))
      = (p : ZMod (p ^ N)) ^ (v - c) * x - (p : ZMod (p ^ N)) ^ (N - c) * y := by
    rw [← hy]; ring
  have hdvd : (p : ZMod (p ^ N)) ∣ (u : ZMod (p ^ N)) := by
    rw [hu]
    exact dvd_sub (dvd_mul_of_dvd_left (dvd_pow_self _ (by omega : v - c ≠ 0)) x)
      (dvd_mul_of_dvd_left (dvd_pow_self _ (by omega : N - c ≠ 0)) y)
  exact not_dvd_of_isUnit (by omega : 0 < N) u.isUnit hdvd

/-- Cancellation of `p ^ v` from `p ^ v * x = p ^ c * u` (with `v ≤ c < N`, `u` a unit):
`x` is `p ^ (c - v)` times a unit. -/
theorem exists_unit_pow_sub_of_pow_mul_eq {v c : ℕ} (hvc : v ≤ c) (hcN : c < N)
    {x : ZMod (p ^ N)} {u : (ZMod (p ^ N))ˣ}
    (h : (p : ZMod (p ^ N)) ^ v * x = (p : ZMod (p ^ N)) ^ c * u) :
    ∃ w : (ZMod (p ^ N))ˣ, x = (p : ZMod (p ^ N)) ^ (c - v) * w := by
  have h0 : (p : ZMod (p ^ N)) ^ v * (x - (p : ZMod (p ^ N)) ^ (c - v) * u) = 0 := by
    rw [mul_sub, ← mul_assoc, ← pow_add]
    have hvcv : v + (c - v) = c := by omega
    rw [hvcv, h, sub_self]
  obtain ⟨y, hy⟩ := exists_mul_pow_of_pow_mul_eq_zero (by omega : v ≤ N) h0
  have hxy : x = (p : ZMod (p ^ N)) ^ (c - v)
      * ((u : ZMod (p ^ N)) + (p : ZMod (p ^ N)) ^ (N - c) * y) := by
    have hsplit : (p : ZMod (p ^ N)) ^ (N - v)
        = (p : ZMod (p ^ N)) ^ (c - v) * (p : ZMod (p ^ N)) ^ (N - c) := by
      rw [← pow_add]; congr 1; omega
    have hx' : x = (p : ZMod (p ^ N)) ^ (N - v) * y + (p : ZMod (p ^ N)) ^ (c - v) * u :=
      sub_eq_iff_eq_add.mp hy
    rw [hx', hsplit]; ring
  have hnil : IsNilpotent ((p : ZMod (p ^ N)) ^ (N - c) * y) := by
    refine ⟨N, ?_⟩
    rw [mul_pow, ← pow_mul]
    have hle : N ≤ (N - c) * N := by
      calc N = 1 * N := (one_mul N).symm
      _ ≤ (N - c) * N := Nat.mul_le_mul_right N (by omega)
    have hz : (p : ZMod (p ^ N)) ^ ((N - c) * N) = 0 := by
      rw [← Nat.cast_pow, CharP.cast_eq_zero_iff (ZMod (p ^ N)) (p ^ N)]
      exact pow_dvd_pow p hle
    rw [hz, zero_mul]
  have hunit : IsUnit ((u : ZMod (p ^ N)) + (p : ZMod (p ^ N)) ^ (N - c) * y) :=
    hnil.isUnit_add_left_of_commute u.isUnit (Commute.all _ _)
  exact ⟨hunit.unit, by rw [hxy, IsUnit.unit_spec]⟩

/-! ## The per-coordinate atoms -/

/-- **Atom (range).** Multiplication by `p ^ v` on `ZMod (p ^ N)` has image of size
`p ^ (N - min v N)`. -/
theorem card_range_mul_pow (v : ℕ) :
    Nat.card (Set.range (fun x : ZMod (p ^ N) => (p : ZMod (p ^ N)) ^ v * x))
      = p ^ (N - min v N) := by
  have hgcd : (p ^ N).gcd (p ^ v) = p ^ min v N := by
    rcases le_total v N with h | h
    · rw [min_eq_left h]
      exact Nat.gcd_eq_right (pow_dvd_pow p h)
    · rw [min_eq_right h]
      exact Nat.gcd_eq_left (pow_dvd_pow p h)
  have hrange : Nat.card (Set.range (fun x : ZMod (p ^ N) => (p : ZMod (p ^ N)) ^ v * x))
      = Nat.card (AddSubgroup.zmultiples ((p : ZMod (p ^ N)) ^ v)) := by
    refine Nat.card_congr (Equiv.subtypeEquivRight fun y => ?_)
    simp only [Set.mem_range, AddSubgroup.mem_zmultiples_iff]
    constructor
    · rintro ⟨x, rfl⟩
      refine ⟨(x.val : ℤ), ?_⟩
      rw [zsmul_eq_mul, Int.cast_natCast, ZMod.natCast_rightInverse x, mul_comm]
    · rintro ⟨k, rfl⟩
      exact ⟨(k : ZMod (p ^ N)), by rw [zsmul_eq_mul, mul_comm]⟩
  rw [hrange, Nat.card_zmultiples, ← Nat.cast_pow,
    ZMod.addOrderOf_coe _ (NeZero.ne (p ^ N)), hgcd,
    Nat.pow_div (min_le_right v N) hp.out.pos]

/-- **Atom (kernel).** Multiplication by `p ^ v` on `ZMod (p ^ N)` has kernel of size
`p ^ min v N`. -/
theorem card_ker_mul_pow (v : ℕ) :
    Nat.card {x : ZMod (p ^ N) // (p : ZMod (p ^ N)) ^ v * x = 0} = p ^ min v N := by
  set f : ZMod (p ^ N) →+ ZMod (p ^ N) := AddMonoidHom.mulLeft ((p : ZMod (p ^ N)) ^ v) with hf
  have h1 : Nat.card (ZMod (p ^ N)) = Nat.card (ZMod (p ^ N) ⧸ f.ker) * Nat.card f.ker :=
    AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup f.ker
  have h2 : Nat.card (ZMod (p ^ N) ⧸ f.ker) = Nat.card f.range :=
    Nat.card_congr (QuotientAddGroup.quotientKerEquivRange f).toEquiv
  have h3 : Nat.card f.range = p ^ (N - min v N) := by
    rw [← card_range_mul_pow (p := p) (N := N) v]
    refine Nat.card_congr (Equiv.subtypeEquivRight fun y => ?_)
    simp [hf, AddMonoidHom.mem_range, Set.mem_range, eq_comm]
  have h4 : Nat.card f.ker
      = Nat.card {x : ZMod (p ^ N) // (p : ZMod (p ^ N)) ^ v * x = 0} := by
    refine Nat.card_congr (Equiv.subtypeEquivRight fun x => ?_)
    simp [hf, AddMonoidHom.mem_ker]
  rw [h2, h3, h4] at h1
  rw [Nat.card_zmod] at h1
  have hsum : p ^ (N - min v N) * p ^ min v N = p ^ N := by
    rw [← pow_add]; congr 1; omega
  have key : p ^ (N - min v N)
        * Nat.card {x : ZMod (p ^ N) // (p : ZMod (p ^ N)) ^ v * x = 0}
      = p ^ (N - min v N) * p ^ min v N := by
    rw [← h1, hsum]
  exact Nat.eq_of_mul_eq_mul_left (pow_pos hp.out.pos _) key

/-! ## Generic kernel-count moves (any commutative ring) -/

section GenericMoves

variable {R : Type*} [CommRing R]

/-- Reindexing rows and columns by equivalences preserves the kernel count. -/
theorem card_ker_reindex {n : ℕ} (M : Matrix (Fin n) (Fin n) R) (e₁ e₂ : Fin n ≃ Fin n) :
    Nat.card {x : Fin n → R // (M.submatrix e₁ e₂).mulVec x = 0}
      = Nat.card {x : Fin n → R // M.mulVec x = 0} := by
  refine Nat.card_congr ?_
  refine
    { toFun := fun x => ⟨x.1 ∘ e₂.symm, ?_⟩
      invFun := fun y => ⟨y.1 ∘ e₂, ?_⟩
      left_inv := fun x => Subtype.ext (by
        funext i; simp [Function.comp_apply])
      right_inv := fun y => Subtype.ext (by
        funext i; simp [Function.comp_apply]) }
  · have hx := x.2
    rw [Matrix.submatrix_mulVec_equiv] at hx
    funext i
    have := congrFun hx (e₁.symm i)
    simpa using this
  · have hy := y.2
    rw [Matrix.submatrix_mulVec_equiv]
    have hcomp : (y.1 ∘ ⇑e₂) ∘ ⇑e₂.symm = y.1 := by
      funext j; simp [Function.comp_apply]
    rw [hcomp, hy]
    funext i
    simp

/-- Reindexing rows and columns changes the determinant by a unit. -/
theorem det_submatrix_equiv {n : ℕ} (M : Matrix (Fin n) (Fin n) R) (e₁ e₂ : Fin n ≃ Fin n) :
    ∃ ε : Rˣ, (M.submatrix e₁ e₂).det = ε * M.det := by
  have h1 : M.submatrix (⇑e₁) (⇑e₂) = (M.submatrix id (⇑e₂)).submatrix (⇑e₁) id := by
    rw [Matrix.submatrix_submatrix, Function.id_comp, Function.comp_id]
  have h2 : ((M.submatrix id (⇑e₂)).submatrix (⇑e₁) id).det
      = Equiv.Perm.sign e₁ * (M.submatrix id (⇑e₂)).det := Matrix.det_permute e₁ _
  have h3 : (M.submatrix id (⇑e₂)).det = Equiv.Perm.sign e₂ * M.det := Matrix.det_permute' e₂ M
  rcases Int.units_eq_one_or (Equiv.Perm.sign e₁) with hs1 | hs1 <;>
    rcases Int.units_eq_one_or (Equiv.Perm.sign e₂) with hs2 | hs2 <;>
    rw [hs1] at h2 <;> rw [hs2] at h3
  · exact ⟨1, by rw [h1, h2, h3]; simp⟩
  · exact ⟨-1, by rw [h1, h2, h3]; simp⟩
  · exact ⟨-1, by rw [h1, h2, h3]; simp⟩
  · exact ⟨1, by rw [h1, h2, h3]; simp⟩

/-- Left multiplication by a matrix with a (two-sided) inverse preserves the kernel count. -/
theorem card_ker_mul_left {n : ℕ} {L L' B : Matrix (Fin n) (Fin n) R} (hL : L' * L = 1) :
    Nat.card {x : Fin n → R // (L * B).mulVec x = 0}
      = Nat.card {x : Fin n → R // B.mulVec x = 0} := by
  refine Nat.card_congr (Equiv.subtypeEquivRight fun x => ?_)
  constructor
  · intro h
    have h2 : L'.mulVec ((L * B).mulVec x) = 0 := by rw [h, Matrix.mulVec_zero]
    rwa [Matrix.mulVec_mulVec, ← Matrix.mul_assoc, hL, Matrix.one_mul] at h2
  · intro h
    rw [← Matrix.mulVec_mulVec, h, Matrix.mulVec_zero]

/-- Right multiplication by a matrix with a two-sided inverse preserves the kernel count. -/
theorem card_ker_mul_right {n : ℕ} {B Q Q' : Matrix (Fin n) (Fin n) R}
    (hQ : Q * Q' = 1) (hQ' : Q' * Q = 1) :
    Nat.card {x : Fin n → R // (B * Q).mulVec x = 0}
      = Nat.card {x : Fin n → R // B.mulVec x = 0} := by
  refine Nat.card_congr ?_
  refine
    { toFun := fun x => ⟨Q.mulVec x.1, ?_⟩
      invFun := fun y => ⟨Q'.mulVec y.1, ?_⟩
      left_inv := fun x => Subtype.ext (by
        show Q'.mulVec (Q.mulVec x.1) = x.1
        rw [Matrix.mulVec_mulVec, hQ', Matrix.one_mulVec])
      right_inv := fun y => Subtype.ext (by
        show Q.mulVec (Q'.mulVec y.1) = y.1
        rw [Matrix.mulVec_mulVec, hQ, Matrix.one_mulVec]) }
  · rw [Matrix.mulVec_mulVec]
    exact x.2
  · rw [Matrix.mulVec_mulVec, Matrix.mul_assoc, hQ, Matrix.mul_one]
    exact y.2

/-- `(1 - u) * (1 + u) = 1 = (1 + u) * (1 - u)` for a square-zero matrix `u`. -/
theorem one_sub_mul_one_add_of_sq {n : Type*} [Fintype n] [DecidableEq n]
    {u : Matrix n n R} (h : u * u = 0) :
    (1 - u) * (1 + u) = 1 ∧ (1 + u) * (1 - u) = 1 := by
  constructor
  · have hexp : (1 - u) * (1 + u) = 1 - u * u := by
      rw [sub_mul, one_mul, mul_add, mul_one]
      abel
    rw [hexp, h, sub_zero]
  · have hexp : (1 + u) * (1 - u) = 1 - u * u := by
      rw [add_mul, one_mul, mul_sub, mul_one]
      abel
    rw [hexp, h, sub_zero]

/-- The row-clearing perturbation acts entrywise as `B i j - q i * B 0 j`. -/
theorem clearL_mul {n : ℕ} (q : Fin (n + 1) → R) (B : Matrix (Fin (n + 1)) (Fin (n + 1)) R) :
    (1 - Matrix.vecMulVec q (Pi.single (0 : Fin (n + 1)) (1 : R))) * B
      = Matrix.of fun i j => B i j - q i * B 0 j := by
  rw [sub_mul, Matrix.one_mul]
  ext i j
  rw [Matrix.sub_apply, Matrix.of_apply]
  congr 1
  rw [Matrix.mul_apply]
  rw [Finset.sum_eq_single (0 : Fin (n + 1))]
  · rw [Matrix.vecMulVec_apply, Pi.single_eq_same, mul_one]
  · intro k _ hk
    rw [Matrix.vecMulVec_apply, Pi.single_eq_of_ne hk, mul_zero, zero_mul]
  · intro habs
    exact absurd (Finset.mem_univ _) habs

/-- The column-clearing perturbation acts entrywise as `B i j - B i 0 * r j`. -/
theorem mul_clearR {n : ℕ} (r : Fin (n + 1) → R) (B : Matrix (Fin (n + 1)) (Fin (n + 1)) R) :
    B * (1 - Matrix.vecMulVec (Pi.single (0 : Fin (n + 1)) (1 : R)) r)
      = Matrix.of fun i j => B i j - B i 0 * r j := by
  rw [mul_sub, Matrix.mul_one]
  ext i j
  rw [Matrix.sub_apply, Matrix.of_apply]
  congr 1
  rw [Matrix.mul_apply]
  rw [Finset.sum_eq_single (0 : Fin (n + 1))]
  · rw [Matrix.vecMulVec_apply, Pi.single_eq_same, one_mul]
  · intro k _ hk
    rw [Matrix.vecMulVec_apply, Pi.single_eq_of_ne hk, zero_mul, mul_zero]
  · intro habs
    exact absurd (Finset.mem_univ _) habs

/-- The row-clearing perturbation is square-zero when `q 0 = 0`. -/
theorem vecMulVec_single_sq_left {n : ℕ} {q : Fin (n + 1) → R} (hq : q 0 = 0) :
    Matrix.vecMulVec q (Pi.single (0 : Fin (n + 1)) (1 : R))
      * Matrix.vecMulVec q (Pi.single (0 : Fin (n + 1)) (1 : R)) = 0 := by
  ext i j
  rw [Matrix.mul_apply, Matrix.zero_apply]
  refine Finset.sum_eq_zero fun k _ => ?_
  simp only [Matrix.vecMulVec_apply]
  rcases eq_or_ne k (0 : Fin (n + 1)) with rfl | hk
  · rw [hq, zero_mul, mul_zero]
  · rw [Pi.single_eq_of_ne hk, mul_zero, zero_mul]

/-- The column-clearing perturbation is square-zero when `r 0 = 0`. -/
theorem vecMulVec_single_sq_right {n : ℕ} {r : Fin (n + 1) → R} (hr : r 0 = 0) :
    Matrix.vecMulVec (Pi.single (0 : Fin (n + 1)) (1 : R)) r
      * Matrix.vecMulVec (Pi.single (0 : Fin (n + 1)) (1 : R)) r = 0 := by
  ext i j
  rw [Matrix.mul_apply, Matrix.zero_apply]
  refine Finset.sum_eq_zero fun k _ => ?_
  simp only [Matrix.vecMulVec_apply]
  rcases eq_or_ne k (0 : Fin (n + 1)) with rfl | hk
  · rw [hr, mul_zero, zero_mul]
  · rw [Pi.single_eq_of_ne hk, zero_mul, mul_zero]

/-- Kernel count of a matrix with cleared first row and column (off the pivot) splits as
(pivot kernel) × (minor kernel). -/
theorem card_ker_pivot_block {n : ℕ} (A : Matrix (Fin (n + 1)) (Fin (n + 1)) R)
    (hrow : ∀ j, j ≠ 0 → A 0 j = 0) (hcol : ∀ i, i ≠ 0 → A i 0 = 0) :
    Nat.card {x : Fin (n + 1) → R // A.mulVec x = 0}
      = Nat.card {t : R // A 0 0 * t = 0}
        * Nat.card {y : Fin n → R // (A.submatrix Fin.succ Fin.succ).mulVec y = 0} := by
  have hchar : ∀ x : Fin (n + 1) → R, A.mulVec x = 0
      ↔ A 0 0 * x 0 = 0 ∧ (A.submatrix Fin.succ Fin.succ).mulVec (Fin.tail x) = 0 := by
    intro x
    have h0 : A.mulVec x 0 = A 0 0 * x 0 := by
      simp only [Matrix.mulVec, dotProduct]
      rw [Fin.sum_univ_succ]
      have hz : ∀ j : Fin n, A 0 j.succ * x j.succ = 0 := fun j => by
        rw [hrow j.succ (Fin.succ_ne_zero j), zero_mul]
      rw [Finset.sum_eq_zero fun j _ => hz j, add_zero]
    have hs : ∀ i : Fin n,
        A.mulVec x i.succ = (A.submatrix Fin.succ Fin.succ).mulVec (Fin.tail x) i := by
      intro i
      simp only [Matrix.mulVec, dotProduct, Matrix.submatrix_apply, Fin.tail]
      rw [Fin.sum_univ_succ, hcol i.succ (Fin.succ_ne_zero i), zero_mul, zero_add]
    constructor
    · intro h
      constructor
      · rw [← h0, h, Pi.zero_apply]
      · funext i
        rw [Pi.zero_apply, ← hs i, h, Pi.zero_apply]
    · rintro ⟨h1, h2⟩
      funext i
      refine Fin.cases ?_ (fun i => ?_) i
      · rw [Pi.zero_apply, h0, h1]
      · rw [Pi.zero_apply, hs i, h2, Pi.zero_apply]
  rw [← Nat.card_prod]
  refine Nat.card_congr ?_
  refine
    { toFun := fun x => (⟨x.1 0, ((hchar x.1).mp x.2).1⟩, ⟨Fin.tail x.1, ((hchar x.1).mp x.2).2⟩)
      invFun := fun ty => ⟨Fin.cons ty.1.1 ty.2.1, (hchar _).mpr ⟨?_, ?_⟩⟩
      left_inv := fun x => Subtype.ext (Fin.cons_self_tail x.1)
      right_inv := fun ty => ?_ }
  · rw [Fin.cons_zero]
    exact ty.1.2
  · rw [Fin.tail_cons]
    exact ty.2.2
  · refine Prod.ext (Subtype.ext ?_) (Subtype.ext ?_)
    · show (Fin.cons ty.1.1 ty.2.1 : Fin (n + 1) → R) 0 = ty.1.1
      exact Fin.cons_zero _ _
    · show Fin.tail (Fin.cons ty.1.1 ty.2.1 : Fin (n + 1) → R) = ty.2.1
      exact Fin.tail_cons _ _

/-- Determinant of a matrix with cleared first column: pivot times minor. -/
theorem det_pivot_block {n : ℕ} (A : Matrix (Fin (n + 1)) (Fin (n + 1)) R)
    (hcol : ∀ i, i ≠ 0 → A i 0 = 0) :
    A.det = A 0 0 * (A.submatrix Fin.succ Fin.succ).det := by
  rw [Matrix.det_succ_column_zero]
  rw [Finset.sum_eq_single (0 : Fin (n + 1))]
  · rw [Fin.succAbove_zero]
    simp
  · intro i _ hi
    rw [hcol i hi, mul_zero, zero_mul]
  · intro habs
    exact absurd (Finset.mem_univ _) habs

end GenericMoves

/-! ## The core count: kernels over `ZMod (p ^ N)` -/

/-- **F-B1 core.** If `det M = p ^ c * u` with `u` a unit and `c < N`, the kernel of
`x ↦ M *ᵥ x` on `(Fin n → ZMod (p ^ N))` has exactly `p ^ c` elements. -/
theorem card_ker_mulVec_of_det :
    ∀ {n : ℕ} (M : Matrix (Fin n) (Fin n) (ZMod (p ^ N))) {c : ℕ}, c < N →
      (∃ u : (ZMod (p ^ N))ˣ, M.det = (p : ZMod (p ^ N)) ^ c * u) →
      Nat.card {x : Fin n → ZMod (p ^ N) // M.mulVec x = 0} = p ^ c := by
  intro n
  induction n with
  | zero =>
    intro M c hc hdet
    obtain ⟨u, hu⟩ := hdet
    rw [Matrix.det_fin_zero] at hu
    have hcu : IsUnit ((p : ZMod (p ^ N)) ^ c) :=
      isUnit_of_mul_isUnit_left (x := (p : ZMod (p ^ N)) ^ c) (y := (u : ZMod (p ^ N)))
        (by rw [← hu]; exact isUnit_one)
    have hc0 : c = 0 := by
      by_contra hc0
      exact not_isUnit_cast_p (by omega) ((isUnit_pow_iff hc0).mp hcu)
    subst hc0
    rw [pow_zero]
    have hall : ∀ x : Fin 0 → ZMod (p ^ N), M.mulVec x = 0 := by
      intro x
      funext i
      exact i.elim0
    haveI : Nonempty {x : Fin 0 → ZMod (p ^ N) // M.mulVec x = 0} := ⟨⟨0, hall 0⟩⟩
    haveI : Subsingleton {x : Fin 0 → ZMod (p ^ N) // M.mulVec x = 0} :=
      ⟨fun a b => Subtype.ext (Subsingleton.elim a.1 b.1)⟩
    exact Nat.card_unique
  | succ n ih =>
    intro M c hc hdet
    obtain ⟨u, hu⟩ := hdet
    -- pivot of minimal valuation
    obtain ⟨ij₀, -, hmin⟩ := Finset.exists_min_image Finset.univ
      (fun ij : Fin (n + 1) × Fin (n + 1) => pval (M ij.1 ij.2)) ⟨(0, 0), Finset.mem_univ _⟩
    obtain ⟨i₀, j₀⟩ := ij₀
    have hmin' : ∀ i j, pval (M i₀ j₀) ≤ pval (M i j) := fun i j =>
      hmin (i, j) (Finset.mem_univ _)
    have hpiv : M i₀ j₀ ≠ 0 := by
      intro h0
      have hM : M = 0 := by
        ext i j
        by_contra hij
        have h1 : pval (M i j) < N := (pval_spec hij).1
        have h2 : pval (M i₀ j₀) ≤ pval (M i j) := hmin' i j
        rw [h0, pval_zero] at h2
        omega
      rw [hM, Matrix.det_zero ⟨0⟩] at hu
      have hp0 : (p : ZMod (p ^ N)) ^ c = 0 := (Units.mul_left_eq_zero u).mp hu.symm
      exact pow_cast_ne_zero hc hp0
    -- swap the pivot to position (0,0)
    set e₁ : Fin (n + 1) ≃ Fin (n + 1) := Equiv.swap 0 i₀ with he₁
    set e₂ : Fin (n + 1) ≃ Fin (n + 1) := Equiv.swap 0 j₀ with he₂
    set M' := M.submatrix e₁ e₂ with hM'def
    have hM'00 : M' 0 0 = M i₀ j₀ := by
      rw [hM'def, Matrix.submatrix_apply, he₁, he₂, Equiv.swap_apply_left, Equiv.swap_apply_left]
    have hpiv' : M' 0 0 ≠ 0 := by rw [hM'00]; exact hpiv
    have hM'min : ∀ i j, pval (M' 0 0) ≤ pval (M' i j) := by
      intro i j
      rw [hM'00, hM'def, Matrix.submatrix_apply]
      exact hmin' (e₁ i) (e₂ j)
    have hdet' : ∃ u' : (ZMod (p ^ N))ˣ, M'.det = (p : ZMod (p ^ N)) ^ c * u' := by
      obtain ⟨ε, hε⟩ := det_submatrix_equiv M e₁ e₂
      refine ⟨ε * u, ?_⟩
      rw [hM'def, hε, hu, Units.val_mul]
      ring
    have hker' : Nat.card {x : Fin (n + 1) → ZMod (p ^ N) // M'.mulVec x = 0}
        = Nat.card {x : Fin (n + 1) → ZMod (p ^ N) // M.mulVec x = 0} := by
      rw [hM'def]
      exact card_ker_reindex M e₁ e₂
    -- divisibility of all entries by the pivot
    have hdvd : ∀ i j, M' 0 0 ∣ M' i j := fun i j => dvd_of_pval_le hpiv' (hM'min i j)
    -- clearing data
    set q : Fin (n + 1) → ZMod (p ^ N) :=
      fun i => if h : i = 0 then 0 else (hdvd i 0).choose with hqdef
    set r : Fin (n + 1) → ZMod (p ^ N) :=
      fun j => if h : j = 0 then 0 else (hdvd 0 j).choose with hrdef
    have hq0 : q 0 = 0 := by rw [hqdef]; simp
    have hr0 : r 0 = 0 := by rw [hrdef]; simp
    have hqspec : ∀ i, i ≠ 0 → M' i 0 = M' 0 0 * q i := by
      intro i hi
      rw [hqdef]
      simp only [dif_neg hi]
      exact (hdvd i 0).choose_spec
    have hrspec : ∀ j, j ≠ 0 → M' 0 j = M' 0 0 * r j := by
      intro j hj
      rw [hrdef]
      simp only [dif_neg hj]
      exact (hdvd 0 j).choose_spec
    set L : Matrix (Fin (n + 1)) (Fin (n + 1)) (ZMod (p ^ N)) :=
      1 - Matrix.vecMulVec q (Pi.single (0 : Fin (n + 1)) (1 : ZMod (p ^ N))) with hLdef
    set Rc : Matrix (Fin (n + 1)) (Fin (n + 1)) (ZMod (p ^ N)) :=
      1 - Matrix.vecMulVec (Pi.single (0 : Fin (n + 1)) (1 : ZMod (p ^ N))) r with hRcdef
    set M'' := L * M' * Rc with hM''def
    -- entrywise description of M''
    have hM''entries : ∀ i j,
        M'' i j = (M' i j - q i * M' 0 j) - (M' i 0 - q i * M' 0 0) * r j := by
      intro i j
      rw [hM''def, hLdef, hRcdef, clearL_mul, mul_clearR]
      simp [Matrix.of_apply]
    have hM''00 : M'' 0 0 = M' 0 0 := by
      rw [hM''entries 0 0, hq0, hr0]
      ring
    have hM''row : ∀ j, j ≠ 0 → M'' 0 j = 0 := by
      intro j hj
      rw [hM''entries 0 j, hq0, hrspec j hj]
      ring
    have hM''col : ∀ i, i ≠ 0 → M'' i 0 = 0 := by
      intro i hi
      rw [hM''entries i 0, hr0, hqspec i hi]
      ring
    -- kernel counts transported through the unit multiplications
    obtain ⟨hL1, hL2⟩ := one_sub_mul_one_add_of_sq (vecMulVec_single_sq_left hq0)
    obtain ⟨hR1, hR2⟩ := one_sub_mul_one_add_of_sq (vecMulVec_single_sq_right hr0)
    have hL1' : L * (1 + Matrix.vecMulVec q (Pi.single (0 : Fin (n + 1)) (1 : ZMod (p ^ N)))) = 1 := by
      rw [hLdef]; exact hL1
    have hL2' : (1 + Matrix.vecMulVec q (Pi.single (0 : Fin (n + 1)) (1 : ZMod (p ^ N)))) * L = 1 := by
      rw [hLdef]; exact hL2
    have hR1' : Rc * (1 + Matrix.vecMulVec (Pi.single (0 : Fin (n + 1)) (1 : ZMod (p ^ N))) r) = 1 := by
      rw [hRcdef]; exact hR1
    have hR2' : (1 + Matrix.vecMulVec (Pi.single (0 : Fin (n + 1)) (1 : ZMod (p ^ N))) r) * Rc = 1 := by
      rw [hRcdef]; exact hR2
    have hkerM'' : Nat.card {x : Fin (n + 1) → ZMod (p ^ N) // M''.mulVec x = 0}
        = Nat.card {x : Fin (n + 1) → ZMod (p ^ N) // M'.mulVec x = 0} := by
      rw [hM''def]
      rw [card_ker_mul_right hR1' hR2']
      exact card_ker_mul_left hL2'
    -- determinant of M'' still has the p^c * unit shape
    have hdet'' : ∃ u'' : (ZMod (p ^ N))ˣ, M''.det = (p : ZMod (p ^ N)) ^ c * u'' := by
      have hLu : IsUnit L.det :=
        IsUnit.of_mul_eq_one _ (by rw [← Matrix.det_mul, hL1', Matrix.det_one])
      have hRu : IsUnit Rc.det :=
        IsUnit.of_mul_eq_one _ (by rw [← Matrix.det_mul, hR1', Matrix.det_one])
      obtain ⟨u', hu'⟩ := hdet'
      refine ⟨hLu.unit * u' * hRu.unit, ?_⟩
      rw [hM''def, Matrix.det_mul, Matrix.det_mul, hu', Units.val_mul, Units.val_mul,
        IsUnit.unit_spec, IsUnit.unit_spec]
      ring
    -- block decomposition
    have hblock := card_ker_pivot_block M'' hM''row hM''col
    have hdetblock := det_pivot_block M'' hM''col
    -- valuation bookkeeping (with the valuation of the pivot made opaque, so that
    -- rewriting `M' 0 0` cannot disturb dependent occurrences)
    obtain ⟨v₀, hv₀N, u₀, hu₀⟩ :
        ∃ v₀, v₀ < N ∧ ∃ u₀ : (ZMod (p ^ N))ˣ, M' 0 0 = (p : ZMod (p ^ N)) ^ v₀ * u₀ :=
      ⟨pval (M' 0 0), (pval_spec hpiv').1, (pval_spec hpiv').2⟩
    obtain ⟨u'', hu''⟩ := hdet''
    have hkey : (p : ZMod (p ^ N)) ^ v₀
        * ((u₀ : ZMod (p ^ N)) * (M''.submatrix Fin.succ Fin.succ).det)
        = (p : ZMod (p ^ N)) ^ c * u'' := by
      rw [← mul_assoc, ← hu₀, ← hM''00, ← hdetblock, hu'']
    have hv₀c : v₀ ≤ c := le_of_pow_mul_eq_pow_mul_unit hc hkey
    obtain ⟨w, hw⟩ := exists_unit_pow_sub_of_pow_mul_eq hv₀c hc hkey
    have hdet₁ : (M''.submatrix Fin.succ Fin.succ).det
        = (p : ZMod (p ^ N)) ^ (c - v₀) * ((u₀⁻¹ * w : (ZMod (p ^ N))ˣ) : ZMod (p ^ N)) := by
      calc (M''.submatrix Fin.succ Fin.succ).det
          = (u₀⁻¹ : (ZMod (p ^ N))ˣ)
            * ((u₀ : ZMod (p ^ N)) * (M''.submatrix Fin.succ Fin.succ).det) := by
            rw [← mul_assoc, Units.inv_mul, one_mul]
        _ = (u₀⁻¹ : (ZMod (p ^ N))ˣ) * ((p : ZMod (p ^ N)) ^ (c - v₀) * w) := by
            rw [hw]
        _ = (p : ZMod (p ^ N)) ^ (c - v₀)
            * ((u₀⁻¹ * w : (ZMod (p ^ N))ˣ) : ZMod (p ^ N)) := by
            rw [Units.val_mul]; ring
    -- the two factors
    have hcard₁ : Nat.card {y : Fin n → ZMod (p ^ N) //
        (M''.submatrix Fin.succ Fin.succ).mulVec y = 0} = p ^ (c - v₀) :=
      ih _ (by omega) ⟨u₀⁻¹ * w, hdet₁⟩
    have hcard₀ : Nat.card {t : ZMod (p ^ N) // M'' 0 0 * t = 0} = p ^ v₀ := by
      have he : {t : ZMod (p ^ N) // M'' 0 0 * t = 0}
          ≃ {s : ZMod (p ^ N) // (p : ZMod (p ^ N)) ^ v₀ * s = 0} :=
        { toFun := fun t => ⟨(u₀ : ZMod (p ^ N)) * t.1, by
            rw [← mul_assoc, ← hu₀, ← hM''00]
            exact t.2⟩
          invFun := fun s => ⟨(u₀⁻¹ : (ZMod (p ^ N))ˣ) * s.1, by
            rw [hM''00, hu₀, mul_assoc, Units.mul_inv_cancel_left]
            exact s.2⟩
          left_inv := fun t => Subtype.ext (Units.inv_mul_cancel_left u₀ t.1)
          right_inv := fun s => Subtype.ext (Units.mul_inv_cancel_left u₀ s.1) }
      rw [Nat.card_congr he, card_ker_mul_pow]
      congr 1
      omega
    -- assemble
    have hfinal : Nat.card {x : Fin (n + 1) → ZMod (p ^ N) // M.mulVec x = 0}
        = p ^ v₀ * p ^ (c - v₀) := by
      rw [← hker', ← hkerM'', hblock, hcard₀, hcard₁]
    rw [hfinal, ← pow_add]
    congr 1
    omega

/-! ## The deliverables -/

section Deliverables

variable {n : ℕ} (M : Matrix (Fin n) (Fin n) (ZMod (p ^ N))) {c : ℕ}

/-- **F-B1 (fibers).** All fibers of `x ↦ M *ᵥ x` over image points have exactly `p ^ c`
elements. -/
theorem fiber_card (hc : c < N)
    (hdet : ∃ u : (ZMod (p ^ N))ˣ, M.det = (p : ZMod (p ^ N)) ^ c * u)
    {y : Fin n → ZMod (p ^ N)} (hy : y ∈ Set.range M.mulVec) :
    Nat.card {x : Fin n → ZMod (p ^ N) // M.mulVec x = y} = p ^ c := by
  obtain ⟨x₀, hx₀⟩ := hy
  rw [← card_ker_mulVec_of_det M hc hdet]
  refine Nat.card_congr ?_
  refine
    { toFun := fun x => ⟨x.1 - x₀, ?_⟩
      invFun := fun t => ⟨t.1 + x₀, ?_⟩
      left_inv := fun x => Subtype.ext (by
        funext i; simp only [Pi.add_apply, Pi.sub_apply]; ring)
      right_inv := fun t => Subtype.ext (by
        funext i; simp only [Pi.add_apply, Pi.sub_apply]; ring) }
  · rw [Matrix.mulVec_sub, x.2, hx₀, sub_self]
  · rw [Matrix.mulVec_add, t.2, hx₀, zero_add]

/-- **F-B1 (image index).** The image of `x ↦ M *ᵥ x` has index `p ^ c` in
`(Fin n → ZMod (p ^ N))`. -/
theorem image_index (hc : c < N)
    (hdet : ∃ u : (ZMod (p ^ N))ˣ, M.det = (p : ZMod (p ^ N)) ^ c * u) :
    Nat.card (Set.range M.mulVec) * p ^ c = Nat.card (Fin n → ZMod (p ^ N)) := by
  set f : (Fin n → ZMod (p ^ N)) →+ (Fin n → ZMod (p ^ N)) :=
    AddMonoidHom.mk' M.mulVec (fun x y => M.mulVec_add x y) with hf
  have h1 : Nat.card (Fin n → ZMod (p ^ N))
      = Nat.card ((Fin n → ZMod (p ^ N)) ⧸ f.ker) * Nat.card f.ker :=
    AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup f.ker
  have h2 : Nat.card ((Fin n → ZMod (p ^ N)) ⧸ f.ker) = Nat.card f.range :=
    Nat.card_congr (QuotientAddGroup.quotientKerEquivRange f).toEquiv
  have h3 : Nat.card f.range = Nat.card (Set.range M.mulVec) := by
    refine Nat.card_congr (Equiv.subtypeEquivRight fun y => ?_)
    simp [hf, AddMonoidHom.mem_range, Set.mem_range]
  have h4 : Nat.card f.ker = p ^ c := by
    rw [← card_ker_mulVec_of_det M hc hdet]
    refine Nat.card_congr (Equiv.subtypeEquivRight fun x => ?_)
    simp [hf, AddMonoidHom.mem_ker]
  rw [h1, h2, h3, h4]

omit hp in
/-- Size of the ambient space, for convenience: `(p ^ N) ^ n = p ^ (N * n)`. -/
theorem card_target : Nat.card (Fin n → ZMod (p ^ N)) = p ^ (N * n) := by
  rw [Nat.card_fun, Nat.card_zmod, Nat.card_eq_fintype_card, Fintype.card_fin, ← pow_mul]

/-- **F-B1 (combined).** If `det M = p ^ c * u` with `u` a unit and `c < N`, then the fibers
of `x ↦ M *ᵥ x` over its image all have exactly `p ^ c` points, and the image has index
`p ^ c`. -/
theorem mulVec_fiber_card_of_det (hc : c < N)
    (hdet : ∃ u : (ZMod (p ^ N))ˣ, M.det = (p : ZMod (p ^ N)) ^ c * u) :
    (∀ y ∈ Set.range M.mulVec,
        Nat.card {x : Fin n → ZMod (p ^ N) // M.mulVec x = y} = p ^ c) ∧
      Nat.card (Set.range M.mulVec) * p ^ c = Nat.card (Fin n → ZMod (p ^ N)) :=
  ⟨fun _ hy => fiber_card M hc hdet hy, image_index M hc hdet⟩

/-! ### Degenerate case: `c = 0` -/

/-- Over any commutative ring, `x ↦ M *ᵥ x` is bijective iff `det M` is a unit. -/
theorem mulVec_bijective_iff_isUnit_det {R : Type*} [CommRing R] {m : ℕ}
    (A : Matrix (Fin m) (Fin m) R) :
    Function.Bijective A.mulVec ↔ IsUnit A.det := by
  constructor
  · intro h
    obtain ⟨B, hB⟩ : ∃ B : Matrix (Fin m) (Fin m) R, A * B = 1 := by
      choose g hg using h.surjective
      refine ⟨Matrix.of fun i j => g (Pi.single j 1) i, ?_⟩
      ext i j
      have hcol : A.mulVec (g (Pi.single j 1)) = Pi.single j 1 := hg _
      have hentry : (A * Matrix.of fun i j => g (Pi.single j 1) i) i j
          = A.mulVec (g (Pi.single j 1)) i := by
        simp only [Matrix.mul_apply, Matrix.mulVec, dotProduct, Matrix.of_apply]
      rw [hentry, hcol, Matrix.one_apply, Pi.single_apply]
    exact IsUnit.of_mul_eq_one _ (by rw [← Matrix.det_mul, hB, Matrix.det_one])
  · intro h
    refine Function.bijective_iff_has_inverse.mpr ⟨(A⁻¹).mulVec, fun x => ?_, fun y => ?_⟩
    · rw [Matrix.mulVec_mulVec, Matrix.nonsing_inv_mul A h, Matrix.one_mulVec]
    · rw [Matrix.mulVec_mulVec, Matrix.mul_nonsing_inv A h, Matrix.one_mulVec]

/-- Under the standing hypothesis `det M = p ^ c * u`, `c < N`: the exponent `c` vanishes iff
the determinant is a unit. -/
theorem c_eq_zero_iff_isUnit_det (hc : c < N)
    (hdet : ∃ u : (ZMod (p ^ N))ˣ, M.det = (p : ZMod (p ^ N)) ^ c * u) :
    c = 0 ↔ IsUnit M.det := by
  obtain ⟨u, hu⟩ := hdet
  constructor
  · rintro rfl
    rw [hu, pow_zero, one_mul]
    exact u.isUnit
  · intro h
    by_contra hc0
    have hpc : (p : ZMod (p ^ N)) ^ c = M.det * ((u⁻¹ : (ZMod (p ^ N))ˣ) : ZMod (p ^ N)) := by
      rw [hu, mul_assoc, Units.mul_inv, mul_one]
    have h1 : IsUnit ((p : ZMod (p ^ N)) ^ c) := by
      rw [hpc]
      exact h.mul u⁻¹.isUnit
    exact not_isUnit_cast_p (by omega) ((isUnit_pow_iff hc0).mp h1)

/-- `c = 0 ↔ IsUnit M` (tie to `Matrix.isUnit_iff_isUnit_det`). -/
theorem c_eq_zero_iff_isUnit (hc : c < N)
    (hdet : ∃ u : (ZMod (p ^ N))ˣ, M.det = (p : ZMod (p ^ N)) ^ c * u) :
    c = 0 ↔ IsUnit M :=
  (c_eq_zero_iff_isUnit_det M hc hdet).trans (Matrix.isUnit_iff_isUnit_det M).symm

/-- `c = 0 ↔ x ↦ M *ᵥ x` is bijective. -/
theorem c_eq_zero_iff_bijective (hc : c < N)
    (hdet : ∃ u : (ZMod (p ^ N))ˣ, M.det = (p : ZMod (p ^ N)) ^ c * u) :
    c = 0 ↔ Function.Bijective M.mulVec :=
  (c_eq_zero_iff_isUnit_det M hc hdet).trans (mulVec_bijective_iff_isUnit_det M).symm

end Deliverables

end LeanUrat.OM.LinearFiber
