import Mathlib

/-!
# M3 (DRAFT SKELETON) — NewtonPolygon: the lower Newton polygon as a lower convex minorant over ℚ

**STATUS: DRAFT SCOUT SKELETON.** This file is the M2-INDEPENDENT core of blueprint module M3
(`LeanUrat.OM.M3.NewtonPolygon`, blueprint §"M3: the lower Newton polygon",
`\subsec:m3`/`def:np-support`…`def:side-to-l4face`). It is written so the abstract Newton-polygon
machinery — the lower convex minorant `npHeight : ℚ → ℚ`, vertices, sides, slopes, and the convexity
lemma statements — typechecks against **Mathlib alone**, taking the support `Finset (ℕ × ℕ)` as an
INPUT parameter. The wiring to M2 (`support := M2.valSupport f`) is left as a clearly-marked TODO at
the bottom; M2 (`LeanUrat.OM.PadicValuation`) does not yet exist, so this file must NOT be built
against it.

Design decision recorded from the blueprint (`def:npheight`, "Why not mathlib `convexHull`"):
mathlib's `convexHull 𝕜 s` (`Mathlib/Analysis/Convex/Hull.lean`,
`ClosureOperator.ofCompletePred (Convex 𝕜)`) is the set-theoretic hull inside a `𝕜`-vector space; it
gives no handle on the *lower* boundary, the vertices as a finite list, or the rational slopes as
data. We therefore build the lower minorant **directly** as the convex lower hull: a finite
`Finset.sup'` over the VALID supporting lines (pairs whose secant lies weakly below all support dots,
`validLines`), the "max over candidate supporting slopes that stay below all dots" formulation, which
is computable and avoids the analytic convexity hierarchy.

REVISION NOTE (BUG-M3 fix): an EARLIER draft defined `npHeight` as an `inf'` of affine lines, but an
`inf'` of affine maps is CONCAVE, not convex, so `npHeight_convexOn` was unprovable (counterexample
`S = {(0,3),(1,0),(2,3)}`: `inf'`-height at `1` is `0 > -3`). The `sup'`-over-valid-lines lower hull is
the correct convex minorant: both the minorant property (`Finset.sup'_le`) and convexity
(`sup'_convexOn` + `pairLine_convexOn`) are now THEOREMS, proved via `convexOn_of_slope_mono_adjacent`
(`Mathlib/Analysis/Convex/Slope.lean`). The valid-line index is nonempty (`validLines_nonempty`) via
the horizontal line through a minimum-height support dot.

CONFIRMED MATHLIB INTERFACE (v4.31.0):
* `Finset.inf' : (s : Finset β) → s.Nonempty → (β → α) → α`  (`Mathlib/Data/Finset/Lattice/Fold.lean`),
  with `Finset.inf'_le`, `Finset.inf'_le_of_le`, `Finset.le_inf'`, `Finset.le_inf'_iff`
  (generated by `@[to_dual]` from the `sup'` lemmas). `ℚ` is a `LinearOrder` + `Lattice`, so `inf'`
  applies and `inf'_le`/`le_inf'` are usable over ℚ.
* `ConvexOn ℚ s f` (`Mathlib/Analysis/Convex/Function.lean`) is well-typed for `s : Set ℚ`,
  `f : ℚ → ℚ` because `ℚ` is a `ℚ`-module and an `OrderedAddCommMonoid`.
* `convex_Icc (r s : ℚ) : Convex ℚ (Set.Icc r s)` (`Mathlib/Analysis/Convex/Basic.lean`).
* `convexOn_of_slope_mono_adjacent` / `convexOn_iff_slope_mono_adjacent`
  (`Mathlib/Analysis/Convex/Slope.lean`): build/characterize `ConvexOn 𝕜 s f` from adjacent secant
  slopes being monotone. This is the route for `npHeight_convexOn` (see TODO there).
* `Int.ceil : ℚ → ℤ` (`⌈·⌉`), `Int.toNat` for the `ceilHeights` / `L4` bridge.
-/

namespace LeanUrat.OM.NewtonPolygon

open scoped Classical
open Finset

/-! ## Abstract setup: the support is an INPUT `Finset (ℕ × ℕ)`.

In the real M3, `support` will be `M2.valSupport f` for a monic `f : ℤ_[p][X]` of `natDegree n`,
which the blueprint (`lem:val-support-facts`) guarantees is nonempty (contains `(n, 0)`). Here we
abstract over it: any nonempty finite set of lattice "dots" `(i, vᵢ)` admits a lower Newton polygon. -/

variable (S : Finset (ℕ × ℕ))

/-- The plotted dots as rational points `(↑i, ↑v) : ℚ × ℚ`. We work over ℚ from the start because
slopes are rational. -/
def dotQ (P : ℕ × ℕ) : ℚ × ℚ := ((P.1 : ℚ), (P.2 : ℚ))

/-! ### Candidate supporting lines

A *candidate line* is determined by an ordered pair `(P, R)` of support points with `P.1 < R.1`
(distinct abscissae): the unique affine function through `dotQ P` and `dotQ R`. At a queried abscissa
`x : ℚ` it evaluates to `v_P + slope·(x - i_P)` with `slope = (v_R - v_P)/(i_R - i_P)`. We *also*
include the degenerate "horizontal through a single point" lines so the family is never empty when
`S` is a singleton, and so the minorant is anchored: the line through `(i,v)` of slope `0` evaluates
to `v` at `x = i`. -/

/-- Slope of the line through two lattice dots with distinct abscissae (junk `0` if equal). -/
def pairSlope (P R : ℕ × ℕ) : ℚ :=
  ((R.2 : ℚ) - (P.2 : ℚ)) / ((R.1 : ℚ) - (P.1 : ℚ))

/-- The affine line through dots `P` and `R`, evaluated at abscissa `x`:
`v_P + slope·(x - i_P)`. -/
def pairLine (P R : ℕ × ℕ) (x : ℚ) : ℚ :=
  (P.2 : ℚ) + pairSlope P R * (x - (P.1 : ℚ))

/-- The candidate-line index set: all ordered pairs of support points. We index by `S ×ˢ S` (the
`Finset` product) so the family is a genuine `Finset` and is nonempty whenever `S` is. The diagonal
pairs `(P, P)` give the horizontal line through `P` (slope junk-`0`), pinning the value `v_P` at
`x = i_P`; off-diagonal pairs with distinct abscissa give the secant lines. -/
def lineIndex : Finset ((ℕ × ℕ) × (ℕ × ℕ)) := S ×ˢ S

lemma lineIndex_nonempty (hS : S.Nonempty) : (lineIndex S).Nonempty := by
  obtain ⟨P, hP⟩ := hS
  exact ⟨(P, P), by simp [lineIndex, Finset.mem_product, hP]⟩

/-! ### The lower Newton height `npHeight` (REVISED: the convex lower hull)

**REVISION (BUG-M3 fix).** `npHeight S hS x` is the **supremum over the VALID supporting lines** of
their value at `x`. A candidate line `(P, R)` is *valid* if its secant lies weakly below every support
dot (`∀ Q ∈ S, pairLine P R Q.1 ≤ Q.2`); the supremum over valid lines is exactly the convex lower
hull `def:npheight`. This `sup'` (not the earlier `inf'`) is the correct convex minorant: a `sup'` of
affine maps is convex, and every valid line is a lower bound, so the `sup'` is the LARGEST lower bound
realizable by a supporting line — the lower Newton polygon.

The earlier `inf'` formulation was CONCAVE (an `inf'` of affine maps), making `npHeight_convexOn`
unprovable (counterexample `S = {(0,3),(1,0),(2,3)}`: `inf'`-height at `1` was `0 > -3`). Switching to
`sup'` over valid lines fixes both the minorant property (now via `sup'_le`) and convexity (now via
the proved `sup'_convexOn` + `pairLine_convexOn`).

The valid-line index set is NONEMPTY: the horizontal line through a minimum-height support dot lies
weakly below all dots (the "line through the lowest support dots"); see `validLines_nonempty`. -/

/-- A candidate line `(P, R)` is **valid** (a genuine lower-supporting line) if its secant lies weakly
below every plotted support dot. -/
def IsValidLine (PR : (ℕ × ℕ) × (ℕ × ℕ)) : Prop :=
  ∀ Q ∈ S, pairLine PR.1 PR.2 (Q.1 : ℚ) ≤ (Q.2 : ℚ)

/-- The valid-line index set: the candidate pairs whose secant lies weakly below all support dots.
Decidability of `IsValidLine` is supplied classically (`open scoped Classical`). -/
noncomputable def validLines : Finset ((ℕ × ℕ) × (ℕ × ℕ)) :=
  (lineIndex S).filter (IsValidLine S)

/-- The diagonal candidate line through `(i, v)` evaluates to `v` at `x = i`. -/
lemma pairLine_diag (i v : ℕ) : pairLine (i, v) (i, v) (i : ℚ) = (v : ℚ) := by
  simp [pairLine, pairSlope]

/-- The diagonal candidate line through `(i, v)` is the **horizontal** line at height `v`: it
evaluates to `v` at EVERY abscissa (the slope is junk-`0`). -/
lemma pairLine_diag_const (i v : ℕ) (x : ℚ) : pairLine (i, v) (i, v) x = (v : ℚ) := by
  simp [pairLine, pairSlope]

/-- **Nonemptiness of the valid-line index** (the hull-existence anchor). The horizontal line through
a minimum-height support dot `P₀` (i.e. `v_{P₀} = min over S of height`) lies weakly below all dots,
hence is a valid line. We obtain `P₀` as the argmin of the height over the nonempty finite `S`. -/
lemma validLines_nonempty (hS : S.Nonempty) : (validLines S).Nonempty := by
  classical
  -- choose a minimum-height support dot `P₀`
  obtain ⟨P₀, hP₀mem, hP₀min⟩ := S.exists_min_image (fun Q => Q.2) hS
  refine ⟨(P₀, P₀), ?_⟩
  rw [validLines, Finset.mem_filter]
  refine ⟨Finset.mem_product.2 ⟨hP₀mem, hP₀mem⟩, ?_⟩
  intro Q hQ
  -- the horizontal line through `P₀` has constant height `v_{P₀} ≤ v_Q`
  rw [show ((P₀, P₀).1 : ℕ × ℕ) = P₀ from rfl, show ((P₀, P₀).2 : ℕ × ℕ) = P₀ from rfl]
  rw [pairLine_diag_const P₀.1 P₀.2 (Q.1 : ℚ)]
  exact_mod_cast hP₀min Q hQ

/-- **Lower Newton height** at a rational abscissa `x`: the supremum of all VALID supporting-line
values at `x` — the convex lower hull. -/
noncomputable def npHeight (hS : S.Nonempty) (x : ℚ) : ℚ :=
  (validLines S).sup' (validLines_nonempty S hS) (fun PR => pairLine PR.1 PR.2 x)

/-! ### Minorant property (`lem:npheight-minorant`)

`npHeight S hS i ≤ v` for every plotted dot `(i, v) ∈ S`: the polygon lies weakly below every
coefficient-valuation point. Every VALID line lies weakly below all dots, so its value at `i` is
`≤ v`; the `sup'` of all those values is therefore `≤ v` (`Finset.sup'_le`). -/

/-- Each valid line evaluated at a dot's abscissa is `≤` that dot's height (by validity). -/
lemma pairLine_le_of_valid {PR : (ℕ × ℕ) × (ℕ × ℕ)} (hPR : PR ∈ validLines S)
    {i v : ℕ} (hiv : (i, v) ∈ S) : pairLine PR.1 PR.2 (i : ℚ) ≤ (v : ℚ) := by
  rw [validLines, Finset.mem_filter] at hPR
  exact hPR.2 (i, v) hiv

/-- **Lower minorant property** (blueprint `lem:npheight-minorant`). For every plotted dot
`(i, v) ∈ S`, `npHeight S hS i ≤ v`: the polygon lies weakly below every coefficient-valuation
point. Now via `Finset.sup'_le` over the valid lines (each is a lower bound). -/
lemma npHeight_le (hS : S.Nonempty) {i v : ℕ} (hiv : (i, v) ∈ S) :
    npHeight S hS (i : ℚ) ≤ (v : ℚ) := by
  rw [npHeight]
  refine Finset.sup'_le _ _ (fun PR hPR => ?_)
  exact pairLine_le_of_valid S hPR hiv

/-! ### Vertices, sides, slopes (`def:np-vertices`, `def:newtonpoly-side`)

The vertex list is the lower-hull breakpoint sequence sorted by abscissa, computed by the integer
cross-product hull scan over `S`. For this scout skeleton we record the *types* and a placeholder
hull-scan stub so that the side/slope structures typecheck; the genuine cross-product scan is M3
content (see TODO). The data we MUST expose (consumed by L4 bridge + M4 residual polynomial + M7) is:
the abscissae of the vertices, and for each side the tuple `(i₀, j₀, v₀, v₁)` plus the derived
`(length, e, h, slope)`. -/

/-- A **side** of the lower Newton polygon: the segment between two consecutive hull vertices,
carrying the raw endpoints `(i₀, v₀)`–`(j₀, v₁)` and the derived combinatorial data. The
`Nat`-coordinate fields are the GMN data; the `slope : ℚ` is `(v₁ - v₀)/(j₀ - i₀)` (descending sides
of the lower hull have `slope ≤ 0`). -/
structure Side where
  /-- Left endpoint abscissa. -/
  i₀ : ℕ
  /-- Right endpoint abscissa. -/
  j₀ : ℕ
  /-- Left endpoint height `v₀`. -/
  v₀ : ℕ
  /-- Right endpoint height `v₁`. -/
  v₁ : ℕ

namespace Side

/-- Horizontal length `ℓ(S) = j₀ - i₀`. -/
def length (s : Side) : ℕ := s.j₀ - s.i₀

/-- Slope `λ_S = (v₁ - v₀)/(j₀ - i₀) : ℚ`. -/
def slope (s : Side) : ℚ := ((s.v₁ : ℚ) - (s.v₀ : ℚ)) / ((s.j₀ : ℚ) - (s.i₀ : ℚ))

/-- Ramification denominator `e_S = Rat.den (slope)` (the reduced-fraction denominator). -/
def e (s : Side) : ℕ := s.slope.den

/-- Slope numerator magnitude `h_S = Rat.num (slope)` (in lowest terms; sign per GMN convention). -/
def h (s : Side) : ℤ := s.slope.num

end Side

/-! ### Vertex/side extraction — the REAL lower-hull scan (GLUE-5, `def:np-vertices`)

**DE-STUBBED (GLUE-5).** `npVertices`/`npSides` are now the genuine lower-Newton-polygon data, defined
*directly off the proved convex lower hull* `npHeight` (the `sup'` over valid supporting lines). We do
NOT reimplement a separate cross-product accumulator and re-prove it computes the hull; instead we use
`npHeight` itself as the oracle of what "on the hull" means, which is the honest move given that
`npHeight` is the proved minorant + convex (`npHeight_le`, `npHeight_convexOn`):

* A support dot `(i, v) ∈ S` lies **on the hull** iff its height is attained: `(v : ℚ) = npHeight i`.
  By `npHeight_le` every dot has `npHeight i ≤ v`; the on-hull dots are exactly those at equality, so
  they are the lower-boundary lattice points. Two distinct dots with the SAME abscissa cannot both be
  on the hull (`npHeight i` is a single value), so on-hull dots have a well-defined height per abscissa.
* `npVerticesFull` = the on-hull dots, **sorted strictly by abscissa** (`Finset.sort (· ≤ ·)` on the
  abscissa images, then looked up). Every entry lies on the hull and the abscissae strictly increase.
* `npVertices` = `npVerticesFull` with **collinear interior points removed** (the genuine GMN vertices:
  breakpoints where the hull slope changes). Removal is the integer cross-product pass
  `keepVertex`/`dropCollinear` below; it is a SUBLIST of `npVerticesFull`, so it inherits both the
  on-hull property (`npVertices_on_hull`) and the strictly-increasing abscissae (`npVertices_sorted`).
* `npSides` = consecutive vertex pairs of `npVertices`, each packaged as a `Side`. The slope therefore
  genuinely changes from side to side, and the per-side height span `(v₀ → v₁)` is the real polygon
  drop, so the Newton-exponent shares are now genuinely NONZERO whenever the polygon has any positive
  height (see `npSides_height_pos` / the M7 `toSideFace` heights). -/

/-- A support dot lies **on the lower hull** iff its height equals `npHeight` at its abscissa. -/
def OnHull (hS : S.Nonempty) (P : ℕ × ℕ) : Prop := (P.2 : ℚ) = npHeight S hS (P.1 : ℚ)

/-- The on-hull support dots. -/
noncomputable def hullDots (hS : S.Nonempty) : Finset (ℕ × ℕ) :=
  S.filter (OnHull S hS)

/-- The (strictly increasing) list of hull abscissae: the abscissae of the on-hull dots, sorted. -/
noncomputable def hullAbscissae (hS : S.Nonempty) : List ℕ :=
  ((hullDots S hS).image Prod.fst).sort (· ≤ ·)

/-- The height of the hull at abscissa `i`: the integer value `⌊npHeight i⌋` as a `ℕ`. On a hull
abscissa `npHeight i` equals the support dot's natural-number height `v`, so this recovers `v`
(`hullHeightAt_of_onHull`). -/
noncomputable def hullHeightAt (hS : S.Nonempty) (i : ℕ) : ℕ :=
  (⌊npHeight S hS (i : ℚ)⌋).toNat

/-- The hull dot at abscissa `i`, as a lattice point `(i, ⌊npHeight i⌋₊)`. On a hull abscissa this is
exactly the on-hull support dot there (`hullDotAt_of_onHull`). -/
noncomputable def hullDotAt (hS : S.Nonempty) (i : ℕ) : ℕ × ℕ :=
  (i, hullHeightAt S hS i)

/-- **Full vertex list**: every on-hull dot, sorted strictly by abscissa. Each entry is the genuine
hull dot at a hull abscissa. -/
noncomputable def npVerticesFull (hS : S.Nonempty) : List (ℕ × ℕ) :=
  (hullAbscissae S hS).map (hullDotAt S hS)

/-! #### Collinear-interior removal — the genuine GMN vertices

A point of `npVerticesFull` is a genuine vertex iff the hull slope *changes* there. Given three
consecutive hull points `A, B, C` (abscissae `iₐ < i_b < i_c`), `B` is collinear and should be dropped
iff the integer cross-product vanishes:
`(i_b - iₐ)·(v_c - vₐ) = (i_c - iₐ)·(v_b - vₐ)`. The pass `dropCollinear` walks the list right-to-left
keeping a point exactly when it is NOT collinear with its kept successors; it is a `Sublist` of the
input (`dropCollinear_sublist`), so the genuine vertices inherit on-hull + sortedness. -/

/-- Integer collinearity test for three lattice points `A, B, C` (true iff `B` lies on segment
`A`–`C`, via the vanishing integer cross product). -/
def collinear₃ (A B C : ℕ × ℕ) : Bool :=
  ((B.1 : ℤ) - A.1) * ((C.2 : ℤ) - A.2) == ((C.1 : ℤ) - A.1) * ((B.2 : ℤ) - A.2)

/-- Remove collinear interior points from a list of lattice points: keep the head unless it is
collinear with the next two kept points. Right-fold so each decision sees its kept successors. -/
def dropCollinear : List (ℕ × ℕ) → List (ℕ × ℕ)
  | [] => []
  | [a] => [a]
  | [a, b] => [a, b]
  | a :: b :: c :: rest =>
      let tail := dropCollinear (b :: c :: rest)
      match tail with
      | b' :: c' :: rest' =>
          if collinear₃ a b' c' then a :: c' :: rest' else a :: b' :: c' :: rest'
      | _ => a :: tail

/-- The recursion equation for the `3+`-element case, with the recursive call exposed. -/
theorem dropCollinear_cons3 (a b c : ℕ × ℕ) (rest : List (ℕ × ℕ)) :
    dropCollinear (a :: b :: c :: rest) =
      (match dropCollinear (b :: c :: rest) with
       | b' :: c' :: rest' =>
           if collinear₃ a b' c' then a :: c' :: rest' else a :: b' :: c' :: rest'
       | _ => a :: dropCollinear (b :: c :: rest)) := by
  conv_lhs => rw [dropCollinear]

/-- The head of `dropCollinear` is the head of the input, and its tail is a sublist of the input's
tail: `dropCollinear (a :: t) = a :: u` with `u <+ t`. -/
theorem dropCollinear_cons_head (a : ℕ × ℕ) (t : List (ℕ × ℕ)) :
    ∃ u, dropCollinear (a :: t) = a :: u ∧ u.Sublist t := by
  match t with
  | [] => exact ⟨[], rfl, by simp⟩
  | [b] => exact ⟨[b], rfl, by simp⟩
  | b :: c :: rest =>
      -- the recursive tail `dropCollinear (b::c::rest)` begins with `b`
      obtain ⟨u, hu, husub⟩ := dropCollinear_cons_head b (c :: rest)
      rw [dropCollinear_cons3, hu]
      -- now the match scrutinee is the concrete `b :: u`; case on `u`
      cases u with
      | nil =>
          -- scrutinee `[b]` hits the catch-all `_ => a :: dropCollinear (b::c::rest) = a :: [b]`
          refine ⟨[b], rfl, ?_⟩
          -- `[b]` ⊑ `b :: c :: rest`
          exact (List.singleton_sublist).2 (by simp)
      | cons c' rest' =>
          -- scrutinee `b :: c' :: rest'`; `husub : (c' :: rest') <+ (c :: rest)`
          simp only
          by_cases hcol : collinear₃ a b c'
          · refine ⟨c' :: rest', by simp only [hcol, if_true], ?_⟩
            -- `c' :: rest'` ⊑ `c :: rest` ⊑ `b :: c :: rest`
            exact husub.cons b
          · refine ⟨b :: c' :: rest', by simp only [hcol]; rfl, ?_⟩
            -- `b :: c' :: rest'` ⊑ `b :: c :: rest`
            exact List.cons_sublist_cons.2 husub
  termination_by t.length
  decreasing_by simp_wf

/-- `dropCollinear` returns a sublist of its input. -/
theorem dropCollinear_sublist (l : List (ℕ × ℕ)) : (dropCollinear l).Sublist l := by
  match l with
  | [] => simp [dropCollinear]
  | a :: t =>
      obtain ⟨u, hu, husub⟩ := dropCollinear_cons_head a t
      rw [hu]
      exact List.cons_sublist_cons.2 husub

/-- **Vertex list** (`def:np-vertices`, GLUE-5, REAL). The genuine lower-Newton-polygon vertices: the
on-hull support dots (sorted by abscissa) with collinear interior points removed, so consecutive
slopes genuinely differ. A SUBLIST of `npVerticesFull` (`dropCollinear_sublist`), hence every entry is
on the hull and the abscissae strictly increase. -/
noncomputable def npVertices (hS : S.Nonempty) : List (ℕ × ℕ) :=
  dropCollinear (npVerticesFull S hS)

/-- **Side list** (`def:newtonpoly-side`, GLUE-5, REAL). Consecutive vertex pairs of `npVertices`,
each packaged as a `Side` carrying the real endpoints `(i₀, v₀)–(j₀, v₁)`. Since `npVertices` has the
collinear points removed, each side has a genuinely different slope and a real (in general nonzero)
height drop `v₁ - v₀`, driving the nonzero Newton-exponent shares. -/
noncomputable def npSides (hS : S.Nonempty) : List Side :=
  ((npVertices S hS).zip (npVertices S hS).tail).map
    (fun (pr : (ℕ × ℕ) × (ℕ × ℕ)) => ⟨pr.1.1, pr.2.1, pr.1.2, pr.2.2⟩)

/-- **`npSides` is a PURE function of the support `Finset`** (`CERTLEVEL_DECOMP.md` Layer B, B-poly-1).
`npSides` (and `npVertices`/`npVerticesFull`) close over the section variable `S : Finset (ℕ × ℕ)`,
so once the supports coincide `S = S'` the side lists coincide — the nonemptiness witness is
proof-irrelevant. This is the cleanest possible statement of Newton-polygon stability: it equals
support equality. Discharged by `subst; rfl`, unconditional, no axiom. -/
theorem npSides_congr (S S' : Finset (ℕ × ℕ)) (hS : S.Nonempty) (hS' : S'.Nonempty)
    (h : S = S') : npSides S hS = npSides S' hS' := by
  subst h; rfl

/-! ### Correctness of the hull scan (footprints below)

The two facts downstream needs:
* `npVerticesFull_on_hull` / `npVertices_on_hull`: every produced vertex lies ON the hull
  (`(v:ℚ) = npHeight i`) — the vertices are genuine lower-boundary lattice points, not arbitrary dots.
* `npVerticesFull_sorted` / `npVertices_sorted`: the vertex abscissae STRICTLY increase — the list is a
  genuine left-to-right hull traversal with no repeats.
Both are proved against the proved `npHeight` (minorant `npHeight_le`), and pass through `dropCollinear`
by `dropCollinear_sublist`. -/

/-- On a hull abscissa, `hullHeightAt` recovers the on-hull dot's natural-number height. (The
membership `(i, v) ∈ S` is kept as a documented precondition though only the on-hull equation is used.)
-/
theorem hullHeightAt_of_onHull (hS : S.Nonempty) {i v : ℕ} (_hiv : (i, v) ∈ S)
    (hon : (v : ℚ) = npHeight S hS (i : ℚ)) : hullHeightAt S hS i = v := by
  unfold hullHeightAt
  rw [← hon]
  simp [Int.floor_natCast, Int.toNat_natCast]

/-- A hull abscissa is exactly the abscissa of some on-hull support dot. -/
theorem mem_hullAbscissae_iff (hS : S.Nonempty) {i : ℕ} :
    i ∈ hullAbscissae S hS ↔ ∃ v, (i, v) ∈ S ∧ (v : ℚ) = npHeight S hS (i : ℚ) := by
  classical
  unfold hullAbscissae
  rw [Finset.mem_sort, Finset.mem_image]
  constructor
  · rintro ⟨P, hP, rfl⟩
    rw [hullDots, Finset.mem_filter] at hP
    exact ⟨P.2, hP.1, hP.2⟩
  · rintro ⟨v, hiv, hon⟩
    exact ⟨(i, v), by rw [hullDots, Finset.mem_filter]; exact ⟨hiv, hon⟩, rfl⟩

/-- **Every full-vertex lies on the hull.** -/
theorem npVerticesFull_on_hull (hS : S.Nonempty) {P : ℕ × ℕ} (hP : P ∈ npVerticesFull S hS) :
    (P.2 : ℚ) = npHeight S hS (P.1 : ℚ) := by
  unfold npVerticesFull at hP
  rw [List.mem_map] at hP
  obtain ⟨i, hi, rfl⟩ := hP
  rw [mem_hullAbscissae_iff] at hi
  obtain ⟨v, hiv, hon⟩ := hi
  -- `hullDotAt S hS i = (i, hullHeightAt S hS i) = (i, v)`
  unfold hullDotAt
  simp only
  rw [hullHeightAt_of_onHull S hS hiv hon]
  exact hon

/-- **Full-vertex abscissae are strictly increasing.** The abscissa list is the image of `Prod.fst`
over the sorted hull abscissae, which is exactly `hullAbscissae` (each entry's first coordinate is the
abscissa it was looked up at), and `Finset.sort (· ≤ ·)` on a `Nodup` set is strictly increasing. -/
theorem npVerticesFull_fst (hS : S.Nonempty) :
    (npVerticesFull S hS).map Prod.fst = hullAbscissae S hS := by
  unfold npVerticesFull
  rw [List.map_map]
  refine List.map_congr_left ?_ |>.trans (List.map_id _)
  intro i _
  rfl

theorem npVerticesFull_sorted (hS : S.Nonempty) :
    ((npVerticesFull S hS).map Prod.fst).Pairwise (· < ·) := by
  rw [npVerticesFull_fst]
  unfold hullAbscissae
  -- `Finset.sort (· ≤ ·)` of a `ℕ`-finset is `SortedLT`, i.e. `Pairwise (· < ·)`.
  exact List.sortedLT_iff_pairwise.mp (Finset.sortedLT_sort _)

/-- **Every genuine vertex lies on the hull** (inherits from `npVerticesFull` via the sublist). -/
theorem npVertices_on_hull (hS : S.Nonempty) {P : ℕ × ℕ} (hP : P ∈ npVertices S hS) :
    (P.2 : ℚ) = npHeight S hS (P.1 : ℚ) :=
  npVerticesFull_on_hull S hS ((dropCollinear_sublist _).subset hP)

/-- **Genuine-vertex abscissae are strictly increasing** (inherits via the sublist on the mapped
abscissa list). -/
theorem npVertices_sorted (hS : S.Nonempty) :
    ((npVertices S hS).map Prod.fst).Pairwise (· < ·) := by
  unfold npVertices
  have hsub : ((dropCollinear (npVerticesFull S hS)).map Prod.fst).Sublist
      ((npVerticesFull S hS).map Prod.fst) :=
    (dropCollinear_sublist _).map Prod.fst
  exact (npVerticesFull_sorted S hS).sublist hsub

/-! ### Finiteness / length bounds (`lem:np-finite`) — now THEOREMS

`npVertices` is a sublist of `npVerticesFull`, whose length is `(hullAbscissae S hS).length ≤ S.card`.
`npSides` has length one less than `npVertices` (the `zip` with the tail). -/

theorem npVertices_length_le (hS : S.Nonempty) : (npVertices S hS).length ≤ S.card := by
  classical
  unfold npVertices
  refine (List.Sublist.length_le (dropCollinear_sublist _)).trans ?_
  unfold npVerticesFull
  rw [List.length_map]
  unfold hullAbscissae
  rw [Finset.length_sort]
  refine (Finset.card_image_le).trans ?_
  exact Finset.card_filter_le _ _

theorem npSides_length (hS : S.Nonempty) :
    (npSides S hS).length + 1 = (npVertices S hS).length ∨ npVertices S hS = [] := by
  classical
  unfold npSides
  rcases (npVertices S hS).eq_nil_or_concat with h | ⟨l, a, h⟩
  · right; exact h
  · left
    rw [List.length_map, List.length_zip, List.length_tail]
    have hlen : 1 ≤ (npVertices S hS).length := by rw [h]; simp
    omega

/-! ### Convexity infrastructure (reusable, proved core-only)

These two lemmas are the genuine mathlib wiring that the corrected convexity proof needs. They are
fully proved (footprint `[propext, Classical.choice, Quot.sound]`) and depend on nothing frozen.

* `pairLine_convexOn`: each candidate line is **affine** in the abscissa, hence convex (and concave)
  on any convex set. Proved via `convexOn_of_slope_mono_adjacent`, observing that every secant slope
  of `pairLine P R` equals the constant `pairSlope P R`.
* `sup'_convexOn`: a `Finset.sup'` of convex functions is convex (pointwise max of convex is convex,
  iterated over the finset via `ConvexOn.sup` + `Finset.cons_induction`).

Together they give: a `Finset.sup'` of `pairLine`s is convex. This is exactly the route the corrected
`npHeight` (the convex **lower hull**, a `sup'` of valid supporting lines — see FLAG below) requires.
They are deliberately NOT specialised to the current `inf'` form of `npHeight`, because that form is
concave, not convex (see FLAG on `npHeight_convexOn`). -/

/-- Each candidate line `pairLine P R` is affine in the abscissa, hence convex on any convex set
`s ⊆ ℚ`. (Every secant slope equals the constant `pairSlope P R`.) -/
lemma pairLine_convexOn (P R : ℕ × ℕ) (s : Set ℚ) (hs : Convex ℚ s) :
    ConvexOn ℚ s (pairLine P R) := by
  apply convexOn_of_slope_mono_adjacent hs
  intro x y z _ _ hxy hyz
  have hyx : y - x ≠ 0 := sub_ne_zero.2 (ne_of_gt hxy)
  have hzy : z - y ≠ 0 := sub_ne_zero.2 (ne_of_gt hyz)
  have e1 : (pairLine P R y - pairLine P R x) / (y - x) = pairSlope P R := by
    simp only [pairLine]; field_simp; ring
  have e2 : (pairLine P R z - pairLine P R y) / (z - y) = pairSlope P R := by
    simp only [pairLine]; field_simp; ring
  rw [e1, e2]

/-- A `Finset.sup'` of pointwise-convex functions is convex (iterated `ConvexOn.sup`). The
nonemptiness witness is universally quantified so the induction can refit it on the tail. -/
lemma sup'_convexOn {ι : Type*} (s : Set ℚ) (g : ι → ℚ → ℚ)
    (hconv : ∀ i, ConvexOn ℚ s (g i)) :
    ∀ (t : Finset ι) (H : t.Nonempty),
      ConvexOn ℚ s (fun x => t.sup' H (fun i => g i x)) := by
  classical
  intro t
  induction t using Finset.cons_induction with
  | empty => intro H; exact absurd H (by simp)
  | cons a t ha ih =>
      intro H
      rcases t.eq_empty_or_nonempty with rfl | ht
      · simpa using hconv a
      · have hsup := (hconv a).sup (ih ht)
        refine hsup.congr ?_
        intro x _
        simp only [Pi.sup_apply]
        rw [Finset.sup'_cons (H := ht)]

/-! ### Convexity (`lem:npheight-convex`, `npHeight_convexOn`) — NOW CLOSED

**REVISION (BUG-M3 fix, CLOSED).** With `npHeight` redefined as the convex lower hull (the `sup'` over
the valid supporting lines), convexity is now a direct consequence of the proved helpers: each valid
line is affine, hence convex (`pairLine_convexOn`), and a `Finset.sup'` of convex functions is convex
(`sup'_convexOn`). The earlier `inf'` formulation was concave (counterexample
`S = {(0,3),(1,0),(2,3)}`: `inf'`-height at `1` was `0 > -3`); the `sup'`-over-valid-lines lower hull
satisfies convexity instead. No `sorry` remains: the valid-line index is nonempty by
`validLines_nonempty` (the horizontal line through a lowest support dot), so the `sup'` is well-formed,
and the proof is a one-liner over the reusable machinery. -/

/-- **Convexity of the lower Newton minorant** (blueprint `lem:npheight-convex`). NOW CLOSED against the
revised convex-lower-hull `npHeight`: the `sup'` of the affine valid lines is convex. -/
theorem npHeight_convexOn (hS : S.Nonempty) (n : ℚ) :
    ConvexOn ℚ (Set.Icc (0 : ℚ) n) (npHeight S hS) := by
  have h :=
    sup'_convexOn (ι := (ℕ × ℕ) × (ℕ × ℕ)) (Set.Icc (0 : ℚ) n)
      (fun PR => pairLine PR.1 PR.2)
      (fun PR => pairLine_convexOn PR.1 PR.2 _ (convex_Icc 0 n))
      (validLines S) (validLines_nonempty S hS)
  -- `npHeight S hS = fun x => (validLines S).sup' _ (fun PR => pairLine PR.1 PR.2 x)` definitionally
  exact h

/-! ### Breakpoint / chord-attainment (HULL_BLUEPRINT §1)

The lower-hull value on a hull side equals the affine chord through the side's two endpoints. This is
the one missing convex-hull primitive that finishes the reduction-stability tree
(`Classifier.npVertices_stable_of_hull_preserved`). We build it from:
* `pairLine_concaveOn` — affine ⇒ concave (a one-line twin of `pairLine_convexOn`);
* `npHeight_convexOn` + `ConvexOn.sub` — `npHeight - pairLine` is convex;
* `ConvexOn.le_on_segment` — a convex function is bounded above on a segment by its endpoint values.
The endpoint values of `npHeight - pairLine` are `≤ 0` by `npHeight_le` (the line passes through the
endpoint heights), so the convex difference is `≤ 0` on the bracket, giving the `≥` direction; the `≤`
direction is `Finset.le_sup'` directly. -/

/-- Each candidate line `pairLine P R` is affine, hence **concave** on any convex `s ⊆ ℚ` (the concave
twin of `pairLine_convexOn`; every secant slope equals the constant `pairSlope P R`). -/
lemma pairLine_concaveOn (P R : ℕ × ℕ) (s : Set ℚ) (hs : Convex ℚ s) :
    ConcaveOn ℚ s (pairLine P R) := by
  apply concaveOn_of_slope_anti_adjacent hs
  intro x y z _ _ hxy hyz
  have hyx : y - x ≠ 0 := sub_ne_zero.2 (ne_of_gt hxy)
  have hzy : z - y ≠ 0 := sub_ne_zero.2 (ne_of_gt hyz)
  have e1 : (pairLine P R y - pairLine P R x) / (y - x) = pairSlope P R := by
    simp only [pairLine]; field_simp; ring
  have e2 : (pairLine P R z - pairLine P R y) / (z - y) = pairSlope P R := by
    simp only [pairLine]; field_simp; ring
  rw [e1, e2]

/-- The two endpoints of a valid line both lie in `S` (the index pair lives in `S ×ˢ S`). -/
lemma validLines_mem_left {PR : (ℕ × ℕ) × (ℕ × ℕ)} (hPR : PR ∈ validLines S) : PR.1 ∈ S := by
  rw [validLines, Finset.mem_filter, lineIndex, Finset.mem_product] at hPR
  exact hPR.1.1

lemma validLines_mem_right {PR : (ℕ × ℕ) × (ℕ × ℕ)} (hPR : PR ∈ validLines S) : PR.2 ∈ S := by
  rw [validLines, Finset.mem_filter, lineIndex, Finset.mem_product] at hPR
  exact hPR.1.2

/-- `pairLine A B` passes through the left endpoint: its value at `A.1` is `A.2`. -/
lemma pairLine_left (A B : ℕ × ℕ) : pairLine A B (A.1 : ℚ) = (A.2 : ℚ) := by
  simp [pairLine]

/-- `pairLine A B` passes through the right endpoint when the abscissae differ: its value at `B.1`
is `B.2` (needs `A.1 ≠ B.1` so the slope's denominator is nonzero). -/
lemma pairLine_right (A B : ℕ × ℕ) (hab : (A.1 : ℚ) ≠ (B.1 : ℚ)) :
    pairLine A B (B.1 : ℚ) = (B.2 : ℚ) := by
  have hsub : (B.1 : ℚ) - (A.1 : ℚ) ≠ 0 := sub_ne_zero.2 (Ne.symm hab)
  simp only [pairLine, pairSlope]
  field_simp
  ring

/-- **Breakpoint / chord-attainment** (HULL_BLUEPRINT §1). On a hull side — between two ON-HULL dots
`A`, `B` whose connecting line is a VALID supporting line (`(A, B) ∈ validLines S`) — the lower Newton
height equals the affine chord through `A` and `B`. (The lower hull is piecewise-affine; on each side
it is exactly the line through the side's endpoints.) The hypotheses use ONLY `(A,B) ∈ validLines S`
and the abscissa bracket: validity already forces both endpoints on the hull, so no
"consecutive / no-dot-between" hypothesis is needed. -/
theorem npHeight_eq_pairLine_of_validLine (hS : S.Nonempty)
    {A B : ℕ × ℕ} (hAB : (A, B) ∈ validLines S)
    {x : ℚ} (hx : x ∈ Set.Icc (A.1 : ℚ) (B.1 : ℚ)) :
    npHeight S hS x = pairLine A B x := by
  have hAmem : A ∈ S := validLines_mem_left S hAB
  have hBmem : B ∈ S := validLines_mem_right S hAB
  have hle : (A.1 : ℚ) ≤ (B.1 : ℚ) := le_trans hx.1 hx.2
  refine le_antisymm ?_ ?_
  · -- (≥ direction): `npHeight x ≤ pairLine A B x` via convex-minus-affine ≤ 0 on the segment.
    -- Set `h := npHeight - pairLine A B`, convex on `Icc 0 (B.1)`, with `h ≤ 0` at both endpoints.
    set g : ℚ → ℚ := npHeight S hS with hg
    set L : ℚ → ℚ := pairLine A B with hL
    have hconv : ConvexOn ℚ (Set.Icc (0 : ℚ) (B.1 : ℚ)) (g - L) :=
      (npHeight_convexOn S hS (B.1 : ℚ)).sub (pairLine_concaveOn A B _ (convex_Icc 0 (B.1 : ℚ)))
    -- endpoints lie in `Icc 0 (B.1)`
    have hA0 : (0 : ℚ) ≤ (A.1 : ℚ) := by positivity
    have hAmemIcc : (A.1 : ℚ) ∈ Set.Icc (0 : ℚ) (B.1 : ℚ) := ⟨hA0, hle⟩
    have hBmemIcc : (B.1 : ℚ) ∈ Set.Icc (0 : ℚ) (B.1 : ℚ) := ⟨le_trans hA0 hle, le_refl _⟩
    -- `(g - L) A.1 ≤ 0`
    have hgA : g (A.1 : ℚ) ≤ (A.2 : ℚ) := npHeight_le S hS hAmem
    have hendA : (g - L) (A.1 : ℚ) ≤ 0 := by
      simp only [Pi.sub_apply, hL]
      rw [pairLine_left A B]; linarith
    -- `(g - L) B.1 ≤ 0`
    have hgB : g (B.1 : ℚ) ≤ (B.2 : ℚ) := npHeight_le S hS hBmem
    have hendB : (g - L) (B.1 : ℚ) ≤ 0 := by
      rcases eq_or_lt_of_le hle with heq | hlt
      · -- degenerate `A.1 = B.1`: `pairLine A B B.1 = A.2` (slope's denom is `0`), and `g B.1 = g A.1`
        simp only [Pi.sub_apply, hL]
        rw [← heq, pairLine_left A B]; linarith
      · simp only [Pi.sub_apply, hL]
        rw [pairLine_right A B (ne_of_lt hlt)]; linarith
    -- `x` is in the segment `[A.1 -[ℚ] B.1] = Icc A.1 B.1`
    have hxseg : x ∈ segment ℚ (A.1 : ℚ) (B.1 : ℚ) := by
      rw [segment_eq_Icc hle]; exact hx
    have hbound := hconv.le_on_segment hAmemIcc hBmemIcc hxseg
    have : (g - L) x ≤ 0 := le_trans hbound (max_le hendA hendB)
    simpa only [Pi.sub_apply, hg, hL, sub_nonpos] using this
  · -- (≤ direction): `pairLine A B x ≤ npHeight x` directly by `Finset.le_sup'`.
    rw [npHeight, Finset.le_sup'_iff]
    exact ⟨(A, B), hAB, le_refl _⟩

/-! ### Consecutive-chord validity (HULL_BLUEPRINT §2.2, work-ledger item 3)

The chord between two ON-HULL support dots with no support dot strictly between their abscissae is a
valid supporting line. Together with the breakpoint lemma `npHeight_eq_pairLine_of_validLine` this
realizes `npHeight` as the piecewise-affine join of its consecutive-vertex chords. The proof is convex
chord-domination: strictly between the endpoints there are no dots (`hmid`); at the endpoints the
chord passes through the dots' heights (on-hull); outside the bracket
`ConvexOn.slope_mono_adjacent` forces the chord below the convex `npHeight`, which lies below every
dot by the minorant property.

NOTE vs the blueprint statement: the memberships `A ∈ S`, `B ∈ S` are REQUIRED hypotheses here (the
blueprint omitted them) — `OnHull` alone does not imply membership, and `(A, B) ∈ validLines S`
demands `(A, B) ∈ lineIndex S = S ×ˢ S`. -/

/-- **Consecutive-chord validity.** If `A, B ∈ S` are on the hull, `A.1 < B.1`, and no support dot
has abscissa strictly between, then the chord `(A, B)` is a valid supporting line. -/
theorem consecutive_chord_valid (hS : S.Nonempty)
    {A B : ℕ × ℕ} (hAmem : A ∈ S) (hBmem : B ∈ S)
    (hA : OnHull S hS A) (hB : OnHull S hS B) (hAB : A.1 < B.1)
    (hmid : ∀ C ∈ S, A.1 < C.1 → C.1 < B.1 → False) :
    (A, B) ∈ validLines S := by
  rw [validLines, Finset.mem_filter]
  refine ⟨Finset.mem_product.2 ⟨hAmem, hBmem⟩, ?_⟩
  intro Q hQ
  show pairLine A B (Q.1 : ℚ) ≤ (Q.2 : ℚ)
  have hgA : npHeight S hS (A.1 : ℚ) = (A.2 : ℚ) := Eq.symm hA
  have hgB : npHeight S hS (B.1 : ℚ) = (B.2 : ℚ) := Eq.symm hB
  have hgQ : npHeight S hS (Q.1 : ℚ) ≤ (Q.2 : ℚ) :=
    npHeight_le S hS (show (Q.1, Q.2) ∈ S by simpa using hQ)
  have hab : (A.1 : ℚ) < (B.1 : ℚ) := by exact_mod_cast hAB
  have hba : (0 : ℚ) < (B.1 : ℚ) - (A.1 : ℚ) := by linarith
  -- single-fraction form of the chord, and reduction to the cross-multiplied bound
  have hexp : pairLine A B (Q.1 : ℚ)
      = (A.2 : ℚ) + ((B.2 : ℚ) - (A.2 : ℚ)) * ((Q.1 : ℚ) - (A.1 : ℚ)) / ((B.1 : ℚ) - (A.1 : ℚ)) := by
    simp only [pairLine, pairSlope]; ring
  have hred : ((B.2 : ℚ) - (A.2 : ℚ)) * ((Q.1 : ℚ) - (A.1 : ℚ))
        ≤ ((Q.2 : ℚ) - (A.2 : ℚ)) * ((B.1 : ℚ) - (A.1 : ℚ)) →
      pairLine A B (Q.1 : ℚ) ≤ (Q.2 : ℚ) := by
    intro hcross
    have h2 : ((B.2 : ℚ) - (A.2 : ℚ)) * ((Q.1 : ℚ) - (A.1 : ℚ)) / ((B.1 : ℚ) - (A.1 : ℚ))
        ≤ (Q.2 : ℚ) - (A.2 : ℚ) := by
      rw [div_le_iff₀ hba]; exact hcross
    rw [hexp]; linarith
  rcases Nat.lt_trichotomy Q.1 A.1 with hqa | hqa | hqa
  · -- `Q` strictly left of `A`: chord-domination via the secant comparison at `(Q.1, A.1, B.1)`
    have hqa' : (Q.1 : ℚ) < (A.1 : ℚ) := by exact_mod_cast hqa
    have haq : (0 : ℚ) < (A.1 : ℚ) - (Q.1 : ℚ) := by linarith
    have hslope := (npHeight_convexOn S hS (B.1 : ℚ)).slope_mono_adjacent
      (x := (Q.1 : ℚ)) (y := (A.1 : ℚ)) (z := (B.1 : ℚ))
      ⟨Nat.cast_nonneg _, by linarith⟩ ⟨Nat.cast_nonneg _, le_refl _⟩ hqa' hab
    rw [hgA, hgB, div_le_div_iff₀ haq hba] at hslope
    -- hslope : (A.2 - npHeight Q.1) * (B.1 - A.1) ≤ (B.2 - A.2) * (A.1 - Q.1)
    refine hred ?_
    have hmul : (npHeight S hS (Q.1 : ℚ) - (A.2 : ℚ)) * ((B.1 : ℚ) - (A.1 : ℚ))
        ≤ ((Q.2 : ℚ) - (A.2 : ℚ)) * ((B.1 : ℚ) - (A.1 : ℚ)) :=
      mul_le_mul_of_nonneg_right (by linarith) hba.le
    nlinarith [hslope, hmul]
  · -- `Q.1 = A.1`: the chord hits `A.2 = npHeight A.1 ≤ Q.2`
    have hq : (Q.1 : ℚ) = (A.1 : ℚ) := by exact_mod_cast hqa
    rw [hq, pairLine_left]
    rw [hq, hgA] at hgQ
    exact hgQ
  · rcases Nat.lt_trichotomy Q.1 B.1 with hqb | hqb | hqb
    · -- strictly between: excluded by `hmid`
      exact (hmid Q hQ hqa hqb).elim
    · -- `Q.1 = B.1`: the chord hits `B.2 = npHeight B.1 ≤ Q.2`
      have hq : (Q.1 : ℚ) = (B.1 : ℚ) := by exact_mod_cast hqb
      rw [hq, pairLine_right A B (ne_of_lt hab)]
      rw [hq, hgB] at hgQ
      exact hgQ
    · -- `Q` strictly right of `B`: secant comparison at `(A.1, B.1, Q.1)`
      have hqb' : (B.1 : ℚ) < (Q.1 : ℚ) := by exact_mod_cast hqb
      have hbq : (0 : ℚ) < (Q.1 : ℚ) - (B.1 : ℚ) := by linarith
      have hslope := (npHeight_convexOn S hS (Q.1 : ℚ)).slope_mono_adjacent
        (x := (A.1 : ℚ)) (y := (B.1 : ℚ)) (z := (Q.1 : ℚ))
        ⟨Nat.cast_nonneg _, by linarith⟩ ⟨Nat.cast_nonneg _, le_refl _⟩ hab hqb'
      rw [hgA, hgB, div_le_div_iff₀ hba hbq] at hslope
      -- hslope : (B.2 - A.2) * (Q.1 - B.1) ≤ (npHeight Q.1 - B.2) * (B.1 - A.1)
      refine hred ?_
      have hmul : (npHeight S hS (Q.1 : ℚ) - (A.2 : ℚ)) * ((B.1 : ℚ) - (A.1 : ℚ))
          ≤ ((Q.2 : ℚ) - (A.2 : ℚ)) * ((B.1 : ℚ) - (A.1 : ℚ)) :=
        mul_le_mul_of_nonneg_right (by linarith) hba.le
      nlinarith [hslope, hmul]

/-! ### COUNTEREXAMPLE — hull preservation does NOT pin the vertex list without abscissa control

The Classifier-side target `npVertices_stable_of_hull_preserved` in its original TWO-hypothesis form
(`hpres` : `S'`-vertices ⊆ `S`, `habove` : `S`-dots on/above the `S'`-hull) is **FALSE**:
take `S' = {(0,0)}` and `S = {(0,0), (1,0)}`. Every `S'`-vertex lies in `S`, and every `S`-dot lies
on the (identically-zero) `S'`-hull, yet `S` has the extra vertex `(1,0)`:
`npVertices S = [(0,0),(1,0)] ≠ [(0,0)] = npVertices S'`. The repaired statement must additionally
control the abscissae of `S` (every `S`-abscissa is an `S'`-abscissa), which the reduction use-site
(`boxValSupport_reduce_stable_R`) supplies for free (reduction never creates support indices).
The helper lemmas compute the hull data of "all heights zero" supports explicitly. -/

/-- Every candidate line of a height-zero pair of dots is identically zero. -/
lemma pairLine_of_heights_zero {P R : ℕ × ℕ} (hP : P.2 = 0) (hR : R.2 = 0) (x : ℚ) :
    pairLine P R x = 0 := by
  simp [pairLine, pairSlope, hP, hR]

/-- If all support heights are zero, the lower Newton height is identically zero. -/
lemma npHeight_of_heights_zero (hS : S.Nonempty) (h0 : ∀ P ∈ S, P.2 = 0) (x : ℚ) :
    npHeight S hS x = 0 := by
  refine le_antisymm ?_ ?_
  · rw [npHeight]
    refine Finset.sup'_le _ _ (fun PR hPR => ?_)
    exact le_of_eq (pairLine_of_heights_zero (h0 _ (validLines_mem_left S hPR))
      (h0 _ (validLines_mem_right S hPR)) x)
  · obtain ⟨P, hP⟩ := hS
    have hmem : (P, P) ∈ validLines S := by
      rw [validLines, Finset.mem_filter]
      refine ⟨Finset.mem_product.2 ⟨hP, hP⟩, fun Q hQ => ?_⟩
      exact le_trans (le_of_eq (pairLine_of_heights_zero (h0 P hP) (h0 P hP) (Q.1 : ℚ)))
        (Nat.cast_nonneg _)
    rw [npHeight, Finset.le_sup'_iff]
    exact ⟨(P, P), hmem, le_of_eq (pairLine_of_heights_zero (h0 P hP) (h0 P hP) x).symm⟩

/-- If all support heights are zero, every support dot is on the hull. -/
lemma hullDots_of_heights_zero (hS : S.Nonempty) (h0 : ∀ P ∈ S, P.2 = 0) :
    hullDots S hS = S := by
  rw [hullDots]
  refine Finset.filter_true_of_mem fun P hP => ?_
  show (P.2 : ℚ) = npHeight S hS (P.1 : ℚ)
  rw [npHeight_of_heights_zero S hS h0, h0 P hP, Nat.cast_zero]

/-- If all support heights are zero, the hull height is zero at every abscissa. -/
lemma hullHeightAt_of_heights_zero (hS : S.Nonempty) (h0 : ∀ P ∈ S, P.2 = 0) (i : ℕ) :
    hullHeightAt S hS i = 0 := by
  unfold hullHeightAt
  rw [npHeight_of_heights_zero S hS h0, Int.floor_zero]
  rfl

/-- Concrete vertex list of the singleton support `{(0,0)}`. -/
lemma npVertices_zeroSingleton (h : ({((0 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)).Nonempty) :
    npVertices {((0 : ℕ), (0 : ℕ))} h = [((0 : ℕ), (0 : ℕ))] := by
  have h0 : ∀ P ∈ ({((0 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)), P.2 = 0 := by
    intro P hP; rw [Finset.mem_singleton] at hP; subst hP; rfl
  unfold npVertices npVerticesFull hullAbscissae
  rw [hullDots_of_heights_zero _ h h0]
  have himg : ({((0 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)).image Prod.fst = {0} := by decide
  rw [himg]
  have hsort : ({(0 : ℕ)} : Finset ℕ).sort (· ≤ ·) = [0] := by
    rw [Finset.sort_singleton]
  rw [hsort]
  have hd : hullDotAt {((0 : ℕ), (0 : ℕ))} h 0 = ((0 : ℕ), (0 : ℕ)) := by
    unfold hullDotAt
    rw [hullHeightAt_of_heights_zero _ h h0]
  rw [List.map_cons, List.map_nil, hd]
  rfl

/-- Concrete vertex list of the two-dot horizontal support `{(0,0), (1,0)}`. -/
lemma npVertices_zeroPair
    (h : ({((0 : ℕ), (0 : ℕ)), ((1 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)).Nonempty) :
    npVertices {((0 : ℕ), (0 : ℕ)), ((1 : ℕ), (0 : ℕ))} h
      = [((0 : ℕ), (0 : ℕ)), ((1 : ℕ), (0 : ℕ))] := by
  have h0 : ∀ P ∈ ({((0 : ℕ), (0 : ℕ)), ((1 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)), P.2 = 0 := by
    intro P hP
    rw [Finset.mem_insert, Finset.mem_singleton] at hP
    rcases hP with rfl | rfl <;> rfl
  unfold npVertices npVerticesFull hullAbscissae
  rw [hullDots_of_heights_zero _ h h0]
  have himg : ({((0 : ℕ), (0 : ℕ)), ((1 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)).image Prod.fst
      = {0, 1} := by decide
  rw [himg]
  have hsort : ({(0 : ℕ), (1 : ℕ)} : Finset ℕ).sort (· ≤ ·) = [0, 1] := by
    have h1 : ∀ b ∈ ({(1 : ℕ)} : Finset ℕ), 0 ≤ b := fun b _ => Nat.zero_le b
    have h2 : (0 : ℕ) ∉ ({(1 : ℕ)} : Finset ℕ) := by decide
    rw [Finset.sort_insert (fun x1 x2 : ℕ => x1 ≤ x2) h1 h2, Finset.sort_singleton]
  rw [hsort]
  have hd : ∀ i : ℕ, hullDotAt {((0 : ℕ), (0 : ℕ)), ((1 : ℕ), (0 : ℕ))} h i = (i, (0 : ℕ)) := by
    intro i
    unfold hullDotAt
    rw [hullHeightAt_of_heights_zero _ h h0]
  rw [List.map_cons, List.map_cons, List.map_nil, hd 0, hd 1]
  rfl

/-- **NEGATIVE RESULT (HULL_BLUEPRINT item 4, falsity witness).** The two-hypothesis hull-invariance
statement (`hpres` + `habove` alone, exactly the original
`Classifier.npVertices_stable_of_hull_preserved` contract) is FALSE: `S' = {(0,0)}`,
`S = {(0,0), (1,0)}` satisfy both hypotheses but have different vertex lists. Any true repair needs
abscissa control on `S` (e.g. every `S`-abscissa is an `S'`-abscissa). -/
theorem npVertices_not_stable_of_hull_preserved :
    ¬ ∀ (S S' : Finset (ℕ × ℕ)) (hS : S.Nonempty) (hS' : S'.Nonempty),
        (∀ P ∈ npVertices S' hS', P ∈ S) →
        (∀ P ∈ S, npHeight S' hS' (P.1 : ℚ) ≤ (P.2 : ℚ)) →
        npVertices S hS = npVertices S' hS' := by
  intro hcl
  have hS : ({((0 : ℕ), (0 : ℕ)), ((1 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)).Nonempty :=
    ⟨((0 : ℕ), (0 : ℕ)), by simp⟩
  have hS' : ({((0 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)).Nonempty := ⟨((0 : ℕ), (0 : ℕ)), by simp⟩
  have h0S' : ∀ P ∈ ({((0 : ℕ), (0 : ℕ))} : Finset (ℕ × ℕ)), P.2 = 0 := by
    intro P hP; rw [Finset.mem_singleton] at hP; subst hP; rfl
  have h := hcl _ _ hS hS'
    (fun P hP => by
      rw [npVertices_zeroSingleton hS', List.mem_singleton] at hP
      subst hP
      simp)
    (fun P _ => by
      rw [npHeight_of_heights_zero _ hS' h0S']
      exact Nat.cast_nonneg _)
  rw [npVertices_zeroPair hS, npVertices_zeroSingleton hS'] at h
  exact absurd h (by decide)

/-! ## TODO: M2 wiring (do NOT build against M2 yet)

When `LeanUrat.OM.PadicValuation` (M2) lands, M3 instantiates the abstract support:

```
-- import LeanUrat.OM.PadicValuation
variable {p : ℕ} [Fact p.Prime] (f : ℤ_[p][X])
def npSupport (f : ℤ_[p][X]) : Finset (ℕ × ℕ) := LeanUrat.OM.PadicValuation.valSupport f
-- nonemptiness from `valSupport_facts` (contains `(natDegree f, 0)` for monic `f`):
lemma npSupport_nonempty (hf : f.Monic) : (npSupport f).Nonempty := …
-- then  npHeight f := npHeight (npSupport f) (npSupport_nonempty hf)   etc.
```

and the L4 bridge `toLatticePolygon` / `toSideFace` (`def:to-lattice`, `def:side-to-l4face`) builds a
`LeanUrat.L4.LatticePolygon` with `ceilHeights i := (npHeight … i).ceil.toNat`,
`isVertex i := decide (i ∈ (npVertices …).map Prod.fst)`. The `L4.LatticePolygon` target type and its
consumers (`L4.newtonExponent`, `L4.newtonVertexCount`, `L4.bb1Value`, `L4.columnMeasure`,
`L4.cellVolume_eq`) are already proved in `LeanUrat.L4`.
-/

end LeanUrat.OM.NewtonPolygon
