/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib
import LeanUrat.OM.PadicLift
import LeanUrat.OM.PadicValuation
import LeanUrat.OM.ClassifierBridgeFiber2
import LeanUrat.OM.WildMenu

/-!
# QpType — genuine ℚ_p-factorization vocabulary (Wave 2a,
`notes/WILD_WAVE2_BLUEPRINT_2026-07-21.md` §2 W2a)

The repo's first formal vocabulary for "the (e,f) of an irreducible factor of `f : ℤ_[p][X]`
over ℚ_p". Mathlib at the pin has no `IsNonarchimedeanLocalField`, no finite-extension
`Valued`/`HasExtension`, and no DVR-ness of `integralClosure ℤ_[p] L` — so per the survey verdict
(blueprint §1, Rank 1) the local-field data is CARRIED AS HYPOTHESIS DATA in a bundle:

* `LocalFactorData p g` — a field `L`/ℚ_p of degree `deg g` generated by a root of `g`, together
  with a DVR `O` that is the integral closure of ℤ_[p] in `L`, lying over ℤ_[p]; `eOf`/`fOf` read
  the genuine mathlib `Ideal.ramificationIdx`/`Ideal.inertiaDeg` (2-arg forms) off the bundle.
* **Non-vacuity witness (mandatory gate, the U1 lesson):** `trivialFactorData` inhabits the bundle
  at `g = X`, `L = ℚ_[p]`, `O = ℤ_[p]`, with `eOf = fOf = 1` PROVED — the bundle is not a
  compiled `False`.
* **Axiom-free Eisenstein theorems on the wild gate fiber** (blueprint §2 W2a-3(a)): the n = 2
  minimal-H wild stratum conditions `v(a₀) = 1 ∧ v(a₁) ≥ 1` force irreducibility over ℚ_p
  (`wildFiber_irreducible`), and membership in the LEVEL-N CLASSIFIER FIBER of the Wave-1 gate
  shape `Tselfloop 2 ((0,1),(2,0)) [(1,1)]` forces those valuation conditions
  (`wildGateFiber_valuation`), hence irreducibility (`wildGateFiber_eisenstein`). This makes part
  of the Wave-2 faithfulness content UNCONDITIONAL and gives the future `om_leaf_faithful` axiom
  its mutation-consistency cross-check.
* `QpFactorization p f` / `qpType` — the packaging: a factorization of `f` into monic
  ℚ_p-irreducible factors, each with its bundle, and the induced `FactorizationType`
  (the multiset of `(eOf, fOf)`); non-vacuity witness `trivialQpFactorization` with
  `qpType = {(1,1)}` proved.

The bridge from box-level digit conditions to genuine ℤ_[p] valuations is
`valuation_eq_of_toZModPow_ne_zero`: below level N, `PadicLift.zmodValuation` composed with
`PadicInt.toZModPow` READS the genuine `PadicInt.valuation` (blueprint §3 last bullet).

Leaf module: no existing file is modified. **No axiom, no sorry** — every declaration here is
core-only (see the AxCheck section at the bottom).
-/

set_option linter.style.longLine false
set_option linter.style.header false

namespace LeanUrat.OM.QpType

open Polynomial IsLocalRing
open LeanUrat LeanUrat.OM
open LeanUrat.OM.CellMenu

/-! ## Block 1 — the bundle and its (e,f) invariants -/

/-- **The local-factor bundle** (blueprint §2 W2a-1). For `g : ℤ_[p][X]`, the data of
* a field `L`, an algebra over ℚ_[p] (and coherently over ℤ_[p]), of ℚ_p-dimension `deg g`,
  generated by a root of `g`;
* "the integers of `L`": a commutative-ring carrier `O` that is a DVR, an algebra over ℤ_[p]
  and inside `L` (scalar-tower coherent), pinned as THE integral closure of ℤ_[p] in `L`
  (`IsIntegralClosure O ℤ_[p] L`), whose maximal ideal lies over `p·ℤ_[p]`.

Mathlib at the pin cannot PROVE this bundle inhabited for wild `g` of degree ≥ 2 (no DVR-ness of
`integralClosure ℤ_[p] L`); the Wave-2b axiom carries exactly that existence content. The bundle
TYPE is inhabited (degree 1): `trivialFactorData` below. -/
structure LocalFactorData (p : ℕ) [Fact p.Prime] (g : ℤ_[p][X]) where
  /-- The local factor field. -/
  L : Type
  [fieldL : Field L]
  [algQL : Algebra ℚ_[p] L]
  [algZL : Algebra ℤ_[p] L]
  [towerZQL : IsScalarTower ℤ_[p] ℚ_[p] L]
  /-- `L` has ℚ_p-degree `deg g`. -/
  finrank_eq : Module.finrank ℚ_[p] L = g.natDegree
  /-- `L` is generated over ℚ_p by a root of `g`. -/
  hasRoot : ∃ x : L, Polynomial.aeval x (g.map (algebraMap ℤ_[p] ℚ_[p])) = 0 ∧
    Algebra.adjoin ℚ_[p] {x} = ⊤
  /-- The integers of `L`. -/
  O : Type
  [crO : CommRing O]
  [domO : IsDomain O]
  [dvrO : IsDiscreteValuationRing O]
  [algZO : Algebra ℤ_[p] O]
  [algOL : Algebra O L]
  [towerZOL : IsScalarTower ℤ_[p] O L]
  /-- `O` is THE integral closure of ℤ_[p] in `L`. -/
  [intClosure : IsIntegralClosure O ℤ_[p] L]
  /-- The maximal ideal of `O` lies over the maximal ideal `p·ℤ_[p]`. -/
  [liesOver : (IsLocalRing.maximalIdeal O).LiesOver (IsLocalRing.maximalIdeal ℤ_[p])]

variable (p : ℕ) [hp : Fact p.Prime]

/-- **The ramification index** of the bundle: mathlib's genuine 2-arg
`Ideal.ramificationIdx (maximalIdeal ℤ_[p]) (maximalIdeal O)`. -/
noncomputable def eOf {g : ℤ_[p][X]} (D : LocalFactorData p g) : ℕ :=
  letI := D.crO
  letI := D.domO
  letI := D.dvrO
  letI := D.algZO
  Ideal.ramificationIdx (IsLocalRing.maximalIdeal ℤ_[p]) (IsLocalRing.maximalIdeal D.O)

/-- **The residual (inertia) degree** of the bundle: mathlib's genuine 2-arg
`Ideal.inertiaDeg (maximalIdeal ℤ_[p]) (maximalIdeal O)`. -/
noncomputable def fOf {g : ℤ_[p][X]} (D : LocalFactorData p g) : ℕ :=
  letI := D.crO
  letI := D.domO
  letI := D.dvrO
  letI := D.algZO
  Ideal.inertiaDeg (IsLocalRing.maximalIdeal ℤ_[p]) (IsLocalRing.maximalIdeal D.O)

/-- The `(e, f)` pair of the bundle. -/
noncomputable def efOf {g : ℤ_[p][X]} (D : LocalFactorData p g) : ℕ × ℕ :=
  (eOf p D, fOf p D)

/-! ## Block 2 — the non-vacuity witness (mandatory gate, the U1 lesson) -/

/-- **The degree-1 witness**: `g = X`, `L = ℚ_[p]`, `O = ℤ_[p]`. Every instance field is
discharged from mathlib (`ℤ_[p]` is a DVR, integrally closed in its fraction field `ℚ_[p]`);
the bundle type is INHABITED. -/
noncomputable def trivialFactorData : LocalFactorData p (X : ℤ_[p][X]) where
  L := ℚ_[p]
  fieldL := inferInstance
  algQL := inferInstance
  algZL := inferInstance
  towerZQL := inferInstance
  finrank_eq := by simp
  hasRoot := ⟨0, by simp, Subsingleton.elim _ _⟩
  O := ℤ_[p]
  crO := inferInstance
  domO := inferInstance
  dvrO := inferInstance
  algZO := inferInstance
  algOL := inferInstance
  towerZOL := inferInstance
  intClosure := inferInstance
  liesOver := ⟨by simp [Ideal.under]⟩

/-- **The witness is unramified: `e = 1`.** `ramificationIdx m m = 1` over the identity algebra:
`m ≤ m^1` but `m ≰ m^2` (else `v_p(p) ≥ 2`). -/
theorem eOf_trivialFactorData : eOf p (trivialFactorData p) = 1 := by
  show Ideal.ramificationIdx (maximalIdeal ℤ_[p]) (maximalIdeal ℤ_[p]) = 1
  have hle : Ideal.map (algebraMap ℤ_[p] ℤ_[p]) (maximalIdeal ℤ_[p]) ≤ (maximalIdeal ℤ_[p]) ^ 1 := by
    rw [Algebra.algebraMap_self, Ideal.map_id, pow_one]
  have hgt : ¬ Ideal.map (algebraMap ℤ_[p] ℤ_[p]) (maximalIdeal ℤ_[p]) ≤ (maximalIdeal ℤ_[p]) ^ 2 := by
    rw [Algebra.algebraMap_self, Ideal.map_id, PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow]
    intro hle2
    have hmem : (p : ℤ_[p]) ∈ Ideal.span {(p : ℤ_[p]) ^ 2} :=
      hle2 (Ideal.mem_span_singleton_self _)
    have h2 := (PadicInt.mem_span_pow_iff_le_valuation _ (PadicInt.prime_p).ne_zero 2).mp hmem
    rw [PadicInt.valuation_p] at h2
    omega
  exact Ideal.ramificationIdx_spec hle hgt

/-- Instance-generic helper: an algebra whose structure map is bijective has `finrank 1`.
(Stated with the `Algebra` instance as a unification target so it applies to the
`Ideal.Quotient.algebraOfLiesOver` instance produced by `Ideal.inertiaDeg_algebraMap`.) -/
theorem finrank_self_of_algebraMap_bijective (R S : Type*) [CommRing R] [Nontrivial R]
    [CommRing S] [Algebra R S] (hbij : Function.Bijective (algebraMap R S)) :
    Module.finrank R S = 1 := by
  have e := LinearEquiv.ofBijective (Algebra.linearMap R S) hbij
  rw [← e.finrank_eq, Module.finrank_self]

/-- Instance-generic helper: a surjective base `algebraMap A B` induces a bijective
`algebraMap (A ⧸ q) (B ⧸ P)` on quotients along a `LiesOver` (injectivity from the
`FaithfulSMul` instance of the lying-over algebra). Stated generically so that the
`Ideal.Quotient.algebraOfLiesOver` instance is the unique one in scope. -/
theorem quotientSelf_algebraMap_bijective {A B : Type*} [CommRing A] [CommRing B]
    [Algebra A B] (q : Ideal A) (P : Ideal B) [P.LiesOver q]
    (hsurj : Function.Surjective (algebraMap A B)) :
    Function.Bijective (algebraMap (A ⧸ q) (B ⧸ P)) := by
  constructor
  · exact FaithfulSMul.algebraMap_injective _ _
  · intro w
    obtain ⟨y, rfl⟩ := Ideal.Quotient.mk_surjective w
    obtain ⟨x, rfl⟩ := hsurj y
    exact ⟨Ideal.Quotient.mk q x, by rw [Ideal.Quotient.algebraMap_mk_of_liesOver]⟩

/-- **The witness has trivial residue extension: `f = 1`.** `inertiaDeg m m = 1`: the residue
"extension" `ℤ_[p]/m → ℤ_[p]/m` is the identity, of `finrank` 1 (via the bijective
`Algebra.linearMap`). -/
theorem fOf_trivialFactorData : fOf p (trivialFactorData p) = 1 := by
  haveI hLO : (maximalIdeal ℤ_[p]).LiesOver (maximalIdeal ℤ_[p]) := ⟨by simp [Ideal.under]⟩
  haveI : Nontrivial (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) :=
    Ideal.Quotient.nontrivial_iff.mpr (Ideal.IsMaximal.ne_top inferInstance)
  show Ideal.inertiaDeg (maximalIdeal ℤ_[p]) (maximalIdeal ℤ_[p]) = 1
  rw [Ideal.inertiaDeg_algebraMap]
  -- pin the quotient algebra to the `algebraOfLiesOver` instance the goal carries
  -- (plain TC synthesis would find `Algebra.id` instead)
  letI : Algebra (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) :=
    Ideal.Quotient.algebraOfLiesOver (maximalIdeal ℤ_[p]) (maximalIdeal ℤ_[p])
  exact finrank_self_of_algebraMap_bijective _ _
    (quotientSelf_algebraMap_bijective _ _ (fun y => ⟨y, rfl⟩))

/-- The witness pair is `(1, 1)`. -/
theorem efOf_trivialFactorData : efOf p (trivialFactorData p) = (1, 1) := by
  unfold efOf
  rw [eOf_trivialFactorData, fOf_trivialFactorData]

/-! ## Block 3a — the ℤ_[p]-valuation ↔ box-digit bridge

`v_p` reads through `toZModPow` below level `N` (blueprint §3, last bullet): for `x : ℤ_[p]` with
nonzero level-`N` residue, the `ZMod(p^N)`-native `PadicLift.zmodValuation` of the residue IS the
genuine `PadicInt.valuation` of `x` (and that valuation is `< N`). -/

/-- The genuine valuation of a natural-number cast: `v_p((m : ℤ_[p])) = (m.factorization p)`.
(Both sides use the `v(0) = 0` convention.) -/
theorem valuation_natCast_factorization (m : ℕ) :
    ((m : ℤ_[p])).valuation = m.factorization p := by
  have h1 := PadicInt.valuation_coe ((m : ℕ) : ℤ_[p])
  rw [PadicInt.coe_natCast, Padic.valuation_natCast] at h1
  rw [Nat.factorization_def m hp.out]
  exact_mod_cast h1.symm

/-- Negation preserves the valuation (unit factor `-1`). -/
theorem valuation_neg (x : ℤ_[p]) : (-x).valuation = x.valuation := by
  by_cases hx : x = 0
  · rw [hx, neg_zero]
  · have h := PadicInt.valuation_mul (x := (-1 : ℤ_[p])) (y := x)
      (neg_ne_zero.mpr one_ne_zero) hx
    rw [neg_one_mul] at h
    rw [h, M2.valuation_eq_zero_of_isUnit p isUnit_one.neg, zero_add]

/-- **The decode bridge.** If the level-`N` residue of `x : ℤ_[p]` is nonzero, then `x ≠ 0`,
the box-native valuation of the residue equals the genuine valuation of `x`, and that valuation
is `< N`. (Ultrametric argument against the congruence `x ≡ (toZModPow N x).val mod p^N`.) -/
theorem valuation_eq_of_toZModPow_ne_zero {N : ℕ} {x : ℤ_[p]}
    (hy : PadicInt.toZModPow N x ≠ 0) :
    x ≠ 0 ∧ x.valuation = PadicLift.zmodValuation p N (PadicInt.toZModPow N x) ∧
      x.valuation < N := by
  haveI : NeZero (p ^ N) := ⟨pow_ne_zero N hp.out.ne_zero⟩
  have hx0 : x ≠ 0 := fun h => hy (by rw [h, map_zero])
  set y := PadicInt.toZModPow N x with hy_def
  -- 0 < N (else `ZMod (p^0)` has only the zero residue)
  have hN : 0 < N := by
    by_contra hN0
    have hN0' : N = 0 := by omega
    subst hN0'
    have hval : y.val < 1 := by simpa using ZMod.val_lt y
    exact hy ((ZMod.val_eq_zero y).mp (by omega))
  -- the canonical representative
  set m := y.val with hm_def
  have hm0 : m ≠ 0 := by rwa [hm_def, Ne, ZMod.val_eq_zero]
  have hcast : ((m : ℕ) : ZMod (p ^ N)) = y := ZMod.natCast_rightInverse y
  -- congruence: x ≡ m  (mod p^N)
  have hsub : x - (m : ℤ_[p]) ∈ Ideal.span {(p : ℤ_[p]) ^ N} := by
    rw [← PadicInt.ker_toZModPow, RingHom.mem_ker, map_sub, map_natCast, hcast, sub_self]
  -- the box valuation is the factorization of the representative, and is < N
  have hw_eq : PadicLift.zmodValuation p N y = m.factorization p :=
    PadicLift.zmodValuation_of_ne_zero p hy
  have hwlt : PadicLift.zmodValuation p N y < N := PadicLift.zmodValuation_lt p hN hy
  have hmval : ((m : ℤ_[p])).valuation = m.factorization p :=
    valuation_natCast_factorization p m
  have hmne : (m : ℤ_[p]) ≠ 0 := Nat.cast_ne_zero.mpr hm0
  by_cases hd : x - (m : ℤ_[p]) = 0
  · -- x = m exactly
    have hxm : x = (m : ℤ_[p]) := sub_eq_zero.mp hd
    refine ⟨hx0, ?_, ?_⟩
    · rw [hxm, hmval, hw_eq]
    · rw [hxm, hmval]; omega
  · -- ultrametric two-sided bound
    have hdN : N ≤ (x - (m : ℤ_[p])).valuation :=
      (PadicInt.mem_span_pow_iff_le_valuation _ hd N).mp hsub
    -- upper: v(x) ≤ w
    have hxup : x.valuation ≤ m.factorization p := by
      have hxm : (m : ℤ_[p]) = x + -(x - (m : ℤ_[p])) := by ring
      have hmin : min x.valuation ((-(x - (m : ℤ_[p]))).valuation)
          ≤ ((x + -(x - (m : ℤ_[p])))).valuation := by
        apply PadicInt.le_valuation_add
        rw [← hxm]; exact hmne
      rw [← hxm, hmval, valuation_neg] at hmin
      omega
    -- lower: w ≤ v(x)
    have hxlo : m.factorization p ≤ x.valuation := by
      have hxm : x = (m : ℤ_[p]) + (x - (m : ℤ_[p])) := by ring
      have hmin : min ((m : ℤ_[p])).valuation ((x - (m : ℤ_[p])).valuation)
          ≤ (((m : ℤ_[p]) + (x - (m : ℤ_[p])))).valuation := by
        apply PadicInt.le_valuation_add
        rw [← hxm]; exact hx0
      rw [← hxm, hmval] at hmin
      omega
    refine ⟨hx0, ?_, ?_⟩
    · rw [hw_eq]; omega
    · omega

/-- **Decoder (exact digit).** A box-native valuation value `v < N` decodes to the genuine
valuation: `zmodValuation N (toZModPow N x) = v → x ≠ 0 ∧ v_p(x) = v`. -/
theorem valuation_eq_of_zmodValuation_lt {N v : ℕ} {x : ℤ_[p]} (hvN : v < N)
    (h : PadicLift.zmodValuation p N (PadicInt.toZModPow N x) = v) :
    x ≠ 0 ∧ x.valuation = v := by
  have hy : PadicInt.toZModPow N x ≠ 0 := by
    intro h0
    rw [h0, PadicLift.zmodValuation_zero] at h
    omega
  obtain ⟨hx0, heq, -⟩ := valuation_eq_of_toZModPow_ne_zero p hy
  exact ⟨hx0, by rw [heq, h]⟩

/-- **Decoder (lower bound).** A box-native valuation `≥ 1` decodes to membership in the maximal
ideal `p·ℤ_[p]` (correctly absorbing the `x = 0` / vanished-residue cases). -/
theorem mem_maximalIdeal_of_one_le_zmodValuation {N : ℕ} (hN : 0 < N) {x : ℤ_[p]}
    (h : 1 ≤ PadicLift.zmodValuation p N (PadicInt.toZModPow N x)) :
    x ∈ maximalIdeal ℤ_[p] := by
  rw [PadicInt.maximalIdeal_eq_span_p]
  by_cases hy : PadicInt.toZModPow N x = 0
  · -- vanished residue: x ∈ (p^N) ≤ (p)
    have hker : x ∈ Ideal.span {(p : ℤ_[p]) ^ N} := by
      rw [← PadicInt.ker_toZModPow]; exact RingHom.mem_ker.mpr hy
    exact Ideal.span_singleton_le_span_singleton.mpr (dvd_pow_self _ hN.ne') hker
  · obtain ⟨hx0, heq, -⟩ := valuation_eq_of_toZModPow_ne_zero p hy
    have h1 : 1 ≤ x.valuation := by omega
    have := (PadicInt.mem_span_pow_iff_le_valuation x hx0 1).mpr h1
    simpa [pow_one] using this

/-! ## Block 3b — the axiom-free Eisenstein theorem on the wild gate stratum -/

/-- **The gate stratum conditions are Eisenstein.** For monic `f` of degree 2 with `v(a₀) = 1`
and `a₁ ∈ (p)`: `f` is Eisenstein at `p·ℤ_[p]`. -/
theorem isEisensteinAt_of_wildGate {f : ℤ_[p][X]} (hf : f.Monic) (hdeg : f.natDegree = 2)
    (h0 : (f.coeff 0).valuation = 1) (h1 : f.coeff 1 ∈ maximalIdeal ℤ_[p]) :
    f.IsEisensteinAt (maximalIdeal ℤ_[p]) := by
  have ha0 : f.coeff 0 ≠ 0 := by
    intro h
    rw [h, PadicInt.valuation_zero] at h0
    omega
  constructor
  · rw [hf.leadingCoeff]
    intro hmem
    exact (Ideal.IsMaximal.ne_top inferInstance)
      (Ideal.eq_top_of_isUnit_mem _ hmem isUnit_one)
  · intro n hn
    rw [hdeg] at hn
    interval_cases n
    · rw [PadicInt.maximalIdeal_eq_span_p]
      have hm := (PadicInt.mem_span_pow_iff_le_valuation _ ha0 1).mpr (by omega)
      simpa [pow_one] using hm
    · exact h1
  · rw [PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow]
    intro hmem
    have h2 := (PadicInt.mem_span_pow_iff_le_valuation _ ha0 2).mp hmem
    omega

/-- **The abstract Eisenstein theorem (membership form).** Monic degree-2 `f` with `v(a₀) = 1`
and `a₁ ∈ p·ℤ_[p]` is irreducible over ℚ_p. (Eisenstein irreducibility over ℤ_[p], transferred
to the fraction field by Gauss's lemma for the integrally closed ℤ_[p].) -/
theorem wildFiber_irreducible' {f : ℤ_[p][X]} (hf : f.Monic) (hdeg : f.natDegree = 2)
    (h0 : (f.coeff 0).valuation = 1) (h1 : f.coeff 1 ∈ maximalIdeal ℤ_[p]) :
    Irreducible (f.map (algebraMap ℤ_[p] ℚ_[p])) := by
  have hEis := isEisensteinAt_of_wildGate p hf hdeg h0 h1
  have hirr : Irreducible f :=
    hEis.irreducible (Ideal.IsMaximal.isPrime inferInstance) hf.isPrimitive (by omega)
  exact (hf.irreducible_iff_irreducible_map_fraction_map (K := ℚ_[p])).mp hirr

/-- **The abstract Eisenstein theorem (valuation form, blueprint literal).** Monic degree-2 `f`
with `v(a₀) = 1` and `v(a₁) ≥ 1` is irreducible over ℚ_p. (With mathlib's `v(0) = 0` convention
this form excludes `a₁ = 0`; the membership form `wildFiber_irreducible'` is the faithful one and
is what the fiber link uses.) -/
theorem wildFiber_irreducible {f : ℤ_[p][X]} (hf : f.Monic) (hdeg : f.natDegree = 2)
    (h0 : (f.coeff 0).valuation = 1) (h1 : 1 ≤ (f.coeff 1).valuation) :
    Irreducible (f.map (algebraMap ℤ_[p] ℚ_[p])) := by
  refine wildFiber_irreducible' p hf hdeg h0 ?_
  by_cases hc : f.coeff 1 = 0
  · rw [hc]; exact Ideal.zero_mem _
  · rw [PadicInt.maximalIdeal_eq_span_p]
    have hm := (PadicInt.mem_span_pow_iff_le_valuation _ hc 1).mpr h1
    simpa [pow_one] using hm

/-! ## Block 3c — the fiber link: the Wave-1 gate fiber forces the Eisenstein conditions

The Wave-1 wild gate shape at `n = 2`, `σ = {(2,1)}` is
`Tselfloop 2 ((0,1),(2,0)) [(1,1)]` (= `WildMenu.ramShape 2 σ`, see `ramShape_gate`). Membership
of `toBox f` in its level-`N` classifier fiber (`N ≥ 2`) pins the digit conditions
`vOf 0 = 1 ∧ vOf 1 ≥ 1` (via `classify_eq_selfloop_iff` + `inCell_mkCell_iff`), which decode to
the genuine `v(a₀) = 1 ∧ a₁ ∈ (p)` — hence Eisenstein irreducibility over ℚ_p. -/

/-- The gate menu path `[(0,1),(2,0)]` (the minimal-H self-loop, `H = fSum σ = 1`). -/
def gatePath : List (ℕ × ℕ) := [(0, 1), (2, 0)]

/-- The gate side `((0,1),(2,0))` (slope `−1/2`). -/
def gateSide : (ℕ × ℕ) × (ℕ × ℕ) := ((0, 1), (2, 0))

/-- The gate residual shape `[(1,1)]` (one linear residual factor, μ = 1). -/
def gateShape : List (ℕ × ℕ) := [(1, 1)]

theorem sidePairs_gatePath : sidePairs gatePath = [gateSide] := rfl

theorem menuPath_gate {N : ℕ} (hN : 2 ≤ N) : MenuPath 2 N gatePath :=
  ⟨1, (2, 0), [], rfl, le_refl 1, by omega, by norm_num, by norm_num, ChainOK.nil rfl rfl⟩

theorem shapesFor_gate : ShapesFor gatePath [gateShape] := by
  unfold ShapesFor
  rw [sidePairs_gatePath]
  refine List.Forall₂.cons ?_ List.Forall₂.nil
  rw [mem_shapesOfDegree_iff]
  refine ⟨List.pairwise_singleton _ _, ?_, ?_⟩
  · intro q hq
    rw [gateShape, List.mem_singleton] at hq
    subst hq
    exact ⟨le_refl 1, le_refl 1⟩
  · rfl

/-- **The gate shape is the Wave-1 menu literal**: `ramShape 2 {(2,1)}` is exactly
`Tselfloop 2 gateSide gateShape`. -/
theorem ramShape_gate :
    WildMenu.ramShape 2 ⟨{((2 : ℕ), (1 : ℕ))}⟩
      = some (ClassifierBridgeFiber.Tselfloop 2 gateSide gateShape) := by
  have hc : WildMenu.constERam 2 ⟨{((2 : ℕ), (1 : ℕ))}⟩ := by
    refine ⟨2, le_refl 2, by simp, ?_, by simp [WildMenu.fSum]⟩
    intro pr hpr
    simp only [Multiset.mem_singleton] at hpr
    subst hpr
    exact ⟨rfl, le_refl 1⟩
  have hf1 : WildMenu.fSum ⟨{((2 : ℕ), (1 : ℕ))}⟩ = 1 := by
    simp [WildMenu.fSum]
  have hws : WildMenu.wShape ⟨{((2 : ℕ), (1 : ℕ))}⟩ = [(1, 1)] := by
    simp [WildMenu.wShape, Multiset.sort_singleton]
  rw [WildMenu.ramShape_of_constERam hc, hf1, hws]
  rfl

/-- **The fiber link (the direction the coherence probe needs).** If `toBox f` lies in the
level-`N` classifier fiber of the gate shape (`N ≥ 2`), then the genuine Eisenstein conditions
hold: `v(a₀) = 1` and `a₁ ∈ p·ℤ_[p]`. -/
theorem wildGateFiber_valuation {N : ℕ} (hN0 : 0 < N) (hN2 : 2 ≤ N) {f : ℤ_[p][X]}
    (hf : f.Monic) (hdeg : f.natDegree = 2)
    (hfib : B.classify p 2 N (PadicLift.toBox p 2 N hN0 f hf hdeg)
      = ClassifierBridgeFiber.Tselfloop 2 gateSide gateShape) :
    (f.coeff 0).valuation = 1 ∧ f.coeff 1 ∈ maximalIdeal ℤ_[p] := by
  set fbox := PadicLift.toBox p 2 N hN0 f hf hdeg with hfbox
  -- fiber → InCell → Matches
  have hIn : InCell p fbox (mkCell 2 gatePath [gateShape]) :=
    (ClassifierBridgeFiber2.classify_eq_selfloop_iff 2 N hN0 (by norm_num) gatePath
      (menuPath_gate hN2) gateSide sidePairs_gatePath gateShape shapesFor_gate
      (by intro q hq; rw [gateShape, List.mem_singleton] at hq; subst hq; rfl)
      (by simp [gateShape]) fbox).mp hfib
  have hM : Matches p fbox gatePath [gateShape] :=
    (inCell_mkCell_iff p (menuPath_gate hN2) shapesFor_gate).mp hIn
  -- the box digit conditions
  have hv0 : vOf p fbox 0 = 1 := hM.1 (0, 1) (by simp [gatePath])
  have hSM : SideMatch p fbox gateShape gateSide := by
    have h2 := hM.2
    rw [sidePairs_gatePath] at h2
    cases h2 with
    | cons h _ => exact h
  have hv1 : 1 ≤ vOf p fbox 1 := by
    have hline := hSM.1 1 (by norm_num [gateSide]) (by norm_num [gateSide])
    have hhalf : lineAt gateSide ((1 : ℕ) : ℚ) = 1 / 2 := by
      norm_num [lineAt, slopeQ, gateSide]
    rw [hhalf] at hline
    by_contra hlt
    rw [not_le] at hlt
    have h00 : vOf p fbox 1 = 0 := by omega
    rw [h00] at hline
    norm_num at hline
  -- decode through toBox
  have hvOf : ∀ i, vOf p fbox i
      = PadicLift.zmodValuation p N (PadicInt.toZModPow N (f.coeff i)) := by
    intro i
    simp only [vOf, hfbox, PadicLift.toBox_val, Polynomial.coeff_map]
  rw [hvOf 0] at hv0
  rw [hvOf 1] at hv1
  obtain ⟨-, hval0⟩ := valuation_eq_of_zmodValuation_lt p (by omega : 1 < N) hv0
  exact ⟨hval0, mem_maximalIdeal_of_one_le_zmodValuation p hN0 hv1⟩

/-- **Machine-checked coherence probe (blueprint W2a-3(a) + W2b mutation check).** Membership in
the level-`N` gate fiber forces IRREDUCIBILITY over ℚ_p — unconditionally, no axiom. Any Wave-2b
axiom mutation asserting a SPLIT type on this fiber contradicts this theorem. -/
theorem wildGateFiber_eisenstein {N : ℕ} (hN0 : 0 < N) (hN2 : 2 ≤ N) {f : ℤ_[p][X]}
    (hf : f.Monic) (hdeg : f.natDegree = 2)
    (hfib : B.classify p 2 N (PadicLift.toBox p 2 N hN0 f hf hdeg)
      = ClassifierBridgeFiber.Tselfloop 2 gateSide gateShape) :
    Irreducible (f.map (algebraMap ℤ_[p] ℚ_[p])) := by
  obtain ⟨h0, h1⟩ := wildGateFiber_valuation p hN0 hN2 hf hdeg hfib
  exact wildFiber_irreducible' p hf hdeg h0 h1

/-! ## Block 4 — `qpType` packaging -/

/-- **A ℚ_p-factorization certificate for `f : ℤ_[p][X]`**: a list of monic factors with product
`f`, each irreducible over ℚ_p, each carrying its `LocalFactorData` bundle. (List-based carrier:
the induced multiset of `(e,f)` pairs is what `qpType` extracts, so no separate permutation
clause is needed.) -/
structure QpFactorization (p : ℕ) [Fact p.Prime] (f : ℤ_[p][X]) where
  /-- The factors. -/
  factors : List (ℤ_[p][X])
  /-- They multiply to `f`. -/
  prod_eq : factors.prod = f
  /-- Each factor is monic. -/
  monic : ∀ g ∈ factors, g.Monic
  /-- Each factor is irreducible over ℚ_p. -/
  irred : ∀ g ∈ factors, Irreducible (g.map (algebraMap ℤ_[p] ℚ_[p]))
  /-- Each factor carries a local-factor bundle. -/
  data : ∀ g ∈ factors, LocalFactorData p g

/-- **The induced factorization type**: the multiset of `(eOf, fOf)` pairs of the factors. -/
noncomputable def qpType {f : ℤ_[p][X]} (F : QpFactorization p f) : FactorizationType :=
  ⟨(F.factors.pmap (fun g hg => efOf p (F.data g hg)) (fun _ h => h) : List (ℕ × ℕ))⟩

/-- **Non-vacuity witness for the packaging**: the trivial factorization of `f = X`. -/
noncomputable def trivialQpFactorization : QpFactorization p (X : ℤ_[p][X]) where
  factors := [(X : ℤ_[p][X])]
  prod_eq := List.prod_singleton
  monic := by
    intro g hg
    rw [List.mem_singleton] at hg
    subst hg
    exact monic_X
  irred := by
    intro g hg
    rw [List.mem_singleton] at hg
    subst hg
    rw [Polynomial.map_X]
    exact Polynomial.irreducible_X
  data := fun g hg => (List.mem_singleton.mp hg) ▸ trivialFactorData p

/-- The trivial factorization has type `{(1,1)}` — the packaging is inhabited with the correct
unramified degree-1 type. -/
theorem qpType_trivialQpFactorization :
    qpType p (trivialQpFactorization p) = ⟨{((1 : ℕ), (1 : ℕ))}⟩ := by
  have h : qpType p (trivialQpFactorization p)
      = ⟨([efOf p (trivialFactorData p)] : List (ℕ × ℕ))⟩ := rfl
  rw [h, efOf_trivialFactorData]
  rfl

/-! ## Block 5 — axiom census (this wave declares NO axiom; everything must be core-only) -/

section AxCheck

#print axioms LeanUrat.OM.QpType.LocalFactorData
#print axioms LeanUrat.OM.QpType.QpFactorization
#print axioms LeanUrat.OM.QpType.finrank_self_of_algebraMap_bijective
#print axioms LeanUrat.OM.QpType.quotientSelf_algebraMap_bijective
#print axioms LeanUrat.OM.QpType.gatePath
#print axioms LeanUrat.OM.QpType.gateSide
#print axioms LeanUrat.OM.QpType.gateShape
#print axioms LeanUrat.OM.QpType.sidePairs_gatePath
#print axioms LeanUrat.OM.QpType.eOf
#print axioms LeanUrat.OM.QpType.fOf
#print axioms LeanUrat.OM.QpType.efOf
#print axioms LeanUrat.OM.QpType.trivialFactorData
#print axioms LeanUrat.OM.QpType.eOf_trivialFactorData
#print axioms LeanUrat.OM.QpType.fOf_trivialFactorData
#print axioms LeanUrat.OM.QpType.efOf_trivialFactorData
#print axioms LeanUrat.OM.QpType.valuation_natCast_factorization
#print axioms LeanUrat.OM.QpType.valuation_neg
#print axioms LeanUrat.OM.QpType.valuation_eq_of_toZModPow_ne_zero
#print axioms LeanUrat.OM.QpType.valuation_eq_of_zmodValuation_lt
#print axioms LeanUrat.OM.QpType.mem_maximalIdeal_of_one_le_zmodValuation
#print axioms LeanUrat.OM.QpType.isEisensteinAt_of_wildGate
#print axioms LeanUrat.OM.QpType.wildFiber_irreducible'
#print axioms LeanUrat.OM.QpType.wildFiber_irreducible
#print axioms LeanUrat.OM.QpType.menuPath_gate
#print axioms LeanUrat.OM.QpType.shapesFor_gate
#print axioms LeanUrat.OM.QpType.ramShape_gate
#print axioms LeanUrat.OM.QpType.wildGateFiber_valuation
#print axioms LeanUrat.OM.QpType.wildGateFiber_eisenstein
#print axioms LeanUrat.OM.QpType.qpType
#print axioms LeanUrat.OM.QpType.trivialQpFactorization
#print axioms LeanUrat.OM.QpType.qpType_trivialQpFactorization

end AxCheck

end LeanUrat.OM.QpType
