/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Uniformity.ChapB.B01
import Uniformity.ChapB.B23

/-!
# Uniformity.ChapB.B25 — the order-1 residual field and the residual reduction

**Chapter B, NODE B.25** (`blueprint/CHAP-B_leaf_layer.md` §4, the order-1 residual layer).
Source: `docs/GMN_citations.md` Def 1.21, fact (I) (*"the order-1 residue field
`F_φ := F[y]/(ψ₀(y))`"*); `EFF.HE6.08`; `EFF.HE3.13` (`R_λ ∈ K[Z]` with `K` the order-1 residue
field).

For an order-1 key `φ` (B.01's `IsKey`: monic, of positive degree, with irreducible reduction),
`resField φ` is the quotient `F[y]/(φ̄)` where `F = ResidueField O` and `φ̄ = φ.map (residue O)`.
Since `φ̄` is irreducible it is a field, of degree `m = φ.natDegree` over `F` (that is B.26).
`resMk π φ k a` is the residual reduction `O[X] → resField φ` at height `k`: take B.23's digit
polynomial `digPoly π k a ∈ F[y]` and push it into the quotient.

Three declarations, all definitional:

* `resField` — an `abbrev`, deliberately: the `Field`/`Algebra F` instances that mathlib finds
  for `AdjoinRoot (φ.map (residue O))` must apply to `resField φ` without re-declaration;
* `instFieldResField` — the field structure, keyed on `hφ : IsKey φ`;
* `resMk` — the residual reduction at height `k`.

## The two repaired forms (blueprint `[repaired: A-F.3/B-D1+B-D3]`)

The stage-0e stub gate (`leanspec/Leanspec/ChapB.lean`) found the blueprint's original signature
of `instFieldResField` doubly defective; both repairs are transcribed here, and the body below is
the gate-verified one.

* **B-D1 (body).** The signed body was `AdjoinRoot.instField (hf := hφ.irred.ne_zero)`.  At our
  pin (`Mathlib/RingTheory/AdjoinRoot.lean`) `AdjoinRoot.instField` takes **no** explicit
  argument and instead requires `[Fact (Irreducible f)]`: there is no argument `hf`, and `f ≠ 0`
  is not the hypothesis it wants.  Repair: supply the `Fact` from `IsKey.irred` by `haveI`, then
  `AdjoinRoot.instField`.
* **B-D3 (kind).** The declaration was signed `noncomputable instance`, which is a HARD ERROR at
  our pin: it carries the explicit non-class hypothesis `(hφ : IsKey φ)`, so *"This instance has
  1 argument that cannot be inferred using typeclass synthesis"*.  Repair: demote to
  `@[reducible] noncomputable def` (`@[reducible]` is then forced by the linter for a class-typed
  `def`).  **Consumers must bring the field structure into scope explicitly**, by
  `letI := instFieldResField hφ` / `haveI := instFieldResField hφ` at each use site — nothing
  here is found by typeclass synthesis.  The alternative repair (making `IsKey` a class) was
  rejected upstream: it would ripple through every chapter-B signature and chapter C's tower
  carriers.

DEPENDS: B.01 (`IsKey`, and its `irred` field) · B.23 (`digPoly`) · mathlib `AdjoinRoot`,
`AdjoinRoot.instField`, `AdjoinRoot.mk`, `IsLocalRing.residue`.

**PROOF.** Definitional.  Environment ENV-A (blueprint §0.1).

## Faithfulness

`docs/GMN_citations.md` Def 1.21 verbatim: the order-1 residue field `F_φ := F[y]/(ψ₀(y))`.
`EFF.HE6.08` instead presents it as `K := F_Q(η_θ) ≅ F_{Q^{f₁}}`, a subfield of `k̄` generated by
a residue; at `e₁ = 1` the two presentations agree because `η_θ = res(θ)` is a root of `φ̄`
(`EFF.HE6.08`'s `η_θ := res(θ^{e₁} π^{−h})` degenerates to `res(θ)` at `e₁ = 1`, `h = 0`).
**This chapter uses the quotient presentation and never the subfield presentation** — the latter
needs an ambient `k̄` and the embeddings `ι_ξ`, which H-1 puts out of scope.
**Flagged for human review** (definition faithfulness).

## Status

Sorry-free, axiom-free (Lean core only).
-/

namespace Uniformity.Density.Leaf

-- ENV-A (blueprint §0.1): the polynomial arena.
variable {O : Type*} [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]

/-- **B.25 (a) — the order-1 residual field.** `resField φ = F[y]/(φ̄)` : the order-1 residual
field of the key `φ`.  An `abbrev`, so that mathlib's `Field` and `Algebra (ResidueField O)`
instances for `AdjoinRoot (φ.map (residue O))` apply to it unchanged. -/
abbrev resField (φ : Polynomial O) : Type _ :=
  AdjoinRoot (φ.map (IsLocalRing.residue O))

/-- **B.25 (b) — the field structure on the residual field.**  For an order-1 key `φ` the
reduction `φ̄` is irreducible, so the quotient `F[y]/(φ̄)` is a field.

Blueprint `[repaired: A-F.3/B-D1+B-D3]`: the body is the `Fact`-route one (B-D1), and the
declaration is a `@[reducible] noncomputable def`, **not** an `instance` (B-D3 — an `instance`
with the explicit non-class hypothesis `hφ` is rejected outright at our pin).  Consumers bring
it into scope with `letI := instFieldResField hφ`. -/
@[reducible] noncomputable def instFieldResField {φ : Polynomial O} (hφ : IsKey φ) :
    Field (resField φ) :=
  haveI : Fact (Irreducible (φ.map (IsLocalRing.residue O))) := ⟨hφ.irred⟩
  AdjoinRoot.instField

/-- **B.25 (c) — the residual reduction at height `k`.**  `resMk π φ k a` reduces `a ∈ O[X]` to
`resField φ` by taking B.23's digit polynomial `digPoly π k a ∈ F[y]` and passing to the
quotient by `φ̄`. -/
noncomputable def resMk (π : O) (φ : Polynomial O) (k : ℕ) (a : Polynomial O) : resField φ :=
  AdjoinRoot.mk (φ.map (IsLocalRing.residue O)) (digPoly π k a)

end Uniformity.Density.Leaf

/-! ## Axiom footprint -/

section AxCheck
#print axioms Uniformity.Density.Leaf.resField
#print axioms Uniformity.Density.Leaf.instFieldResField
#print axioms Uniformity.Density.Leaf.resMk
end AxCheck
