/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Uniformity.ChapB.B02

/-!
# Uniformity.ChapB.B53a — the quotient identification (step 1 of NODE B.53)

**Chapter B, NODE B.53, part (a) of the mandated 3-way split**
(`blueprint/CHAP-B_leaf_layer.md` §7). Pure commutative algebra: no valuation, no key
hypothesis, not even monicity.

The blueprint's step 1 of B.53. For `α := AdjoinRoot.root g` and `θ := AdjoinRoot.root φ`,

```
AdjoinRoot g ⧸ (φ(α))  ≅  O[X] ⧸ (g, φ)  ≅  AdjoinRoot φ ⧸ (g(θ))
                                         =  AdjoinRoot φ ⧸ (dev φ g 0 (θ)),
```

as **`O`-algebras** — the `O`-algebra structure is what makes the two sides comparable as
`O`-modules downstream (B53c compares their `Module.length O`), so the chain is assembled from
mathlib's `ₐ`-flavoured double-quotient equivalences rather than the bare `≃+*` ones.

Three declarations:

* `span_mk_eq_map_span` — `Ideal.span {AdjoinRoot.mk a b} = (Ideal.span {b}).map (mkₐ O (a))`,
  the bookkeeping that lets `DoubleQuot.quotQuotEquivQuotSupₐ` see the principal ideal
  `(φ(α))` as the pushforward of `(φ)`;
* `mk_eq_mk_dev_zero` — `AdjoinRoot.mk φ g = AdjoinRoot.mk φ (dev φ g 0)`, i.e. `g(θ)` is
  computed by the zeroth `φ`-adic development coefficient `g %ₘ φ` (B.02 at `j = 0`); this is
  the *only* place the `φ`-development enters step 1;
* `quotKeyEquiv` — the composite `O`-algebra equivalence.

The chain, with `A := AdjoinRoot g` and `B := AdjoinRoot φ`, is

```
A ⧸ (φ(α))  ≃  A ⧸ (φ).map (mk g)  ≃  O[X] ⧸ ((g) ⊔ (φ))
            ≃  O[X] ⧸ ((φ) ⊔ (g))  ≃  B ⧸ (g).map (mk φ)
            ≃  B ⧸ (g(θ))          ≃  B ⧸ ((dev φ g 0)(θ)),
```

i.e. `Ideal.quotientEquivAlgOfEq`, `DoubleQuot.quotQuotEquivQuotSupₐ`, `sup_comm`, and the same
two backwards. The symmetry `(g) ⊔ (φ) = (φ) ⊔ (g)` is the whole mathematical content — it is
the resultant symmetry `Res(g,φ) = ±Res(φ,g)` in ideal-theoretic form, and it is why B.53 can
trade a norm on `AdjoinRoot g` for a valuation on `AdjoinRoot φ`.

DEPENDS: B.02 (`dev`) · mathlib `AdjoinRoot.mk`, `AdjoinRoot.mk_self`,
`Polynomial.modByMonic_add_div`, `Ideal.map_span`, `Ideal.quotientEquivAlgOfEq`,
`DoubleQuot.quotQuotEquivQuotSupₐ`.

**Note.** `Polynomial.modByMonic_add_div` is unconditional at our pin (`p %ₘ q + q * (p /ₘ q) = p`
for *every* `q`, the non-monic branch being `p %ₘ q = p`, `p /ₘ q = 0`), so `mk_eq_mk_dev_zero`
needs no monicity either. Monicity re-enters only downstream, where `dev φ g 0` must have degree
below `φ`'s (B.03) and where `AdjoinRoot φ`/`AdjoinRoot g` must be free `O`-modules.

## Status

Sorry-free, axiom-free (Lean core only).
-/

namespace Uniformity.Density.Leaf

open Polynomial

-- ENV-A (blueprint §0.1): the polynomial arena. Nothing below uses the DVR structure; the
-- variable block matches the rest of the chapter.
variable {O : Type*} [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]

set_option linter.unusedSectionVars false in
/-- The principal ideal generated by the class of `b` in `AdjoinRoot a` is the pushforward of
`(b)` along the quotient map, in the `mkₐ` form `DoubleQuot.quotQuotEquivQuotSupₐ` wants. -/
theorem span_mk_eq_map_span (a b : Polynomial O) :
    Ideal.span {AdjoinRoot.mk a b}
      = Ideal.map (Ideal.Quotient.mkₐ O (Ideal.span {a})) (Ideal.span {b}) := by
  rw [Ideal.map_span, Set.image_singleton]
  rfl

set_option linter.unusedSectionVars false in
/-- `g(θ) = (dev φ g 0)(θ)` in `AdjoinRoot φ`: the class of `g` is the class of its zeroth
`φ`-adic development coefficient `g %ₘ φ` (B.02 at `j = 0`). -/
theorem mk_eq_mk_dev_zero (φ g : Polynomial O) :
    AdjoinRoot.mk φ g = AdjoinRoot.mk φ (dev φ g 0) := by
  have hdev : dev φ g 0 = g %ₘ φ := rfl
  rw [hdev]
  conv_lhs => rw [← Polynomial.modByMonic_add_div g φ]
  rw [map_add, map_mul, AdjoinRoot.mk_self, zero_mul, add_zero]

/-- **B.53, step 1 — the quotient identification.**
`AdjoinRoot g ⧸ (φ(α)) ≃ₐ[O] AdjoinRoot φ ⧸ ((dev φ g 0)(θ))`, both sides being
`O[X] ⧸ (g, φ)` in disguise. -/
noncomputable def quotKeyEquiv (φ g : Polynomial O) :
    (AdjoinRoot g ⧸ Ideal.span {AdjoinRoot.mk g φ}) ≃ₐ[O]
      (AdjoinRoot φ ⧸ Ideal.span {AdjoinRoot.mk φ (dev φ g 0)}) :=
  (Ideal.quotientEquivAlgOfEq O (span_mk_eq_map_span g φ)).trans <|
    (DoubleQuot.quotQuotEquivQuotSupₐ O (Ideal.span {g}) (Ideal.span {φ})).trans <|
      (Ideal.quotientEquivAlgOfEq O (sup_comm (Ideal.span {g}) (Ideal.span {φ}))).trans <|
        (DoubleQuot.quotQuotEquivQuotSupₐ O (Ideal.span {φ}) (Ideal.span {g})).symm.trans <|
          (Ideal.quotientEquivAlgOfEq O (span_mk_eq_map_span φ g)).symm.trans
            (Ideal.quotientEquivAlgOfEq O (by rw [mk_eq_mk_dev_zero φ g]))

end Uniformity.Density.Leaf

/-! ## Axiom footprint -/

section AxCheck
#print axioms Uniformity.Density.Leaf.span_mk_eq_map_span
#print axioms Uniformity.Density.Leaf.mk_eq_mk_dev_zero
#print axioms Uniformity.Density.Leaf.quotKeyEquiv
end AxCheck
