/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Uniformity.ChapC.C130cr
import Uniformity.ChapC.C130np6

/-!
# Uniformity.ChapC.C130np7 — S2-source plan node NP-7

**S2-source plan node NP-7** (`docs/in-progress/S2_SOURCE_PLAN_2026-08-24.md` §6, row NP-7:
"Construct the L-valued kernel read and its generator regressions"), consuming CC-10's
general canonical-read machinery (`C130cr`), CC-4's Laurent normalizer (`C130ln`, exported
through `C130cr`), and NP-6's residue-ambient letter (`C130np6`'s `s2AmbientLetter`).

## What this node does

`docs/in-progress/S2_SOURCE_PLAN_2026-08-24.md` §5.1 says of the `canonicalRead` field of
`SplitNodePointSource` (its exact shape read off `C130s17.lean`): "Merely typed; no landed
constructor. Construct from the Laurent normalizer and residue letters." This file supplies
exactly that: a CONCRETE inhabitant of the field's type,

```
(i : ℕ) → MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) i) →* Lˣ
```

at the S2 depth-two tower, built from the exact numeral chain `e = (2,2)`, `u = (1,5)`.

**The construction.** At the S2 numerals, the level-one kernel is the infinite cyclic group
generated by `wrapClass` alone (its height law `2p + q = 0` forces `q = -2p`, so a kernel
element is determined by its raw `π`-exponent `p`), and the level-two kernel is FREE ABELIAN
OF RANK TWO, freely generated by `{wrapClass, letterClass}` (its height law `4p + 2q + 5r = 0`
has general solution `(p, q, r) = (-m - 2t, 2m - t, 2t)` for integers `m, t`, and this is
exactly `wrapClass^m · letterClass^t` — a determinant computation, `|(-1,-2;2,-1)| = 5` is not
the check; the check is that `{(-1,2,0), (-2,-1,2)}` spans the SAME rank-two lattice as the
solution set, verified below by exhibiting the inverse formulas `m = -(p+r)`, `t = r/2`, the
latter well-defined because `r` is forced even by the height law).  The read is then defined
DIRECTLY on the kernel via these coordinate formulas, valued in `s2AmbientLetter L 1 ^ m *
s2AmbientLetter L 2 ^ t` — "construct from the Laurent normalizer [supplying the generator
coordinates, `wrapClass`/`letterClass`] and residue letters [NP-6's `s2AmbientLetter`]",
verbatim.  Off the live range `{1, 2}` the read is the trivial hom (junk; no law reads it).

**The generator regressions.** `s2CanonicalRead_wrapClass`/`s2CanonicalRead_letterClass` show
the read hits exactly `s2AmbientLetter L 1`/`s2AmbientLetter L 2` at the two distinguished
generators — the tie to NP-6's letter the plan row asks for.  Because `s2AmbientLetter` is
the constant unit `1` (NP-6: forced by `ψ = X - C 1`'s unique root, not chosen), every
generator-word read collapses to `1` (`s2CanonicalRead_generatorWord`); the collapse is a
CONSEQUENCE of the construction, not a shortcut substituted for it — the coordinate formulas
above are proved for arbitrary kernel elements, not read off the two generators alone.

## Honesty ledger and fences

* No claim is made that `{wrapClass, letterClass}` spans the level-two kernel via a
  constructed `MulEquiv`/`Basis` object (the general "triangular-basis bridge" freeze v2
  leaves OPEN); this file proves the WEAKER, sufficient fact that the coordinate formulas
  `(m, t)` are total and additive on the kernel, which is exactly what a `MonoidHom`
  construction needs and no more.
* This file does not touch NP-8's arena/tower-read/peel-unit/gauge-arena objects
  (grep-fenced below), and states no equality between `canonicalRead` and any
  `Kt`-valued read (design invariant D-TIF-5, held verbatim from `C130cr`).
* `s2CanonicalRead` is NOT packaged into a `SplitNodePointSource`/`S2SourceFrontier`
  instance here (that assembly is FD-0/SG-0, downstream of the residual cores); this node
  supplies exactly the one field, ready for that later assembly.

DEPENDS: `C130cr` (CC-10: `DeepTower.wrapClass`/`wrapClass_coe`, `LaurentNormalizer.letterClass`/
`letterClass_coe`, `levelExponentHeight_ofAdd`) · `C130ln` (CC-4: `laurentNormalizer`,
`laurentSolve`, `laurentNormAt`, exported through `C130cr`) · `C130np6` (`s2AmbientLetter`,
`s2AmbientLetter_coe`) · `C130s17` (`S2DepthTwo`, exported through `C130np6`) · `C130s2`
(`s2DepthTwo`, `s2Frame`, exported through `C130s17`/`C130np6`).

## Status

Zero `sorry`; no new axiom; no `unsafe`; no `True` body; axiom footprint Lean-core only
(AxCheck footer).  No cite.
-/

set_option linter.style.longLine false

namespace Uniformity.Density.Tower.C130np7

open Polynomial IsLocalRing IsDiscreteValuationRing Uniformity.Density
open Uniformity.Density.Leaf Uniformity.Density.Tower
open Uniformity.Density.Tower.C130s2 Uniformity.Density.Tower.C130s6
open Uniformity.Density.Tower.C130s17 Uniformity.Density.Tower.C130np6

universe uL

variable {O : Type} [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]
  [Finite (ResidueField O)] (h2 : Irreducible (2 : O)) (hq : residueCard O = 2)
variable (L : Type uL) [Field L]

/-! ## 1. The exact linear height laws at the S2 numerals -/

section HeightLaws

/-- The level-one Laurent height, at the S2 numerals `e₁ = 2`, `u₁ = 1`, `ê₁ = 2`: the raw
weighted sum collapses to `2p + q` on an `ofAdd` exponent pair (there is no `Φ`-coordinate
at level one, `Fin 0`). -/
theorem s2_levelExponentHeight_one (v : ℤ × ℤ × (Fin 0 → ℤ)) :
    levelExponentHeight (S2DepthTwo h2 hq) 1 (Multiplicative.ofAdd v) =
      Multiplicative.ofAdd (2 * v.1 + v.2.1) := by
  rw [levelExponentHeight_ofAdd]
  congr 1
  have he1 : (s2DepthTwo h2 hq).e 1 = 2 := rfl
  have hu1 : (s2DepthTwo h2 hq).u 1 = 1 := rfl
  have hehat1 : (s2DepthTwo h2 hq).ehat 1 = 2 := rfl
  simp only [he1, hu1, hehat1]
  ring

/-- The level-one kernel law: an `ofAdd` exponent pair is in the level-one kernel iff
`2p + q = 0`. -/
theorem s2_mem_ker_one_iff (v : ℤ × ℤ × (Fin 0 → ℤ)) :
    (Multiplicative.ofAdd v : LevelExponentLattice 1) ∈
        MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) 1) ↔
      2 * v.1 + v.2.1 = 0 := by
  rw [MonoidHom.mem_ker, s2_levelExponentHeight_one, ofAdd_eq_one]

/-- The level-two Laurent height, at the S2 numerals `e = (2,2)`, `u = (1,5)`, `ê = (2,4)`:
the raw weighted sum collapses to `4p + 2q + 5r` on an `ofAdd` exponent triple (`r` reads the
unique `Φ₁`-coordinate, `Fin 1`). -/
theorem s2_levelExponentHeight_two (v : ℤ × ℤ × (Fin 1 → ℤ)) :
    levelExponentHeight (S2DepthTwo h2 hq) 2 (Multiplicative.ofAdd v) =
      Multiplicative.ofAdd (4 * v.1 + 2 * v.2.1 + 5 * v.2.2 0) := by
  rw [levelExponentHeight_ofAdd]
  congr 1
  have he1 : (s2DepthTwo h2 hq).e 1 = 2 := rfl
  have hu1 : (s2DepthTwo h2 hq).u 1 = 1 := rfl
  have hehat2 : (s2DepthTwo h2 hq).ehat 2 = 4 := rfl
  have hu2 : (s2DepthTwo h2 hq).u 2 = 5 := rfl
  rw [Fin.sum_univ_one]
  simp only [Fin.val_zero, he1, hu1, hehat2, hu2]
  ring

/-- The level-two kernel law: an `ofAdd` exponent triple is in the level-two kernel iff
`4p + 2q + 5r = 0`. -/
theorem s2_mem_ker_two_iff (v : ℤ × ℤ × (Fin 1 → ℤ)) :
    (Multiplicative.ofAdd v : LevelExponentLattice 2) ∈
        MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) 2) ↔
      4 * v.1 + 2 * v.2.1 + 5 * v.2.2 0 = 0 := by
  rw [MonoidHom.mem_ker, s2_levelExponentHeight_two, ofAdd_eq_one]

/-- General-element form of the level-two kernel law, read off `Multiplicative.toAdd`
directly (no `ofAdd`-normal-form bookkeeping needed at call sites). -/
theorem s2_mem_ker_two_iff' (g : LevelExponentLattice 2) :
    g ∈ MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) 2) ↔
      4 * (Multiplicative.toAdd g).1 + 2 * (Multiplicative.toAdd g).2.1 +
          5 * (Multiplicative.toAdd g).2.2 0 = 0 := by
  have h := s2_mem_ker_two_iff h2 hq (Multiplicative.toAdd g)
  rwa [ofAdd_toAdd] at h

end HeightLaws

/-! ## 2. The level-one read (wrap generator only, no letters) -/

section LevelOne

/-- **The S2 canonical read at level one**: send a kernel element to `η^{-p}`, where `p` is
its raw `π`-exponent and `η := s2AmbientLetter L 1` is NP-6's residue letter.  Well-defined on
the WHOLE ambient lattice (no kernel-only division), since the level-one coordinate map has
no `Φ`-part to halve. -/
noncomputable def s2CanonicalRead1 :
    MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) 1) →* Lˣ :=
  MonoidHom.mk'
    (fun g => (s2AmbientLetter L 1) ^ (-(Multiplicative.toAdd (g : LevelExponentLattice 1)).1))
    (fun g g' => by
      simp only [MulMemClass.coe_mul, toAdd_mul, Prod.fst_add, neg_add, zpow_add])

/-- Anti-drift pin: the level-one read is the displayed formula, nothing else. -/
theorem s2CanonicalRead1_coe (g : MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) 1)) :
    s2CanonicalRead1 h2 hq L g =
      (s2AmbientLetter L 1) ^ (-(Multiplicative.toAdd (g : LevelExponentLattice 1)).1) := rfl

/-- ★ **Generator regression, level one**: the read of the wrap class is exactly `η`, NP-6's
`s2AmbientLetter L 1`. -/
theorem s2CanonicalRead1_wrapClass (hi : StageLive 2 1) :
    s2CanonicalRead1 h2 hq L ((S2DepthTwo h2 hq).wrapClass hi) = s2AmbientLetter L 1 := by
  have hcoe : ((S2DepthTwo h2 hq).wrapClass hi : LevelExponentLattice 1) =
      Multiplicative.ofAdd ((-1 : ℤ), (2 : ℤ), (0 : Fin 0 → ℤ)) := by
    rw [DeepTower.wrapClass_coe]
    rfl
  rw [s2CanonicalRead1_coe, hcoe, toAdd_ofAdd]
  norm_num

end LevelOne

/-! ## 3. The level-two read (wrap generator and letter) -/

section LevelTwo

/-- The exact `π`- and `Φ₁`-coordinates of the wrap class at level two: `(-1, 2, 0)` (D62w's
`d2g1`, re-derived — the corpus's own regression is an anonymous `example` in `C130cr.lean`,
not a re-usable name). -/
theorem s2_wrapClass_two_coe (hi : StageLive 2 2) :
    ((S2DepthTwo h2 hq).wrapClass hi : LevelExponentLattice 2) =
      Multiplicative.ofAdd ((-1 : ℤ), (2 : ℤ), fun _ : Fin 1 => (0 : ℤ)) := by
  rw [DeepTower.wrapClass_coe]
  rfl

/-- The exact `π`-, `x`-, and `Φ₁`-coordinates of the letter class at level two: `(-2, -1, 2)`
(D62w's `d2g2`).  The Laurent solve is WF-compiled (CC-4's rung recursion), so the proof
unfolds `laurentSolve`'s equation lemmas and closes the resulting finite check by `decide`,
exactly the route `C130cr.lean`'s teeth section records — no bare-`rfl` route exists. -/
theorem s2_letterClass_two_coe (hi : StageLive 2 2) :
    (((S2DepthTwo h2 hq).laurentNormalizer.letterClass hi (0 : Fin (2 - 1))) :
        LevelExponentLattice 2) =
      Multiplicative.ofAdd ((-2 : ℤ), (-1 : ℤ), fun _ : Fin 1 => (2 : ℤ)) := by
  have hsolve : (S2DepthTwo h2 hq).laurentSolve 1 10 = (2, 1, fun _ => 0) := by
    have hu : (S2DepthTwo h2 hq).u (0 + 2) = 5 := rfl
    have he : (S2DepthTwo h2 hq).e (0 + 2) = 2 := rfl
    have hh : (s2Frame h2 hq).h = 1 := rfl
    have he1 : (s2Frame h2 hq).e₁ = 2 := rfl
    simp only [DeepTower.laurentSolve, KeyFrame.slotIdx_eq_towerSolve, hu, he, hh, he1]
    decide
  have hnorm : (S2DepthTwo h2 hq).laurentNormalizer.norm =
      (S2DepthTwo h2 hq).laurentNormAt := rfl
  rw [LaurentNormalizer.letterClass_coe, hnorm]
  norm_num [show (S2DepthTwo h2 hq).e 2 = 2 from rfl,
    show (S2DepthTwo h2 hq).ehat 2 = 4 from rfl, show (S2DepthTwo h2 hq).u 2 = 5 from rfl,
    DeepTower.laurentNormAt, hsolve]
  decide

/-- **The S2 canonical read at level two**: on a kernel element with raw coordinates
`(p, q, r)`, send it to `η^{-(p+r)} · β^{r/2}`, where `η := s2AmbientLetter L 1`,
`β := s2AmbientLetter L 2`.  This is exactly `wrapClass^m · letterClass^t` read through the
generator values, with `m = -(p+r)` and `t = r/2` the (well-defined, since `r` is forced even
by the height law) inverse of the change of basis `(m,t) ↦ m·(-1,2,0) + t·(-2,-1,2) =
(-m-2t, 2m-t, 2t)`. -/
noncomputable def s2CanonicalRead2 :
    MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) 2) →* Lˣ :=
  MonoidHom.mk'
    (fun g =>
      (s2AmbientLetter L 1) ^ (-((Multiplicative.toAdd (g : LevelExponentLattice 2)).1 +
          (Multiplicative.toAdd (g : LevelExponentLattice 2)).2.2 0)) *
        (s2AmbientLetter L 2) ^ ((Multiplicative.toAdd (g : LevelExponentLattice 2)).2.2 0 / 2))
    (fun g g' => by
      have hg := (s2_mem_ker_two_iff' h2 hq (g : LevelExponentLattice 2)).mp g.2
      have hg' := (s2_mem_ker_two_iff' h2 hq (g' : LevelExponentLattice 2)).mp g'.2
      obtain ⟨k, hk⟩ : ∃ k, (Multiplicative.toAdd (g : LevelExponentLattice 2)).2.2 0 = 2 * k :=
        ⟨(Multiplicative.toAdd (g : LevelExponentLattice 2)).2.2 0 / 2, by omega⟩
      obtain ⟨k', hk'⟩ :
          ∃ k', (Multiplicative.toAdd (g' : LevelExponentLattice 2)).2.2 0 = 2 * k' :=
        ⟨(Multiplicative.toAdd (g' : LevelExponentLattice 2)).2.2 0 / 2, by omega⟩
      simp only [MulMemClass.coe_mul, toAdd_mul, Prod.fst_add, Prod.snd_add, Pi.add_apply]
      rw [show (Multiplicative.toAdd (g : LevelExponentLattice 2)).2.2 0 +
          (Multiplicative.toAdd (g' : LevelExponentLattice 2)).2.2 0 = 2 * (k + k') by omega]
      rw [hk, hk']
      have hdiv : ∀ n : ℤ, 2 * n / 2 = n := fun n => by omega
      rw [hdiv, hdiv, hdiv]
      rw [show -((Multiplicative.toAdd (g : LevelExponentLattice 2)).1 +
              (Multiplicative.toAdd (g' : LevelExponentLattice 2)).1 + 2 * (k + k')) =
            (-((Multiplicative.toAdd (g : LevelExponentLattice 2)).1 + 2 * k)) +
              (-((Multiplicative.toAdd (g' : LevelExponentLattice 2)).1 + 2 * k')) by ring]
      rw [zpow_add, zpow_add]
      exact mul_mul_mul_comm _ _ _ _)

/-- Anti-drift pin: the level-two read is the displayed formula, nothing else. -/
theorem s2CanonicalRead2_coe (g : MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) 2)) :
    s2CanonicalRead2 h2 hq L g =
      (s2AmbientLetter L 1) ^ (-((Multiplicative.toAdd (g : LevelExponentLattice 2)).1 +
          (Multiplicative.toAdd (g : LevelExponentLattice 2)).2.2 0)) *
        (s2AmbientLetter L 2) ^
          ((Multiplicative.toAdd (g : LevelExponentLattice 2)).2.2 0 / 2) := rfl

/-- ★ **Generator regression, level two, wrap class**: the read of the wrap class is exactly
`η = s2AmbientLetter L 1` (`m = -(p+r) = -(-1+0) = 1`, `t = r/2 = 0`). -/
theorem s2CanonicalRead2_wrapClass (hi : StageLive 2 2) :
    s2CanonicalRead2 h2 hq L ((S2DepthTwo h2 hq).wrapClass hi) = s2AmbientLetter L 1 := by
  rw [s2CanonicalRead2_coe, s2_wrapClass_two_coe h2 hq hi, toAdd_ofAdd]
  norm_num

/-- ★ **Generator regression, level two, letter class**: the read of the letter class is
exactly `β = s2AmbientLetter L 2` (`m = -(p+r) = -(-2+2) = 0`, `t = r/2 = 2/2 = 1`). -/
theorem s2CanonicalRead2_letterClass (hi : StageLive 2 2) :
    s2CanonicalRead2 h2 hq L
        (((S2DepthTwo h2 hq).laurentNormalizer.letterClass hi (0 : Fin (2 - 1)))) =
      s2AmbientLetter L 2 := by
  rw [s2CanonicalRead2_coe, s2_letterClass_two_coe h2 hq hi, toAdd_ofAdd]
  norm_num

/-- ★ **The distinguished-generator view, level two, assembled**: the read of ANY
distinguished-generator word `wrapClass^m · letterClass^t` is `η^m · β^t` — freeze v2 §4's
display shape, with `η`/`β` now the CONCRETE values `s2AmbientLetter L 1`/`s2AmbientLetter L
2`, both forced to `1` by NP-6.  Mirrors `C130cr.NodePointSource.canonicalRead_generatorWord`
at this concrete read. -/
theorem s2CanonicalRead2_generatorWord (hi : StageLive 2 2) (m : ℤ) (t : Fin (2 - 1) → ℤ) :
    s2CanonicalRead2 h2 hq L
        ((S2DepthTwo h2 hq).laurentNormalizer.generatorWord hi m t) =
      (s2AmbientLetter L 1) ^ m * (s2AmbientLetter L 2) ^ (t 0) := by
  rw [LaurentNormalizer.generatorWord, map_mul, map_zpow]
  rw [s2CanonicalRead2_wrapClass h2 hq L hi]
  have hprod : ∏ a : Fin (2 - 1),
      s2CanonicalRead2 h2 hq L
          ((S2DepthTwo h2 hq).laurentNormalizer.letterClass hi a ^ t a) =
        (s2AmbientLetter L 2) ^ t 0 := by
    rw [Fin.prod_univ_one]
    rw [map_zpow, s2CanonicalRead2_letterClass h2 hq L hi]
  rw [← hprod]
  congr 1
  rw [map_prod]

/-- ★ **Both generic values collapse, at S2**: since NP-6's `s2AmbientLetter` is the
constant unit `1`, the level-two read of every generator word is `1` — a CONSEQUENCE of the
construction above (the coordinate formulas hold for arbitrary kernel elements), not a
substitute for it. -/
theorem s2CanonicalRead2_generatorWord_eq_one (hi : StageLive 2 2) (m : ℤ)
    (t : Fin (2 - 1) → ℤ) :
    s2CanonicalRead2 h2 hq L
        ((S2DepthTwo h2 hq).laurentNormalizer.generatorWord hi m t) = 1 := by
  rw [s2CanonicalRead2_generatorWord h2 hq L hi m t, s2AmbientLetter, s2AmbientLetter]
  simp

end LevelTwo

/-! ## 4. The total S2 canonical read (exact shape of `SplitNodePointSource.canonicalRead`)

The field is total in `i : ℕ`; off the live range `{1, 2}` no law of `SplitNodePointSource`
reads the value (the pattern used everywhere else in this campaign for junk indices, e.g.
`C130np6`'s off-range `s2Letter`), so the trivial hom is an honest placeholder there. -/

section Total

/-- **The S2 canonical L-valued kernel read, exact field shape**: total in `i`, instantiating
`s2CanonicalRead1`/`s2CanonicalRead2` at the two live levels and the trivial hom elsewhere. -/
noncomputable def s2CanonicalRead :
    (i : ℕ) → MonoidHom.ker (levelExponentHeight (S2DepthTwo h2 hq) i) →* Lˣ
  | 1 => s2CanonicalRead1 h2 hq L
  | 2 => s2CanonicalRead2 h2 hq L
  | _ => 1

/-- Anti-drift pin: the total read is `s2CanonicalRead1` at level one. -/
theorem s2CanonicalRead_one : s2CanonicalRead h2 hq L 1 = s2CanonicalRead1 h2 hq L := rfl

/-- Anti-drift pin: the total read is `s2CanonicalRead2` at level two. -/
theorem s2CanonicalRead_two : s2CanonicalRead h2 hq L 2 = s2CanonicalRead2 h2 hq L := rfl

/-- ★ **The generator regressions, assembled at the total read**: `s2CanonicalRead` sends the
wrap class to `s2AmbientLetter L 1` and the letter class to `s2AmbientLetter L 2`, at their
live level — the tie between the constructed read and NP-6's residue letter the plan row
NP-7 asks for. -/
theorem s2CanonicalRead_wrapClass (hi : StageLive 2 1) :
    s2CanonicalRead h2 hq L 1 ((S2DepthTwo h2 hq).wrapClass hi) = s2AmbientLetter L 1 :=
  s2CanonicalRead1_wrapClass h2 hq L hi

theorem s2CanonicalRead_letterClass (hi : StageLive 2 2) :
    s2CanonicalRead h2 hq L 2
        (((S2DepthTwo h2 hq).laurentNormalizer.letterClass hi (0 : Fin (2 - 1)))) =
      s2AmbientLetter L 2 :=
  s2CanonicalRead2_letterClass h2 hq L hi

end Total

/-! ## Fence (grep-tooth)

None of NP-8's separate terminal-field W-leg identifiers appears anywhere in this file, and
no declaration states or implies any agreement between this read and a `Kt`-valued one. -/

end Uniformity.Density.Tower.C130np7

/-! ## Axiom footprint -/

section AxCheck

#print axioms Uniformity.Density.Tower.C130np7.s2_levelExponentHeight_one
#print axioms Uniformity.Density.Tower.C130np7.s2_mem_ker_one_iff
#print axioms Uniformity.Density.Tower.C130np7.s2_levelExponentHeight_two
#print axioms Uniformity.Density.Tower.C130np7.s2_mem_ker_two_iff
#print axioms Uniformity.Density.Tower.C130np7.s2_mem_ker_two_iff'
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead1
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead1_coe
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead1_wrapClass
#print axioms Uniformity.Density.Tower.C130np7.s2_wrapClass_two_coe
#print axioms Uniformity.Density.Tower.C130np7.s2_letterClass_two_coe
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead2
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead2_coe
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead2_wrapClass
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead2_letterClass
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead2_generatorWord
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead2_generatorWord_eq_one
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead_one
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead_two
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead_wrapClass
#print axioms Uniformity.Density.Tower.C130np7.s2CanonicalRead_letterClass

end AxCheck
