import Uniformity.ChapB.B01
import Uniformity.ChapB.B02
import Uniformity.ChapB.B03
import Uniformity.ChapB.B04
import Uniformity.ChapB.B05
import Uniformity.ChapB.B06
import Uniformity.ChapB.B07
import Uniformity.ChapB.B08
import Uniformity.ChapB.B09
import Uniformity.ChapB.B10
import Uniformity.ChapB.B11
import Uniformity.ChapB.B12
import Uniformity.ChapB.B13a
import Uniformity.ChapB.B13b
import Uniformity.ChapB.B14
import Uniformity.ChapB.B15
import Uniformity.ChapB.B16
import Uniformity.ChapB.B17
import Uniformity.ChapB.B18
import Uniformity.ChapB.B19
import Uniformity.ChapB.B20
import Uniformity.ChapB.B21
import Uniformity.ChapB.B22
import Uniformity.ChapB.B23
import Uniformity.ChapB.B24
import Uniformity.ChapB.B25
import Uniformity.ChapB.B26
import Uniformity.ChapB.B27
import Uniformity.ChapB.B28
import Uniformity.ChapB.B29
import Uniformity.ChapB.B30
import Uniformity.ChapB.B31
import Uniformity.ChapB.B32a
import Uniformity.ChapB.B32b
import Uniformity.ChapB.B32c
import Uniformity.ChapB.B33
import Uniformity.ChapB.B34
import Uniformity.ChapB.B35a
import Uniformity.ChapB.B35b
import Uniformity.ChapB.B35c
import Uniformity.ChapB.B35d
import Uniformity.ChapB.B36
import Uniformity.ChapB.B37
import Uniformity.ChapB.B39a
import Uniformity.ChapB.B39b
import Uniformity.ChapB.B40
import Uniformity.ChapB.B41a
import Uniformity.ChapB.B41b
import Uniformity.ChapB.B42
import Uniformity.ChapB.B42a
import Uniformity.ChapB.B44
import Uniformity.ChapB.B45
import Uniformity.ChapB.B46
import Uniformity.ChapB.B47
import Uniformity.ChapB.B48
import Uniformity.ChapB.B49
import Uniformity.ChapB.B50
import Uniformity.ChapB.B51
import Uniformity.ChapB.B52
import Uniformity.ChapB.B53a
import Uniformity.ChapB.B53b
import Uniformity.ChapB.B53c
import Uniformity.ChapB.B54
import Uniformity.ChapB.B55
import Uniformity.ChapB.B56
import Uniformity.ChapB.B57
import Uniformity.ChapB.B58
import Uniformity.ChapB.B59a
import Uniformity.ChapB.B59b
import Uniformity.ChapB.B60
import Uniformity.ChapB.B61
import Uniformity.ChapB.B63
import Uniformity.ChapB.B63a
import Uniformity.ChapB.B64
import Uniformity.ChapB.B65
import Uniformity.ChapB.B66
import Uniformity.ChapB.B66a
import Uniformity.ChapB.B66c
import Uniformity.ChapB.B67
import Uniformity.ChapB.B68
import Uniformity.ChapB.B69
import Uniformity.ChapB.B70
import Uniformity.ChapB.B71
import Uniformity.ChapB.B72
import Uniformity.ChapB.B73
import Uniformity.ChapB.B74
import Uniformity.ChapB.B75
import Uniformity.ChapB.B76
import Uniformity.ChapB.B77a
import Uniformity.ChapB.B77b
import Uniformity.ChapB.B78
import Uniformity.ChapB.B79a
import Uniformity.ChapB.B79b
import Uniformity.ChapB.B80
import Uniformity.ChapB.B81
import Uniformity.ChapB.B82
import Uniformity.ChapB.B83Kit
import Uniformity.ChapB.B83a
import Uniformity.ChapB.B83b
import Uniformity.ChapB.B83c
import Uniformity.ChapB.B83d
import Uniformity.ChapB.B84a
import Uniformity.ChapB.B84b
import Uniformity.ChapB.B84c
import Uniformity.ChapB.B84d
import Uniformity.ChapB.B85a
import Uniformity.ChapB.B85b
import Uniformity.ChapB.BBox1CiteStatement

/-! ChapB roll-up — regenerated at §10 close (B.83–B.86), 2026-08-16.

Every chapter-B module, including §8/§9's certificate layer (B.79a/b, B.80, B.81, B.82), the
§10 gate instances (B.83a–d, B.84a–d, B.85a/b) and their booked shared evaluation kit
(`B83Kit`). `B.86` (the census block) imports this file and nothing else. -/
