/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib
import LeanUrat.Moves.Defs
import LeanUrat.Moves.DefsT
import LeanUrat.Moves.DefsCore

/-!
# Moves/DefsL — the round-5 (FINAL) localization objects for the MOVES tower induction (§B2-DEF)

**Provenance.** `lean/notes/MOVES_2026-07-24.md` §B2-DEF (D.0–D.11). ROUND-5 design layer,
answering the four demands of audit #4 (`lean/notes/MOVES_LEAN_SEMAUDIT4_2026-07-26.md`).
Imports `Defs.lean`/`DefsT.lean`/`DefsCore.lean` UNCHANGED. Design rationale and the per-demand
(a)/(b) record: blueprint `MOVES_LEAN_BLUEPRINT_2026-07-26.md` § ROUND 5. Definitions plus two
two-line lemmas (`locT` unit equations, `grRes_mul_T_neg` — the definitional normalization);
no `sorry`, no axioms.

## The round-5 design: the graded localization, built concretely as `L = L₀[T^{±1}]`

D.1(e) — proved once in the accepted §B2-DEF — says the localization `L = 𝒢[⟨U ∪ {Y}⟩⁻¹]` of a
stage with degree-1 unit `T` is CANONICALLY `L₀[T^{±1}]`, via `x ↦ R(x)·T^{deg x}` on homogeneous
elements. Under the standing round-1 codomain fiat (`L₀ := LaurentPolynomial ↥σ.K` — the D2 flag,
carried unchanged), that canonical presentation is a CONCRETE ring:

  `LTwo ↥σ.K := LaurentPolynomial (LaurentPolynomial ↥σ.K)`   (inner variable `z`, outer `T`),

and the initial-form map is `Stage.grRes f := C (σ.R f) · T (σ.w f)` — so `T` (the outer
variable, the unit `locT`) IS an actual localized element, and the normalization
`R(f) = [f]·T^{−w(f)}` holds definitionally (`grRes_mul_T_neg`). The StageCore tie laws
(`w_strict`/`w_jump`/`R_neg`, round 4) make `grRes` injective on graded classes, so identities
of `grRes`-images are equivalent to identities of genuine initial forms in any genuine model:
the constructions below state the D.0(P2)/D.2(S4)/D.7(vi)/D.8 laws about ACTUAL objects.

* **Demand 1 (T-vector → actual localized normalizing unit): `TvecUnitLaw`** — the product
  identity `Π in(ũᵢ)^{aᵢ} · Y^t = T` as an equation between UNITS of `LTwo`, factors pinned to
  `grRes` of the literal `σ.Tvec` entries (whose support IS `σ.reps`, by `Stage.hTvec`) and the
  key; exponents the literal vector entries. Replaces the two-evaluation shadow `TvecLaw`
  (propositionally equivalent under the Stage laws — but now stated at the locus D.0(P2)
  specifies, with `T` present as the element the law is about).
* **Demand 2 (S4 = the coefficient LOCALIZATION): `Stage.coeffLocSR` + `CoeffLocLaw`** — the
  coefficient localization `𝒞[⟨U⟩⁻¹]` as a genuine `Subring (LTwo ↥σ.K)` (generated by the
  coefficient initial forms and the INVERSES of the representative units), with (S4) stated of
  it: degree-0 part = `K` exactly (both inclusions), plus the (P1) pinning — `z` realized
  EXACTLY (scalar 1) as a degree-0 formal `U ∪ {Y}`-monomial vector (`IsLVecVal`, exponent
  vectors over the genuine representative list). Rank-1-ness of the exponent group is no longer
  imposed by the codomain alone: graded injectivity (tie laws) transfers it to any genuine model.
* **Demand 3 (D.8 transport on Laurent slot terms + terminal carry): `IsCarryChainL` /
  `CarryTransportL` / `LandingCylinderL`** — the triangular recursion as a RELATIONAL chain on
  LAURENT slot terms `c_j = T(j·m̂ − a)·R(B_j)` (no polynomial coercion: negative `z`-powers may
  cancel only across ψ-levels, exactly as D.8 displays), digits the canonical `deg < g`
  representatives, carries Laurent, and the terminal no-overflow `carry j = 0` for `j ≥ N`
  RECORDED as a clause. The chain's witness is unique (deterministic both ways on actual loci —
  the D.8 triangular bijection); the executable `carryRec` of round 4 is retired from the
  cylinder.
* **Demand 4 (P6i scalar action preserves the piece)** — no new object: the corrected `L2.P6i`
  statement (MANIFEST_FINAL) hypothesizes `σ.w û = 0` and concludes `σ.w (û·f) = γ` with the
  scaling — an endomorphism of the fixed graded piece.
* **`StageCoreL` / `TransitionCoreL`** — the round-4 cores extended by the new laws; the
  transition record `child_dig_frame` now carries the frame-unit exponent as a function of the
  PARENT WEIGHT alone (`∃ mfun : ℤ → ℤ` BEFORE `∀ B`) — the per-index coherence `TRANSviii_a`'s
  `∃ m, ∀ c` needs (audit #4's uniform-orbit demand).

All items are flagged for semantic-guardian review (the trust boundary). The single remaining
boundary — the identification of `(σ.R, σ.w)` with the residual calculus of a genuine graded
tower (the round-1 D2 fiat + D.1(e)) — is restated, unchanged, in blueprint § ROUND 5 with the
full spec of the graded-ring campaign that would discharge it.
-/

set_option linter.style.longLine false
set_option linter.style.header false
set_option linter.unusedSectionVars false

namespace LeanUrat.Moves

open Polynomial

/-! ## 1. The concrete graded localization `L = L₀[T^{±1}]` and its distinguished units -/

/-- The concrete presentation of the stage localization `L = 𝒢[⟨U ∪ {Y}⟩⁻¹]` given by D.1(e):
`L ≅ L₀[T^{±1}]` with `L₀` the (fiat) Laurent codomain. Inner variable = `z`, outer = `T`. -/
abbrev LTwo (K : Type*) [Field K] : Type _ := LaurentPolynomial (LaurentPolynomial K)

/-- The Laurent variable `T n` as a unit (inverse `T (−n)`), in any Laurent ring. -/
noncomputable def tUnit (R : Type*) [CommRing R] (n : ℤ) : (LaurentPolynomial R)ˣ :=
  ⟨LaurentPolynomial.T n, LaurentPolynomial.T (-n),
    by rw [← LaurentPolynomial.T_add, add_neg_cancel, LaurentPolynomial.T_zero],
    by rw [← LaurentPolynomial.T_add, neg_add_cancel, LaurentPolynomial.T_zero]⟩

/-- **The normalizing unit `T`** — the degree-1 unit of `L = L₀[T^{±1}]`, as an ACTUAL unit of
the actual ring (the element D.0's `T` and (P2)'s product law are about). -/
noncomputable def locT (K : Type*) [Field K] : (LTwo K)ˣ := tUnit (LaurentPolynomial K) 1

section
variable {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]

/-- **The initial form `[f]` in the concrete localization**: `grRes f = C (R f) · T (w f)` —
the image of `[f] ∈ gr_w(A)` under D.1(e)'s isomorphism `L ≅ L₀[T^{±1}]` (`f = 0 ↦ 0`). -/
noncomputable def Stage.grRes (σ : Stage p F) (f : Polynomial ℤ_[p]) : LTwo ↥σ.K :=
  LaurentPolynomial.C (σ.R f) * LaurentPolynomial.T (σ.w f)

/-- `T` genuinely normalizes: `R(f) = [f]·T^{−w(f)}`, definitionally in the concrete model. -/
lemma Stage.grRes_mul_T_neg (σ : Stage p F) (f : Polynomial ℤ_[p]) :
    σ.grRes f * LaurentPolynomial.T (- σ.w f) = LaurentPolynomial.C (σ.R f) := by
  rw [Stage.grRes, mul_assoc, ← LaurentPolynomial.T_add, add_neg_cancel,
    LaurentPolynomial.T_zero, mul_one]

/-- `u` is a unit of `L` whose value is the initial form of `f` (pins units by value — unit
inverses are unique, so no choice is needed anywhere downstream). -/
def IsGrUnit (σ : Stage p F) (f : Polynomial ℤ_[p]) (u : (LTwo ↥σ.K)ˣ) : Prop :=
  (u : LTwo ↥σ.K) = σ.grRes f

/-! ## 2. Demand 1 — the T-vector product law at the actual unit (D.0 (P2), D.3(b), D.7(vi)-(vii)) -/

/-- **The T-vector product law, at its genuine locus**: `Π in(ũᵢ)^{aᵢ} · Y^t = T` as an identity
of UNITS of the concrete localization `L = L₀[T^{±1}]` — each factor the initial form of the
literal `σ.Tvec` entry (support = `σ.reps` by `Stage.hTvec`), `Y = in(Φ)`, exponents the literal
vector entries and the Bézout `σ.t`, right side the actual normalizing unit `locT`. Requiring
the factors to BE units is part of the law (initial forms of representatives are invertible in
`L` — genuine (S4)/D.7(iv) content, supplied by `hS5`-monomiality in genuine models). Replaces
`TvecLaw` (the audit-#4 two-evaluation shadow) as the tower's T-provenance. -/
def TvecUnitLaw (σ : Stage p F) : Prop :=
  ∃ (uY : (LTwo ↥σ.K)ˣ) (ru : Fin σ.Tvec.length → (LTwo ↥σ.K)ˣ),
    IsGrUnit σ σ.Φ uY ∧
    (∀ i, IsGrUnit σ (σ.Tvec.get i).1 (ru i)) ∧
    (∏ i, ru i ^ (σ.Tvec.get i).2) * uY ^ σ.t = locT ↥σ.K

/-! ## 3. Demand 2 — the coefficient localization as a genuine subring, and (S4) about it -/

/-- The formal `U ∪ {Y}`-monomial exponent vectors: an integer exponent per representative
(over the genuine list `σ.reps`) plus a key exponent — the free lattice of monomial directions
BEFORE any flattening (the object whose rank the exponent-group clause is about). -/
def LVec {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F] (σ : Stage p F) : Type _ :=
  (Fin σ.reps.length → ℤ) × ℤ

/-- The weight (degree in `L`) of a formal monomial vector — computed from the genuine stage
weights of the representative elements and the key weight `h`, NOT through `R`. -/
def Stage.lvecWeight (σ : Stage p F) (v : LVec σ) : ℤ :=
  (∑ i, v.1 i * σ.w (σ.reps.get i)) + v.2 * (σ.h : ℤ)

/-- `u` is the value in `L` of the formal monomial vector `v`: the product of the representative
initial-form units to the vector's exponents times the key unit to the key exponent. -/
def IsLVecVal (σ : Stage p F) (v : LVec σ) (u : (LTwo ↥σ.K)ˣ) : Prop :=
  ∃ (ru : Fin σ.reps.length → (LTwo ↥σ.K)ˣ) (uY : (LTwo ↥σ.K)ˣ),
    (∀ i, IsGrUnit σ (σ.reps.get i) (ru i)) ∧ IsGrUnit σ σ.Φ uY ∧
    u = (∏ i, ru i ^ v.1 i) * uY ^ v.2

/-- **The coefficient localization `L^coeff = 𝒞[⟨U⟩⁻¹]`, as an actual subring of `L`**: generated
by the initial forms of the nonzero coefficients (the coefficient subring `𝒞` of `gr_w(A)`) and
the INVERSES of the representative units (localization at `⟨U⟩`; no `Y`, per D.0/(S4)). -/
noncomputable def Stage.coeffLocSR (σ : Stage p F) : Subring (LTwo ↥σ.K) :=
  Subring.closure
    ({x | ∃ B, B ≠ 0 ∧ inC σ.Φ B ∧ x = σ.grRes B} ∪
     {x | ∃ (i : Fin σ.reps.length) (u : (LTwo ↥σ.K)ˣ),
        IsGrUnit σ (σ.reps.get i) u ∧ x = ((u⁻¹ : (LTwo ↥σ.K)ˣ) : LTwo ↥σ.K)})

/-- **(S4), stated of the actual localization** (D.2 (S4), D.7(v)-(vi)):
* **(L^coeff)₀ ⊆ K** — every DEGREE-0 element of the coefficient localization subring (an outer
  constant `C ℓ`; degree-0 elements of `L₀[T^{±1}]` are exactly these) is a `K`-constant. This
  quantifies over the localization's every degree-0 element — sums, products, and fractions
  included — not over pairs of flattened outputs;
* **(L^coeff)₀ ⊇ K** — every `K`-constant lies in the subring;
* **(P1) the `z`-pinning** — `z` is EXACTLY (scalar 1) the value of a degree-0 formal
  `U ∪ {Y}`-monomial vector: the genuine `z = V^{−h}·Y^{e}` of D.2/D.7(vi). Its class generates
  the degree-0 exponent group: positions of monomial values are forced, `z` has position 1, and
  graded injectivity (StageCore tie laws) transfers rank-1-ness to genuine models — the audit-#4
  "erased exponent direction" is excluded by injectivity on cleared-denominator pairs, not by
  the codomain. -/
def CoeffLocLaw (σ : Stage p F) : Prop :=
  (∀ ℓ : LaurentPolynomial ↥σ.K, LaurentPolynomial.C ℓ ∈ σ.coeffLocSR →
      ∃ d : ↥σ.K, ℓ = LaurentPolynomial.C d)
  ∧ (∀ d : ↥σ.K, LaurentPolynomial.C (LaurentPolynomial.C d) ∈ σ.coeffLocSR)
  ∧ (∃ (zv : LVec σ) (u : (LTwo ↥σ.K)ˣ),
      σ.lvecWeight zv = 0 ∧ IsLVecVal σ zv u ∧
      (u : LTwo ↥σ.K) = LaurentPolynomial.C (zvar ↥σ.K))

/-! ## 4. The round-5 stage core and transition core -/

/-- **The stage core, round 5** — round 4's `StageCore` (parent-valuation laws, genuine reps,
tie laws, `prevIaug`, `SlotDecomp`, `CoeffFieldLawCore`) EXTENDED by the two demand-repairs:
the T-vector product law at the actual normalizing unit (demand 1), and (S4) stated of the
actual coefficient localization subring (demand 2). Constructed by the base, transported by
both transitions, consumed by every unit needing tower provenance. -/
structure StageCoreL (σ : Stage p F) : Prop where
  core : StageCore σ
  tvec_unit : TvecUnitLaw σ
  coeff_loc : CoeffLocLaw σ

/-- **The transition core, round 5** — `TransitionData` + the factorwise T-vector transport
(D.7(vi)-(vii), as round 4) + the cross-stage residual record with the frame-unit exponent a
FUNCTION OF THE PARENT WEIGHT ALONE (`mfun` quantified BEFORE the elements): the child digit
scalar of `B ∈ Ĉ` is `dig'(B)·z̄^{mfun (σ.w B)}` at the forced position `−t'·σ.w B`. This is the
per-index coherence audit #4 demanded for `TRANSviii_a`'s `∃ m, ∀ c` — realizers of one index
`(γ, j)` share the parent weight `γ + j·h`, hence the frame unit; the orbit scalar enters
linearly through `dig'`. (It implies round 4's per-element `child_dig`.) -/
structure TransitionCoreL (σ σ' : Stage p F) (Φhat : Polynomial ℤ_[p]) (e' h' : ℕ)
    (zbar : Fˣ) : Prop where
  base : TransitionData σ σ' Φhat e' h' zbar
  child_Tvec : σ'.Tvec
      = σ.Tvec.map (fun q => (q.1, σ'.s * q.2)) ++ [(σ.Φ, σ'.s * σ.t)]
  child_dig_frame : ∃ mfun : ℤ → ℤ, ∀ B, B ≠ 0 → inC Φhat B →
      ∃ c' : (↥σ'.K)ˣ,
        σ'.R B = LaurentPolynomial.C (c' : ↥σ'.K) * LaurentPolynomial.T (- σ'.t * σ.w B) ∧
        ((c' : ↥σ'.K) : F) = σ.digPrime zbar B * ((zbar ^ (mfun (σ.w B)) : Fˣ) : F)

end

/-! ## 5. Demand 3 — the D.8 carry transport on LAURENT slot terms, terminal carry recorded -/

/-- **The D.8 triangular carry chain, on Laurent slot terms** (MOVES ~2339-2358): `carry 0 = 0`;
at every level `j` the incoming slot term plus carry splits as the canonical digit (a POLYNOMIAL
of degree `< deg ψ` — the representative system `{deg < g}`) plus `ψ` times the outgoing carry.
Slot terms and carries are LAURENT (negative `z`-powers may cancel across ψ-levels — the
audit-#4 locus); digits are canonical. The witness `(Cdig, carry)` is unique given `c` (digit =
the unique `deg < g` representative of the class mod `ψ` in `F[z^{±1}]`, `z` invertible mod `ψ`
for `ψ ≠ z`; carry = the exact quotient) — the chain IS the displayed deterministic recursion,
in both directions on actual loci. -/
def IsCarryChainL {K : Type*} [Field K] (ψ : Polynomial K) (c : ℕ → LaurentPolynomial K)
    (Cdig : ℕ → Polynomial K) (carry : ℕ → LaurentPolynomial K) : Prop :=
  carry 0 = 0 ∧
  ∀ j, (Cdig j).degree < ψ.degree ∧
    c j + carry j = Polynomial.toLaurent (Cdig j) + Polynomial.toLaurent ψ * carry (j + 1)

/-- **The transported pattern with terminal no-overflow**: some carry sequence realizes the
chain from the slot terms `c` to the digits `Cdig`, and every carry from level `N` on VANISHES
— the recorded terminal condition (audit #4: without it, `N` digits can agree while an
unrecorded `ψ^N` overflow remains, breaking the reverse implication). With `c` vanishing from
`N` on, the terminal clause forces `Cdig j = 0` for `j ≥ N`: the development is EXACT. -/
def CarryTransportL {K : Type*} [Field K] (ψ : Polynomial K) (c : ℕ → LaurentPolynomial K)
    (Cdig : ℕ → Polynomial K) (N : ℕ) : Prop :=
  ∃ carry : ℕ → LaurentPolynomial K,
    IsCarryChainL ψ c Cdig carry ∧ ∀ j, N ≤ j → carry j = 0

section
variable {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]

/-- **The landing cylinder, round 5** (D.8 (BOX)/(VERTEX)/(TRANSPORT)): as round 4's
`LandingCylinder` — side line `m₀` attained at the vertex `μ` (VERTEX), every slot `j < μ`
strictly above (BOX) — but the anchored minimizing-slot terms are now the LAURENT elements
`c_j := T(j·m̂ − a)·R(B_j)` themselves (`m̂ = −t·h·g`; zero at non-minimizing slots and beyond
`N`), and the stratum's pattern `Cdig` is reproduced through `CarryTransportL`: the relational
triangular chain WITH the terminal no-overflow clause. No polynomial coercion of individual
slot terms (the audit-#4 FAITHLESS locus), and the `j = μ` instance carries the explicit vertex
unit `T(μ·m̂ − a)` — D.8's `z̄^{−μm̂}` normalization. -/
def LandingCylinderL (σ : Stage p F) (ψ : Polynomial ↥σ.K) (g : ℕ) (μ : ℕ) (a : ℤ)
    (Cdig : ℕ → Polynomial ↥σ.K) (B : ℕ → Polynomial ℤ_[p]) (N : ℕ) : Prop :=
  ∃ m₀ : ℤ,
    B μ ≠ 0 ∧ σ.w (B μ) + (μ : ℤ) * ((σ.e : ℤ) * σ.h * g) = m₀ ∧
    (∀ j, j < N → B j ≠ 0 → m₀ ≤ σ.w (B j) + (j : ℤ) * ((σ.e : ℤ) * σ.h * g)) ∧
    (∀ j, j < μ → B j ≠ 0 → m₀ < σ.w (B j) + (j : ℤ) * ((σ.e : ℤ) * σ.h * g)) ∧
    ∃ cL : ℕ → LaurentPolynomial ↥σ.K,
      (∀ j, j < N →
        ((B j ≠ 0 ∧ σ.w (B j) + (j : ℤ) * ((σ.e : ℤ) * σ.h * g) = m₀) →
          cL j = LaurentPolynomial.T ((j : ℤ) * (- σ.t * σ.h * g) - a) * σ.R (B j)) ∧
        (¬ (B j ≠ 0 ∧ σ.w (B j) + (j : ℤ) * ((σ.e : ℤ) * σ.h * g) = m₀) → cL j = 0)) ∧
      (∀ j, N ≤ j → cL j = 0) ∧
      CarryTransportL ψ cL Cdig N

end

end LeanUrat.Moves
