/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib
import LeanUrat.Moves.Defs

/-!
# Moves/DefsT — tower/transition extensions for the MOVES induction (§B2-DEF)  [ROUND 3]

**Provenance.** `lean/notes/MOVES_2026-07-24.md` §B2-DEF (D.0–D.11).  This file is the ROUND-3
redesign layer that repairs the round-2 semantic-faithfulness audit
`lean/notes/MOVES_LEAN_SEMAUDIT2_2026-07-26.md` (29 FAITHLESS + 5 structural leftovers).  It
imports `Defs.lean` UNCHANGED (the concurrent fan-out reads `Defs.lean`/`MANIFEST.json`; this file
and `MANIFEST_R3.json` carry all round-3 material).  Contains ONLY definitions/structures — no
theorems, no `sorry`, no axioms.  Design rationale: blueprint `MOVES_LEAN_BLUEPRINT_2026-07-26.md`
§ ROUND 3.

## What the audit demanded, and where it lives here

* **S3 genuine slot decomposition** (DEF-1): `SlotDecomp` — degreewise DECOMPOSITION *and*
  INDEPENDENCE (Y-transcendence: a vanishing Y-combination inside ONE graded piece is termwise
  zero), not the residual-additivity substitute the audit rejected.
* **S4 coefficient field** (DEF-2 half): `CoeffFieldLaw` — the degree-0 coefficient field connected
  to `K` by a surjectivity law, the fixed-position (fixed-`Y`) `K`-line clause, and the exponent
  group `= ℤ` clause.
* **Anti-pathology / history / T-vector residual consequences** (DEF-3 + fresh findings):
  `StageWF` — `wPrev` is a valuation, `reps` is nonempty and contains `p` with CANONICAL
  (scalar-1) monomial residuals (the residual consequence of `T = Π in(ũ)^a`), and `K` is generated
  by the digit scalars (the localization theorem connecting `K` to `R`).
* **Transition laws, CONSTRUCTED** (DEF-8 + G5): `TransitionData` — the child stage's parent
  valuation IS the parent's `w` (`child_wPrev`), the DEF-8 threshold law `σ'.wPrev Φ̂ = σ.w Φ̂`,
  the slot-minimum weight, genuine residue growth, and representative growth by the outgoing key.
* **Recentering substitution law** (DEF-10): `RecenterSubstLaw`/`IsRecenteringT` — the
  common-localization identity `z' = z − c̃` at the EVALUATION level, SCOPED to read-height
  coefficient data (the audit rejected arbitrary-`f` quantification).
* **Unitriangular digit count** (P6ii): `DigitSystem`/`IsSolution` — a `k`-equation unitriangular
  system whose solution set has the nominal `|α|^{n−k}` count.

All items are flagged for semantic-guardian review (the trust boundary).
-/

set_option linter.style.longLine false
set_option linter.style.header false
set_option linter.unusedSectionVars false

namespace LeanUrat.Moves

open Polynomial

section
variable {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]

/-! ## 1. S3 — the genuine slot decomposition (DEF-1) -/

/-- **(S3) genuine slot decomposition** (D.2 (S3), D.3): the two facts the accepted proof
transports, phrased so a pathological `R` cannot satisfy them.

* **DECOMPOSITION** (within a graded piece): for a development whose nonzero slots all have equal
  total weight `γ` and whose sum stays at weight `γ`, `R` is additive across the slots (the old
  round-2 `L2.slotDecomp`).
* **INDEPENDENCE / `Y`-transcendence** (the half the audit demanded and round-2 lacked): a
  `Y`-combination `Σ_j R(B_j)·(R Φ)^j` all of whose nonzero coefficient slots live in ONE graded
  piece `γ` (so their `z`-positions are DISTINCT by the stride/anchor-congruence) vanishes only
  termwise — i.e. `Y = [Φ]` is transcendental over the coefficient classes, degreewise. -/
def SlotDecomp (σ : Stage p F) : Prop :=
  (∀ (B : ℕ → Polynomial ℤ_[p]) (N : ℕ) (γ : ℤ),
      (∀ j, N ≤ j → B j = 0) →
      (∀ j, j < N → B j ≠ 0 → σ.w (B j * σ.Φ ^ j) = γ) →
      (∑ j ∈ Finset.range N, B j * σ.Φ ^ j) ≠ 0 →
      σ.w (∑ j ∈ Finset.range N, B j * σ.Φ ^ j) = γ →
      σ.R (∑ j ∈ Finset.range N, B j * σ.Φ ^ j)
        = ∑ j ∈ Finset.range N, σ.R (B j * σ.Φ ^ j))
  ∧
  (∀ (B : ℕ → Polynomial ℤ_[p]) (N : ℕ) (γ : ℤ),
      (∀ j, j < N → B j ≠ 0 → inC σ.Φ (B j) ∧ σ.w (B j) + (j : ℤ) * σ.w σ.Φ = γ) →
      (∑ j ∈ Finset.range N, σ.R (B j) * (σ.R σ.Φ) ^ j) = 0 →
      ∀ j, j < N → B j = 0)

/-! ## 2. S4 — the coefficient-localization degree-0 field (DEF-2, S4 half) -/

/-- **(S4) coefficient field law** (D.2 (S4), D.7(vi)): the three clauses the audit named.

* **degree-0 field = `K`** (the "theorem-shaped law connecting `K` to the residual data"): every
  unit of the current field `K` is realized as a coefficient digit scalar at some parent weight
  and its forced position `−t·ν`.  Together with `hS5` (scalars land IN `Kˣ`) this pins the
  degree-0 coefficient field to `K` exactly.
* **fixed-`Y` (fixed-position) lines are `K`-lines**: two coefficient residuals sharing a
  `z`-position differ by a `K`-scalar.
* **exponent group `= ℤ`** (generated by `z = T 1`): the positions of all monomial residuals
  generate `ℤ`. -/
def CoeffFieldLaw (σ : Stage p F) : Prop :=
  (∀ c : (↥σ.K)ˣ, ∃ (B : Polynomial ℤ_[p]) (ν : ℤ),
      B ≠ 0 ∧ inC σ.Φ B ∧ σ.wPrev B = ν ∧
        σ.R B = LaurentPolynomial.C (c : ↥σ.K) * LaurentPolynomial.T (- σ.t * ν))
  ∧
  (∀ (B B' : Polynomial ℤ_[p]) (c c' : ↥σ.K) (k : ℤ),
      σ.R B = LaurentPolynomial.C c * LaurentPolynomial.T k →
      σ.R B' = LaurentPolynomial.C c' * LaurentPolynomial.T k →
      c ≠ 0 → ∃ d : ↥σ.K, σ.R B' = LaurentPolynomial.C d * σ.R B)
  ∧
  (AddSubgroup.closure
      {k : ℤ | ∃ (B : Polynomial ℤ_[p]) (c : ↥σ.K),
          B ≠ 0 ∧ σ.R B = LaurentPolynomial.C c * LaurentPolynomial.T k} = ⊤)

/-! ## 3. Stage well-formedness — anti-pathology, history, T-vector residual laws (DEF-3 + fresh) -/

/-- **Stage well-formedness** — the laws that stop the audit's *pathological-stage vacuity*
(fresh structural findings): a `Stage` satisfying its round-2 axioms can still describe an abstract
residual calculus with no tower behind it.  `StageWF σ` forbids that, using only residual-level
consequences (the graded ring stays unbuilt, per §B2-DEF's structural decision — blueprint gap G1
persists for the raw exponent vector, but its CONSUMABLE residual consequences are now laws).

* `wPrev_mul`/`wPrev_ult` — the parent valuation IS a valuation (the audit: "`wPrev` is
  unconstrained outside the coefficient space and is not asserted to be a valuation").
* `reps_nonempty`/`p_is_rep` — the representative list is genuine: nonempty and containing `p`
  (the audit: "`reps` may be empty, need not contain `p`").
* `reps_pinned` — the **T-vector product identity's residual consequence**: each representative is a
  CANONICAL (scalar-1) monomial residual `z^{−t·wPrev(ũ)}` (the pinned coefficient unit `V` whose
  digit is 1); this ties `R` to the representatives so `R` is not "an abstract Laurent-valued
  operation".
* `K_gen` — the **localization theorem connecting `K` to `R`** (the audit: "`K` is declared … without
  any localization theorem connecting it to `R`"): `K` is generated by the digit scalars. -/
structure StageWF (σ : Stage p F) : Prop where
  wPrev_mul : ∀ f g, f ≠ 0 → g ≠ 0 → σ.wPrev (f * g) = σ.wPrev f + σ.wPrev g
  wPrev_ult : ∀ f g, f ≠ 0 → g ≠ 0 → f + g ≠ 0 → min (σ.wPrev f) (σ.wPrev g) ≤ σ.wPrev (f + g)
  reps_nonempty : σ.reps ≠ []
  p_is_rep : (Polynomial.C (p : ℤ_[p])) ∈ σ.reps
  reps_pinned : ∀ ũ ∈ σ.reps, σ.R ũ = LaurentPolynomial.T (- σ.t * σ.wPrev ũ)
  K_gen : σ.K = Subfield.closure
      { x : F | ∃ (B : Polynomial ℤ_[p]) (c : ↥σ.K) (k : ℤ),
          B ≠ 0 ∧ inC σ.Φ B ∧ σ.R B = LaurentPolynomial.C c * LaurentPolynomial.T k ∧ x = (c : F) }

/-! ## 4. The transition — the child stage's laws, CONSTRUCTED (DEF-8 + G5) -/

/-- **Transition data** (D.7 Proposition TRANS): the parent→child laws, to be CONSTRUCTED by
`TRANSstage` (the audit: "`TRANSstage` constructing (not assuming) the next stage's laws").
Bundling these as a `Prop` about `(σ, σ')` means `TRANSstage`'s conclusion produces the genuine
tower step rather than extracting from an already-complete target.

* `child_wPrev` — the **history invariant**: the child's parent valuation IS the parent's `w` (the
  audit: "no history invariant saying that the current `wPrev` … came from the preceding stage").
* `threshold` — the **DEF-8 threshold law** `σ'.wPrev Φ̂ = σ.w Φ̂`, consumed by `TRANSviii_b`.
* `child_field`/`field_grow` — genuine residue growth `σ'.K = K⟮z̄⟯ ⊇ K`.
* `child_reps` — representatives grow by the outgoing key `Φ` (D.7(iv)). -/
structure TransitionData (σ σ' : Stage p F) (Φhat : Polynomial ℤ_[p]) (e' h' : ℕ)
    (zbar : Fˣ) : Prop where
  child_key   : σ'.Φ = Φhat
  child_e     : σ'.e = e'
  child_h     : σ'.h = h'
  child_field : σ'.K = σ.nextField zbar
  field_grow  : σ.K ≤ σ'.K
  child_base  : σ'.FQ = σ.FQ
  child_wPrev : ∀ f, σ'.wPrev f = σ.w f
  threshold   : σ'.wPrev Φhat = σ.w Φhat
  child_slotmin : IsSlotMinWeight σ'.w Φhat e' h' σ.w
  child_reps  : σ'.reps = σ.reps ++ [σ.Φ]

/-! ## 5. The recentering substitution law — common localization, scoped (DEF-10 + G7) -/

/-- **The D.10 substitution identity at the evaluation level** (`z' = z − c̃`), SCOPED to the
read-height coefficient space (the audit rejected arbitrary-`f` quantification in
`recLiftIndep`/`recSubst`; D.10's own scope clause restricts it to coefficient/read-height data).
For a coefficient `B ∈ C_Φ`, evaluating the primed digit at `z̄'` equals the parent digit at
`z̄ = z̄' + c̃`. -/
def RecenterSubstLaw (σ σ' : Stage p F) (cc : ↥σ.K) : Prop :=
  ∀ (B : Polynomial ℤ_[p]), B ≠ 0 → inC σ.Φ B →
    ∀ (zbar zbar' : Fˣ), (zbar : F) = (zbar' : F) + ((cc : ↥σ.K) : F) →
      σ'.digPrime zbar' B = σ.digPrime zbar B

/-- **The recentering, with its substitution law** (D.10): the round-2 `IsRecentering`
field-by-field construction, AUGMENTED by the common-localization substitution `RecenterSubstLaw`
(round-2 `IsRecentering` only related digits at the SAME `z̄`; the change-of-transcendental
`z' = z − c̃` was missing). -/
def IsRecenteringT (σ σ' : Stage p F) (cc : ↥σ.K) (tt : Polynomial ℤ_[p]) : Prop :=
  IsRecentering σ σ' cc tt ∧ RecenterSubstLaw σ σ' cc

end

/-! ## 6. Unitriangular digit systems (P6ii, the ledger) -/

/-- **A unitriangular digit system** (D.3(e)(ii), D.11): `n` digit coordinates over an alphabet
`α`, of which a subset are PINNED; each pinned coordinate is a function `solve` of the STRICTLY
EARLIER coordinates (the accumulated affine carries are the unitriangular part).  This is the
structure the audit demanded in place of "cardinality invariance under an arbitrary equivalence". -/
structure DigitSystem (n : ℕ) (α : Type*) where
  /-- which of the `n` coordinates are pinned by an equation -/
  pinned : Fin n → Bool
  /-- a pinned coordinate's value, as a function of the strictly-earlier coordinates -/
  solve : (i : Fin n) → ((j : Fin n) → j < i → α) → α

/-- `x` solves the digit system: each pinned coordinate equals its `solve`-value on the earlier
coordinates. -/
def DigitSystem.IsSolution {n : ℕ} {α : Type*} (D : DigitSystem n α) (x : Fin n → α) : Prop :=
  ∀ i : Fin n, D.pinned i = true → x i = D.solve i (fun j _ => x j)

/-- The number of pinned coordinates (`k` in the `|α|^{n−k}` count). -/
def DigitSystem.numPinned {n : ℕ} {α : Type*} (D : DigitSystem n α) : ℕ :=
  (Finset.univ.filter (fun i => D.pinned i)).card

end LeanUrat.Moves
