/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Uniformity.ChapD.D07
import Uniformity.ChapD.D13

/-!
# Uniformity.ChapD.D17 — `levelOneArena`, the level-1 gauge arena

**Chapter D, NODE D.17** [def] [fresh] (`blueprint/CHAP-D_gauge_tchain.md` §4, the level-1
gauge layer; amendments A-1 and A-D.1 govern — **A-D.1/D-D2 RE-SIGNS this SIGNATURE with REAL
BODIES**, see below). ENV-D1 + ENV-D3 (`{K : Type*} [Field K]`, `η : Kˣ`).

*The level-1 arena.* The level-1 monomials `x^i π^a` are represented EXACTLY by the exponent
lattice `Multiplicative (ℤ × ℤ)` (first coordinate the `x`-exponent, second the `π`-exponent).
This node lands

* the **height homomorphism** `levelOneHeight e₁ h : (i,a) ↦ i·h + a·e₁` (`EFF.T1.01`'s
  `dv₁(x) = h`, `dv₁(π) = e₁`);
* the **level-1 section** `levelOneSection e₁ h` with `n k = x^{i(k)}π^{a(k)}`, i.e. the
  exponent pair `(iexp e₁ h k, aexp e₁ h k)` (`EFF.T1.01`'s `n̂₁(k)`);
* the **kernel-divisibility lemma** `levelOneHeight_ker_dvd` (D.17's PROOF step 4);
* the **level-1 arena** `levelOneArena e₁ h he hcop η : GaugeArena _ K _`, whose residue
  homomorphism sends `(i,a) ↦ η^{i/e₁}` — well defined because `i·h + a·e₁ = 0` together with
  `Nat.Coprime h e₁` forces `e₁ ∣ i` and `(i,a) = (i/e₁)·(e₁,−h)`, i.e. the value-zero subgroup
  is the cyclic group generated by the exponent pair of `x^{e₁}/π^h`, mapped by `t ↦ η^t`
  (`EFF.T1.01`'s `η = res(x^{e₁}/π^h)`, `K₁ = F_Q(η)`; `EFF.T1.04`'s `z₁ := η`).

**Four public declarations** *[was two; A-D.1/D-D2 adds `levelOneHeight` (note SD-2) and
`levelOneHeight_ker_dvd`]* — sanctioned against GC-6.5, scoped to exactly those names: they are
one instance split only by where the field `K` enters, plus the two names its BODY cannot be
written without. Chapter C and the §10 gates cite the section and the arena by name.

## DEFECT D-D2 (A-D.1) — why the bodies are mandatory, not stylistic

The originally-signed `levelOneArena` row stopped at its TYPE, which §12 rule 2 forbids for a
def-class node. Worse, D.19's residue corollary `res_chi_varpi` and D.21's `levelOne_rho`
apply `(levelOneArena …).res` to a SUBTYPE element, so their membership proofs must mention
`(levelOneArena …).v`: **landing this node as an `axiom`, or with an opaque body, makes those
two statements UNSTATABLE** without inventing extra membership hypotheses (D-D8, the
statability fence). With the real bodies below they are statable exactly as signed.

## Landing order (A-D.1/D-D2) — a DEFINITIONAL dependency on D.13

`BP.D.17 → BP.D.13` is a **definitional** edge, not a lemma edge: the `exact_height` field can
only be discharged from D.13's `iexp_aexp_spec`, so `levelOneArena`'s axiom footprint carries
whatever `iexp_aexp_spec` carries (the stub-stage census printed `iexp_aexp_spec` itself for
`LeanspecD.levelOneArena`, since it was an `axiom` there). D.13 is landed with
`iexp_aexp_spec` PROVED, so this file's footprint prints Lean core only — verified in the
`AxCheck` block below, which is what makes D.68's census read clean for `levelOneArena`.

## Faithfulness

**⚠ Mandatory, trust-boundary definitions.** Flagged for the chapter cross-read and for human
review (parent CLAUDE.md trust boundary).

* *the lattice is an exact model, and deliberately partial.* All §4 consumed identities
  (`EFF.T1.07/.10/.19`) are monomial-exponent identities and their corpus derivations are
  exponent computations, so `Multiplicative (ℤ × ℤ)` models them exactly. What the lattice
  does NOT model is EVALUATION of monomials at field elements — deliberately, per the §4
  design note (the `ξ`-evaluation clauses are chapter C's tower carrier, GC-7). No node of
  this chapter consumes an evaluation.
* *`η` is DATA here.* Its corpus meaning — `η = res(x^{e₁}/π^h)` inside `K₁ = F_Q(η)` with
  basis `1, η, …, η^{f₁−1}` — is restored at D.26, where the coordinate reads land. Nothing in
  this file constrains `η` beyond being a unit.
* *the `(… : ℤ)` cast in `levelOneSection` is REQUIRED*: `iexp` is `ℕ`-valued while the lattice
  is `ℤ × ℤ`.
* *`res` is spelled as a `MonoidHom` built by hand*, not transported: `map_mul'` is exactly the
  additivity of `i ↦ i / e₁` on the kernel, which is `Int.add_ediv_of_dvd_left` against
  `levelOneHeight_ker_dvd`. This is why that lemma is public — it is consumed inside a `def`
  body, where a tactic hole would be an opaque proof term.

DEPENDS: D.01 (`NormSection`) · D.07 (`GaugeArena`) · D.13 (`iexp`, `aexp`, `iexp_aexp_spec`
— the DEFINITIONAL edge above) · mathlib `Multiplicative`, `MonoidHom.ker`,
`Int.add_ediv_of_dvd_left`, `Nat.isCoprime_iff_coprime`, `Nat.Coprime.dvd_of_dvd_mul_right`
— all name-verified at the v4.31.0 pin.

**PROOF.** 1. `n_zero`: `iexp e₁ h 0 = 0` and `aexp e₁ h 0 = 0` compute. 2. `v` is a hom:
componentwise `ℤ`-linearity of `(i,a) ↦ i·h + a·e₁`. 3. `exact_height`: D.13's identity
verbatim, transported along `Multiplicative.ofAdd`. 4. Kernel description: from `i·h + a·e₁ = 0`
we get `e₁ ∣ i·h`, and `Nat.Coprime h e₁` (cast to `IsCoprime` over `ℤ`) gives `e₁ ∣ i`.
5. `res` hom-ness: `t := i / e₁` is additive on the kernel by step 4, so `t ↦ η^t` is a `zpow`
hom. The four bodies are the gate-verified `leanspec/Leanspec/ChapD.lean` stub bodies verbatim
(stage 0e, the D-D2 elaboration, byte-checked green), with the landed namespace restored.

SOURCE: `EFF.T1.01` (the carrier: `dv₁(x) = h`, `dv₁(π) = e₁`, `η`, `K₁`, the basis, `n̂₁(k)`);
`EFF.T1.04` (`z₁ := η`, `(C1-base-letter)`).

**TEETH.** T1 §4.2 checks 1/2/4 (every level-1 check runs through this instance) → gates
D.65/D.66 instantiate it at both primes; nothing is scored inside this file (a definition over
an abstract field, which admits no `decide`).

ENVIRONMENT: ENV-D1 + ENV-D3.

## Status

Sorry-free, axiom-free (Lean core only) — in particular `levelOneArena`'s footprint no longer
carries `iexp_aexp_spec` as an axiom, D.13 having landed it as a theorem.
-/

namespace Uniformity.Density.Gauge

/-- **D.17 — the level-1 height homomorphism.** `v (i,a) = i·h + a·e₁` on the exponent lattice
`Multiplicative (ℤ × ℤ)` (`EFF.T1.01`'s `dv₁(x) = h`, `dv₁(π) = e₁`).  [A-D.1/SD-2: a NEW
public name — the height hom must be nameable for the arena's body AND for its kernel lemma to
be stated at all.] -/
def levelOneHeight (e₁ h : ℕ) : Multiplicative (ℤ × ℤ) →* Multiplicative ℤ where
  toFun g :=
    Multiplicative.ofAdd ((Multiplicative.toAdd g).1 * h + (Multiplicative.toAdd g).2 * e₁)
  map_one' := by simp
  map_mul' x y := by simp [← ofAdd_add]; ring

/-- **D.17 — the level-1 section.** `n k = x^{i(k)}π^{a(k)}`, i.e. the exponent pair
`(iexp e₁ h k, aexp e₁ h k)` (`EFF.T1.01`'s `n̂₁(k)`).  ⚠ the `(… : ℤ)` cast is REQUIRED:
`iexp` is `ℕ`-valued. -/
def levelOneSection (e₁ h : ℕ) : NormSection (Multiplicative (ℤ × ℤ)) where
  n k := Multiplicative.ofAdd ((iexp e₁ h k : ℤ), aexp e₁ h k)
  n_zero := by simp [iexp, aexp]

/-- **D.17's PROOF step 4**, PROVED because `levelOneArena`'s `res` field needs it inside a
`def` body (not a tactic hole, not an `axiom`): the value-zero subgroup of the level-1 height
hom has `x`-coordinate divisible by `e₁`, which is what makes `(i,a) ↦ η^{i/e₁}` a
homomorphism. -/
theorem levelOneHeight_ker_dvd (e₁ h : ℕ) (hcop : Nat.Coprime h e₁)
    {g : Multiplicative (ℤ × ℤ)} (hg : g ∈ MonoidHom.ker (levelOneHeight e₁ h)) :
    (e₁ : ℤ) ∣ (Multiplicative.toAdd g).1 := by
  rw [MonoidHom.mem_ker] at hg
  have h0 : (Multiplicative.toAdd g).1 * h + (Multiplicative.toAdd g).2 * e₁ = 0 := by
    simp only [levelOneHeight, MonoidHom.coe_mk, OneHom.coe_mk, ofAdd_eq_one] at hg
    exact hg
  have hd : (e₁ : ℤ) ∣ (Multiplicative.toAdd g).1 * h :=
    ⟨-(Multiplicative.toAdd g).2, by linarith⟩
  exact (Nat.isCoprime_iff_coprime.mpr hcop.symm).dvd_of_dvd_mul_right hd

/-- **D.17 — the level-1 arena.** Height hom `v (i,a) = i·h + a·e₁`; residue hom
`(i,a) ↦ η^{i/e₁}` on the value-zero subgroup, which by `levelOneHeight_ker_dvd` is exactly the
cyclic group generated by the exponent pair `(e₁, −h)` of `x^{e₁}/π^h` (`EFF.T1.01`,
`EFF.T1.04`).  `exact_height` is D.13's `iexp_aexp_spec` verbatim — the DEFINITIONAL edge
`BP.D.17 → BP.D.13` of A-D.1/D-D2. -/
noncomputable def levelOneArena (e₁ h : ℕ) (he : 0 < e₁) (hcop : Nat.Coprime h e₁)
    {K : Type*} [Field K] (η : Kˣ) :
    GaugeArena (Multiplicative (ℤ × ℤ)) K (levelOneSection e₁ h) where
  v := levelOneHeight e₁ h
  exact_height k := by
    simp only [levelOneSection, levelOneHeight, MonoidHom.coe_mk, OneHom.coe_mk, toAdd_ofAdd]
    exact congrArg Multiplicative.ofAdd (iexp_aexp_spec e₁ h he hcop k).2
  res :=
    { toFun := fun g => η ^ ((Multiplicative.toAdd (g : Multiplicative (ℤ × ℤ))).1 / (e₁ : ℤ))
      map_one' := by simp
      map_mul' := by
        intro g₁ g₂
        have h1 := levelOneHeight_ker_dvd e₁ h hcop g₁.2
        simp only [Subgroup.coe_mul, toAdd_mul, Prod.fst_add]
        rw [Int.add_ediv_of_dvd_left h1, zpow_add] }

end Uniformity.Density.Gauge

/-! ## Axiom footprint -/

section AxCheck

#print axioms Uniformity.Density.Gauge.levelOneHeight
#print axioms Uniformity.Density.Gauge.levelOneSection
#print axioms Uniformity.Density.Gauge.levelOneHeight_ker_dvd
#print axioms Uniformity.Density.Gauge.levelOneArena

end AxCheck
