-- GOLF PASS 2 (2026-07-30): pre-golf axiom baselines for 20 load-bearing OM theorems
-- NOT covered by LeanUrat/AxChk_baseline.lean (their modules are absent from its
-- direct-import + #print census). Generated by the golf-2 planning leg.
import LeanUrat.OM.QuotientBox
import LeanUrat.OM.ResidualPolynomial
import LeanUrat.OM.OMType
import LeanUrat.OM.CellPartition
import LeanUrat.OM.NewtonPolygon
import LeanUrat.OM.LevelNCount
import LeanUrat.OM.Termination
import LeanUrat.OM.PadicValuation
import LeanUrat.OM.ResidueCount
import LeanUrat.OM.LimitGlue
import LeanUrat.OM.LimitSpine
import LeanUrat.OM.LimitRecurrence
import LeanUrat.OM.SchwartzZippel
import LeanUrat.OM.Discriminant
import LeanUrat.OM.RecenterBox
import LeanUrat.OM.CountingModel

#print axioms LeanUrat.OM.QuotientBox.card_monicBox
#print axioms LeanUrat.OM.M4.residualPoly_factorization
#print axioms LeanUrat.OM.M4.factorize_any
#print axioms LeanUrat.OM.M5.nodeSizeOf_child_lt
#print axioms LeanUrat.OM.M7.partition
#print axioms LeanUrat.OM.M7.cellsOfShapeWF_shapeOf
#print axioms LeanUrat.OM.NewtonPolygon.npHeight_convexOn
#print axioms LeanUrat.OM.NewtonPolygon.npVertices_not_stable_of_hull_preserved
#print axioms LeanUrat.OM.M8.shapeFiber_partition
#print axioms LeanUrat.OM.M8.nodeTrunc_tendsto
#print axioms LeanUrat.OM.M6.finiteTermination
#print axioms LeanUrat.OM.M2.valSupport_facts
#print axioms LeanUrat.OM.M0.nonSquarefreeMonicCount
#print axioms LeanUrat.OM.F3.node_limit_assembly
#print axioms LeanUrat.OM.LimitSpine.spine_nodeMeasure_boxSum
#print axioms LeanUrat.OM.LimitRecurrence.firstOrder_recurrence_limit
#print axioms LeanUrat.OM.SchwartzZippel.schwartz_zippel_local
#print axioms LeanUrat.OM.M_F4.discZeroCount_eq_eval_card
#print axioms LeanUrat.OM.RecenterBox.mass_chain2
#print axioms LeanUrat.OM.F1.shapeFiber_consistency_bulk
