/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib
import LeanUrat.HC1.DefsTower
import LeanUrat.MovesGr.Defs
import LeanUrat.MovesC.Defs

/-!
# HC1/DefsCar — the REAL graded carriers (blueprint §2.3)

**Provenance.** `HC1_LEAN_BLUEPRINT_2026-07-28.md` (rev 2) §2.3, with the F3-1/F3-2/
F3-3 repairs built in (D7) and the C-1 strTop re-thread (D3). The carriers are
CONCRETE: `grQ` is MovesGr's `grPiece` of the top stage's side valuation at the
⌊strTop·γ⌋ reindex; `alphabet` is generated by the ACTUAL slot images; `floorB` is
DEFINED from the realizability data's lines via `blockEdge` (no free field).

E-phase structural deviations (all recorded in the blueprint's DEVIATIONS appendix):
* `Tower.side` is defined by choice against the spec `HasSide` (∃ SideVal agreeing
  with the top stage's `w` on nonzeros) with a trivial fallback — `SideVal.w_smul`
  is not definitionally dischargeable at Defs level; `HasSide` is T6's first leg.
* `GradedCarrierR` keeps MovesR's ten-field law-carrying shape; since its laws are
  unit T6's THEOREMS, `Tower.carrier` takes the `CarrierLaws` proof as an argument
  and downstream units are stated on the concrete data (`wQ`/`inGr`/`grQ`).
* The per-read LINES/WINDOWS are NOT tower data (intercepts need the recorded
  vertex); they ride in the `TowerRealizable` structure (§5's open kernel), which
  all line-consuming units already hypothesize. `floorB`/`floorC` live on it.
-/

set_option linter.style.longLine false
set_option linter.style.header false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 800000

namespace LeanUrat.HC1

open Polynomial LeanUrat.Moves LeanUrat.MovesGr

universe u

open scoped Classical

/-- The trivial side valuation (the junk fallback for the choice-based `Tower.side`;
never fires on genuine towers — `HasSide` is provable along the spine). -/
noncomputable def trivSideVal (p : ℕ) [Fact p.Prime] : SideVal p where
  w f := if f = 0 then ⊤ else 0
  w_zero := if_pos rfl
  w_ne_top f hf := by simp [if_neg hf]
  w_neg f := by simp [neg_eq_zero]
  w_add f g := by
    by_cases hfg : f + g = 0
    · simp [hfg]
    · have hor : f ≠ 0 ∨ g ≠ 0 := by
        by_contra hcon
        push Not at hcon
        exact hfg (by simp [hcon.1, hcon.2])
      rcases hor with hf | hg
      · exact le_trans (min_le_left _ _) (by simp [if_neg hf, if_neg hfg])
      · exact le_trans (min_le_right _ _) (by simp [if_neg hg, if_neg hfg])
  w_smul c f := by
    by_cases h : Polynomial.C c * f = 0
    · simp [h]
    · have hf : f ≠ 0 := right_ne_zero_of_mul h
      have hc : c ≠ 0 := fun h0 => h (by simp [h0])
      simp [hf, hc]
  w_mul f g := by
    by_cases h : f * g = 0
    · simp [h]
    · have hf : f ≠ 0 := left_ne_zero_of_mul h
      have hg : g ≠ 0 := right_ne_zero_of_mul h
      simp [hf, hg]
  w_one := by simp

variable {p : ℕ} [Fact p.Prime] {F : Type u} [Field F] [Finite F]

namespace Tower

variable (T : Tower p F)

/-- The spec of the tower's side-valuation bundle: a MovesGr `SideVal` agreeing with
the TOP stage's `σ.w` on nonzeros (`0 ↦ ⊤`) — the `GenuineStageModel.hSw` pattern.
Provable for every tower (the constant-weight nonnegativity behind `w_smul` rides
the spine induction); T6's first leg. -/
def HasSide : Prop :=
  ∃ S : SideVal p, ∀ f : Polynomial ℤ_[p], f ≠ 0 → S.w f = ((T.topStage).w f : WithTop ℤ)

/-- The top stage's side-valuation package (blueprint §2.3): `σ.w` extended by
`0 ↦ ⊤`, laws from `StageCoreL` — chosen against `HasSide`, trivial fallback. -/
noncomputable def side : SideVal p :=
  if h : T.HasSide then h.choose else trivSideVal p

lemma side_w (h : T.HasSide) {f : Polynomial ℤ_[p]} (hf : f ≠ 0) :
    T.side.w f = ((T.topStage).w f : WithTop ℤ) := by
  rw [side, dif_pos h]; exact h.choose_spec f hf

/-- Whether `strTop·γ` is an integer — the stage-lattice condition of D3's recorded
convention (off-lattice γ carries the zero piece map and no weight). -/
def onLattice (γ : ℚ) : Prop := ((⌊(T.strTop : ℚ) * γ⌋ : ℚ) = (T.strTop : ℚ) * γ)

/-- **The real graded pieces** (instantiates MovesR D4(a) at δ = 1; D3 convention):
`Gr γ := (T.side).grPiece ⌊strTop·γ⌋` (strTop = §2.2's frame stretch STR_K·e_K —
audit C-1's re-thread). -/
noncomputable def grQ (γ : ℚ) : Type _ := (T.side).grPiece ⌊(T.strTop : ℚ) * γ⌋

noncomputable instance (γ : ℚ) : AddCommGroup (T.grQ γ) :=
  inferInstanceAs (AddCommGroup ((T.side).grPiece ⌊(T.strTop : ℚ) * γ⌋))

/-- the absolute-scale weight `w := strTop⁻¹·(side weight)` in `WithTop ℚ`. -/
noncomputable def wQ (f : Polynomial ℤ_[p]) : WithTop ℚ :=
  WithTop.map (fun n : ℤ => (n : ℚ) / (T.strTop : ℚ)) (T.side.w f)

/-- the class map into the piece (0 off-lattice or below weight — D3's recorded,
auditable convention: on-lattice γ hits the genuine stage-scale piece; off-lattice γ
has `inγ γ := 0` and no weight ever equals it). -/
noncomputable def inGr (γ : ℚ) (f : Polynomial ℤ_[p]) : T.grQ γ :=
  if h : T.onLattice γ ∧ ((⌊(T.strTop : ℚ) * γ⌋ : WithTop ℤ) ≤ T.side.w f) then
    Submodule.Quotient.mk ⟨f, h.2⟩
  else 0

end Tower

/-- **The re-declared MovesR carrier shape** (blueprint §2.3, pending the MovesR
re-key; one structure, ten fields, same laws — MOVESR blueprint D4(a) verbatim at
ℚ-graded δ = 1). -/
structure GradedCarrierR (p : ℕ) [Fact p.Prime] where
  Coeff : Type                             -- slot coefficients B
  [coeffAdd : AddCommGroup Coeff]
  Gr : ℚ → Type                            -- D.3(e)(i)'s graded pieces
  [grAdd : ∀ γ, AddCommGroup (Gr γ)]
  w : Coeff → WithTop ℚ                    -- the K1-chain-weight function
  inγ : (γ : ℚ) → Coeff → Gr γ             -- the initial-form / class map
  w_add : ∀ B B', min (w B) (w B') ≤ w (B + B')
  inγ_add : ∀ (γ : ℚ) (B B'), (γ : WithTop ℚ) ≤ w B → (γ : WithTop ℚ) ≤ w B' →
    inγ γ (B + B') = inγ γ B + inγ γ B'    -- additivity at weight γ
  inγ_kills : ∀ (γ : ℚ) B, (γ : WithTop ℚ) < w B → inγ γ B = 0  -- kills weight above
  inγ_detects : ∀ (γ : ℚ) B, w B = (γ : WithTop ℚ) → inγ γ B ≠ 0  -- weight detection

attribute [instance] GradedCarrierR.coeffAdd GradedCarrierR.grAdd

namespace Tower

variable (T : Tower p F)

/-- The top coefficient space (deg < deg Φ̂_top), an AddCommGroup via
`Polynomial.degreeLT` — the carrier's `Coeff` (blueprint D3). -/
noncomputable def CoeffTop : Submodule ℤ_[p] (Polynomial ℤ_[p]) :=
  Polynomial.degreeLT ℤ_[p] ((T.topStage).Φ.natDegree)

/-- The four GradedCarrier laws for the tower's concrete data (unit T6's theorem;
`Tower.carrier` packages them). -/
def CarrierLaws : Prop :=
  (∀ B B' : ↥T.CoeffTop, min (T.wQ B) (T.wQ B') ≤ T.wQ (↑B + ↑B')) ∧
  (∀ (γ : ℚ) (B B' : ↥T.CoeffTop), (γ : WithTop ℚ) ≤ T.wQ B → (γ : WithTop ℚ) ≤ T.wQ B' →
    T.inGr γ (↑B + ↑B') = T.inGr γ B + T.inGr γ B') ∧
  (∀ (γ : ℚ) (B : ↥T.CoeffTop), (γ : WithTop ℚ) < T.wQ B → T.inGr γ B = 0) ∧
  (∀ (γ : ℚ) (B : ↥T.CoeffTop), T.wQ B = (γ : WithTop ℚ) → T.inGr γ B ≠ 0)

/-- **The real GradedCarrier** (instantiates MovesR D4(a) at δ = 1; D3 convention),
packaged from the concrete data once the laws (unit T6) are supplied. -/
noncomputable def carrier (hL : T.CarrierLaws) : GradedCarrierR p where
  Coeff := ↥T.CoeffTop
  Gr := T.grQ
  w := fun B => T.wQ B
  inγ := fun γ B => T.inGr γ B
  w_add := hL.1
  inγ_add := hL.2.1
  inγ_kills := hL.2.2.1
  inγ_detects := hL.2.2.2

/-- block map: the development-slot block label (D.3(e)(ii)) — the TOP slot. -/
def blk (c : T.Coord) : ℕ := c.slot (Fin.last T.K)

/-- level set `L_γ(b) = {c : blk c = b ∧ ht c = γ}` (D.3(e)(ii)). -/
def levelSet (b : ℕ) (γ : ℚ) : Set T.Coord := {c | T.blk c = b ∧ T.ht c = γ}

/-- Teichmüller-style digit lift (blueprint §2.3's `y′`): a base-stage (S6a)
realizer of the F_Q-digit `y` at parent weight 0, chosen by choice (0 at digit 0 or
if no realizer exists — hS6a supplies existence on genuine towers). Bound to the
Moves base-residue apparatus through the (S6a) shape. -/
noncomputable def digLift (y : ↥(T.stg 0).FQ) : Polynomial ℤ_[p] :=
  if h : ∃ B : Polynomial ℤ_[p], B ≠ 0 ∧ inC (T.stg 0).Φ B ∧ (T.stg 0).wPrev B = 0 ∧
      (T.stg 0).R B = LaurentPolynomial.C (⟨(y : F), (T.stg 0).hFQ_le y.2⟩ : ↥(T.stg 0).K) *
        LaurentPolynomial.T 0
  then h.choose else 0

/-- slot coefficient of a digit assignment on a block: `Σ_{c ∈ blk b} y′_c·m_c`
(TYP(a)'s display: B IS its tower expansion; junk 0 at infinite support —
consumers restrict to finitely supported assignments). -/
noncomputable def slotCoeff (b : ℕ) (y : T.Coord → ↥(T.stg 0).FQ) :
    Polynomial ℤ_[p] :=
  ∑ᶠ c ∈ {c : T.Coord | T.blk c = b}, T.digLift (y c) * T.mono c

/-- **the TYP composite** (D7(i) — THE additive object): level-set digits →
graded piece, `(y_c)_c ↦ inγ γ (slotCoeff b y)` on L_γ(b)-supported assignments. -/
noncomputable def typComposite (b : ℕ) (γ : ℚ)
    (y : ↥(T.levelSet b γ) → ↥(T.stg 0).FQ) : T.grQ γ :=
  T.inGr γ (T.slotCoeff b (fun c => if h : c ∈ T.levelSet b γ then y ⟨c, h⟩ else 0))

/-- **the alphabet = the slot-image SPAN** (D7(ii), the F3-2 repair): the additive
closure of the single-coordinate images. -/
noncomputable def alphabet (b : ℕ) (γ : ℚ) : AddSubgroup (T.grQ γ) :=
  AddSubgroup.closure (⋃ c : ↥(T.levelSet b γ),
    Set.range fun y : ↥(T.stg 0).FQ => T.typComposite b γ (Pi.single c y))

/-- `aDim` := the alphabet's p-logarithm (T7's exactness equation is the theorem). -/
noncomputable def aDim (b : ℕ) (γ : ℚ) : ℕ := Nat.log p (Nat.card ↥(T.alphabet b γ))

/-- the block's left base edge: block b of the TOP frame starts at `b·deg Φ_top`
(C.1.0(a) blocks; the F3-3 staircase floor evaluates lines here). -/
noncomputable def blockEdge (b : ℕ) : ℕ := b * (T.topStage).Φ.natDegree

/-- The frame width of read k: 1 at the root read, `deg Φ_{k−1}` for k ≥ 1 (the
fine-slot width of the frame read k happens in — C.1.0(a)). -/
noncomputable def frameWidth : ℕ → ℕ
  | 0 => 1
  | k + 1 => if h : k < T.K + 1 then (T.stg ⟨k, h⟩).Φ.natDegree else 1

end Tower

/-- **The realizability data of a tower** (blueprint §5's open kernel: per-move
(SAE) + (NA) + (HV), C.0's realizability data conditions, "typed as a structure
over the tower's lines/windows"). It CARRIES the per-read side lines and windows —
they are recorded §C data, NOT tower data (Deviation D-3: intercepts/windows need
the per-read vertex, which `Tower` does not record) — tied to the tower by the
slope law, plus the three realizability conditions in the form the DOM/LST
consumers read: the steeper chain ((I-aug) on lines), the vertex-entry endpoint
inequality at each per-i interior end ((SAE)'s seed for DOM), the window
containment inside the previous rim ((NA)'s locus), and the vertex-height tie
((HV): the line passes through the recorded window vertex at its recorded height).
Never discharged inside HC1 (its discharge per-instance is classifier work,
HC-2-side). -/
structure TowerRealizable (T : Tower p F) where
  /-- read k's side line (absolute v_p-scale, MovesC affine form) -/
  line : ℕ → MovesC.Line
  /-- read k's window left slot `s₀` -/
  s0 : ℕ → ℕ
  /-- read k's window width `wSide` (slots) -/
  wSide : ℕ → ℕ
  /-- read k's descend order μ (the rim threshold data) -/
  mu : ℕ → ℕ
  /-- read k's recorded vertex height u* (absolute scale) -/
  ustar : ℕ → ℚ
  /-- the per-i factor-interior end (DOM's `[0, interiorEnd i)`) -/
  interiorEnd : ℕ → ℕ
  /-- the slope law: read k's line descends at `κ_k` per frame-k fine slot —
  `slope·D = κ` (C.1.0(c); ties the recorded lines to the tower's own read data). -/
  slope_law : ∀ k : Fin (T.K + 1), (line k.val).slope * (T.frameWidth k.val : ℚ) = T.kappa k
  /-- (HV) tie: the line passes through the window's right endpoint at height u*. -/
  vertex_tie : ∀ k : Fin (T.K + 1),
    (line k.val).at ((s0 k.val + wSide k.val) * T.frameWidth k.val) = ustar k.val
  /-- the (I-aug) steeper chain on the recorded lines. -/
  steeper : ∀ k : Fin (T.K + 1), ∀ m, m < k.val → (line m).slope < (line k.val).slope
  /-- (SAE)'s vertex-entry seed: at each per-i interior end the current line
  dominates every earlier one (MovesC `DomData.vertex_entry`'s shape). -/
  vertex_entry : ∀ k : Fin (T.K + 1), ∀ m, m ≤ k.val →
    (line m).at (interiorEnd k.val) ≤ (line k.val).at (interiorEnd k.val)
  /-- (NA)'s locus: the next read's window sits inside the previous read's rim. -/
  window : ∀ k : ℕ, k < T.K → s0 (k + 1) + wSide (k + 1) ≤ mu k

namespace TowerRealizable

variable {T : Tower p F} (rl : TowerRealizable T)

/-- **THE STAIRCASE FLOOR** (the F3-3 repair, by construction):
`floorB b := (lines K).at (blockEdge b)` — the current read line at the block's
left base edge. -/
noncomputable def floorB (b : ℕ) : ℚ := (rl.line T.K).at (T.blockEdge b)

/-- the pointwise history-floor max at a coordinate's base index (MovesC `floorOf`;
T10's `floorC`). -/
noncomputable def floorC (c : T.Coord) : ℚ :=
  MovesC.floorOf rl.line T.K (T.baseIdx c)

/-- factor-interior blocks: the whole block sits inside the top read's per-i
factor interior. -/
def interiorB (b : ℕ) : Prop := T.blockEdge (b + 1) ≤ rl.interiorEnd T.K

end TowerRealizable

end LeanUrat.HC1
