/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib
import LeanUrat.HC1.DefsSpine
import LeanUrat.Moves.L4_TRANSv_R3
import LeanUrat.Moves.L4_TRANSviii_b_R4
import LeanUrat.Moves.L2_widthBound

/-!
# HC1.S6_childS4field — D.7(v): the child degree-0 coefficient field is F′ = K⟮z̄⟯

moves_ref: MOVES 2364–2391 (D.7(v), ingredients (1)–(3) displayed). deps: S5;
Moves `L4_TRANSv_R3` (CLEAN — repaired at 4b29f6e, +StageCore fence-change
APPROVED per its header; §4.3 CLOSED — S6 supplies `hcore` from the spine),
`L4_TRANSviii_b_R4` (clean, the (S6b) recursion), `L2_widthBound` (clean). sketch:
unit-monomial weights from powers of in(p); g consecutive stride positions; (S6b)
scalars above the clean threshold; span = F′. difficulty: HARD. hyp: none.
-/

set_option linter.style.longLine false
set_option linter.style.header false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 800000

namespace LeanUrat.HC1

open Polynomial LeanUrat.Moves

/-- **(ingredient 2 helper)** Every `z̄`-evaluation of a Laurent polynomial over the current
field `K` lands in the next residue field `F′ = K⟮z̄⟯`: `eval₂` is a ring hom generated by
`C`-values (in `K ⊆ F′`) and `T`-powers (integer powers of `z̄ ∈ F′`). -/
private lemma eval₂_mem_nextField {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]
    (σ : Stage p F) (zbar : Fˣ) (q : LaurentPolynomial ↥σ.K) :
    LaurentPolynomial.eval₂ σ.K.subtype zbar q ∈ σ.nextField zbar := by
  induction q using LaurentPolynomial.induction_on' with
  | add r s hr hs => rw [map_add]; exact add_mem hr hs
  | C_mul_T n a =>
    rw [LaurentPolynomial.eval₂_C_mul_T, Units.val_zpow_eq_zpow_val]
    have hz : (zbar : F) ∈ σ.nextField zbar := Subfield.subset_closure (Or.inr rfl)
    exact mul_mem (σ.le_nextField zbar (SetLike.coe_mem a)) (zpow_mem hz n)

/-- Unit S6: the D-map (dig′ per piece) on the lift coefficient space `C_Φ̂` is
additive-injective per piece (equal digits at equal weight force a deeper
difference) with image ALL of F′ = K⟮z̄⟯ by the LARGE-WEIGHT (S6b) argument. -/
theorem S6_childS4field {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]
    (σ : Stage p F) (hσ : StageCoreL σ) {ψ : Polynomial ↥σ.K} {g : ℕ}
    {Φhat : Polynomial ℤ_[p]} {e' h' : ℕ} {zbar : Fˣ}
    (th : TransHyp σ ψ g Φhat e' h' zbar) :
    (∀ x : F, x ∈ σ.nextField zbar → x ≠ 0 →
      ∃ B : Polynomial ℤ_[p], B ≠ 0 ∧ inC Φhat B ∧ σ.digPrime zbar B = x) ∧
    (∀ B : Polynomial ℤ_[p], B ≠ 0 → inC Φhat B →
      σ.digPrime zbar B ∈ σ.nextField zbar) ∧
    (∀ B B' : Polynomial ℤ_[p], B ≠ 0 → B' ≠ 0 → B - B' ≠ 0 →
      inC Φhat B → inC Φhat B' → σ.w B = σ.w B' →
      σ.digPrime zbar B = σ.digPrime zbar B' → σ.w B < σ.w (B - B')) := by
  -- `z̄` is a root of `ψ` in the polynomial `eval₂` form the Moves engine expects
  have hzbar : Polynomial.eval₂ σ.K.subtype (zbar : F) ψ = 0 := by
    have h := th.hroot
    rwa [Polynomial.aeval_def, Polynomial.eval₂_map, Algebra.algebraMap_self, RingHom.id_comp] at h
  refine ⟨?_, ?_, ?_⟩
  · -- (1) SURJECTIVITY onto `F′`: `L4_TRANSv` at any nonzero target (`hcore` from the spine)
    intro x hx hx0
    obtain ⟨B, hmem, hdig, hnz⟩ :=
      L4_TRANSv σ hσ.core ψ g th.hdeg th.hmonic th.hirr th.hne_z Φhat th.hlift zbar hzbar x hx
    exact ⟨B, hnz hx0, hmem, hdig⟩
  · -- (2) IMAGE ⊆ `F′`: `digPrime` is `eval₂` of a `↥K`-Laurent polynomial at `z̄`
    intro B _ _
    exact eval₂_mem_nextField σ zbar (σ.R B)
  · -- (3) ADDITIVE-INJECTIVE PER PIECE (equal digits at equal weight force a deeper difference)
    intro B B' hB hB' hBB' hmemB hmemB' hwEq _hdigEq
    by_contra hle
    rw [not_lt] at hle
    -- weight facts: `w(-1) = 0`, hence `w(-B') = w(B')`
    have hm1 : (-1 : Polynomial ℤ_[p]) ≠ 0 := neg_ne_zero.mpr one_ne_zero
    have hw1 : σ.w (1 : Polynomial ℤ_[p]) = 0 := by
      have h := σ.hwmul 1 1 one_ne_zero one_ne_zero; rw [one_mul] at h; omega
    have hwm1 : σ.w (-1 : Polynomial ℤ_[p]) = 0 := by
      have h := σ.hwmul (-1) (-1) hm1 hm1
      rw [neg_mul_neg, one_mul, hw1] at h; omega
    have hwnegB' : σ.w (-B') = σ.w B' := by
      have h := σ.hwmul (-1) B' hm1 hB'
      rw [neg_one_mul] at h; rw [h, hwm1, zero_add]
    -- the difference is not shallower than the pieces: `γ ≤ w(B − B')`
    have hsub : B + (-B') = B - B' := by ring
    have hlow : σ.w B ≤ σ.w (B - B') := by
      have h := σ.hwult B (-B') hB (neg_ne_zero.mpr hB') (by rw [hsub]; exact hBB')
      rw [hwnegB', ← hwEq, min_self, hsub] at h; exact h
    have hEq : σ.w (B - B') = σ.w B := le_antisymm hle hlow
    -- residual additivity at the tied weight: `R(B) = R(B − B') + R(B')`
    have hsum : (B - B') + B' = B := by ring
    have hRB : σ.R B = σ.R (B - B') + σ.R B' := by
      have h := σ.hRadd (B - B') B' hBB' hB' (by rw [hsum]; exact hB)
        (by rw [hEq]; exact hwEq) (by rw [hsum, hEq])
      rwa [hsum] at h
    -- transport to the digit level: `digPrime B = digPrime(B − B') + digPrime B'`
    have hdigadd : σ.digPrime zbar B
        = σ.digPrime zbar (B - B') + σ.digPrime zbar B' := by
      simp only [Stage.digPrime]; rw [hRB, map_add]
    -- equal digits ⟹ the difference has zero digit
    have hdigzero : σ.digPrime zbar (B - B') = 0 := by
      have h2 : σ.digPrime zbar (B - B') + σ.digPrime zbar B'
          = 0 + σ.digPrime zbar B' := by rw [zero_add, ← hdigadd, _hdigEq]
      exact add_right_cancel h2
    -- but a nonzero coefficient at a definite weight has a NONZERO digit (`L3_digPrime_nonzero`)
    have hmemsub : inC Φhat (B - B') := by
      show (B - B').degree < Φhat.degree
      calc (B - B').degree ≤ max B.degree B'.degree := Polynomial.degree_sub_le B B'
        _ < Φhat.degree := max_lt hmemB hmemB'
    obtain ⟨_, hΦdeg⟩ := L3_liftMonic σ ψ g th.hg Φhat th.hlift
    have hsubdeg : (B - B').natDegree < σ.e * g * σ.Φ.natDegree := by
      rw [← hΦdeg]; exact Polynomial.natDegree_lt_natDegree hBB' hmemsub
    exact L3_digPrime_nonzero σ ψ g th.hdeg th.hirr th.hne_z zbar hzbar (B - B') hBB' hsubdeg
      hdigzero

end LeanUrat.HC1

#print axioms LeanUrat.HC1.S6_childS4field
