#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
w11_checks.py -- SEALED BATTERY for W11_PROOF_2026-08-08.md
(W-11 at the n = 2 slice: the COMPLETE decided menu of monic quadratics
-- every decided shape, its exact window-N count as ONE q-polynomial,
the exhaustiveness sum, and the EXACT drainage law undecided = q^N --
at every tested prime power q, BOTH residue characteristics, wild p = 2
included.  The hExhaust program (RealInstanceV2.montes_unconditional_
exhaustive's hypothesis) instantiated and verified at n = 2.)

TWO-COMMIT SEAL.  Commit 1 = this runner + the note with its
preregistered predictions, battery UNRUN on the full roster; commit 2 =
the verdict appended to the note FROM the committed artifacts
(w11_checks_output.txt / w11_checks_results.json).  PRE-SEAL SMOKE
DISCLOSED: developed and debugged with `--smoke` (census rows
(Zp,2,3),(Zp,2,4),(Zp,3,2),(Fqt,4,2),(Fqt,9,3); towers C2A,C3E; oracle
row (3,2) + (2,3)); observed on the smoke rows: all violation families
0, all five teeth firing; the note's S5 spot-value table was computed
BY HAND from the S2 closed forms first and confirmed at smoke
((Zp,2,4) per-center table and the (Fqt,9,3) seven-family table sum
531,441 exactly).  DEVICE PROBE DISCLOSED: `gp` availability
(factorpadic + nfinit on x^2+2x+2 at p=2) probed before composition.
No full run happened before the seal.

THE MENU UNDER TEST (note S0/S2).  n = 2, O a complete DVR with residue
field F_q, window N (coefficients in O/pi^N).  The classifier read is
RECURSIVE: level-0 factorization of fbar; if double root, recenter and
read the Newton polygon of (0,u=v(a0')),(1,w=v(a1')),(2,0); refinement
(residual double root) recenters again at depth k and recurses on the
node C(2k+1,k+1) = {v(a0'') >= 2k+1, v(a1'') >= k+1}.  DECIDED LEAVES
(absolute params; histories = tuples of refinement depths, counts summed
over histories -- note S2.5 proves the instance bracket q^(k-1)):

  SEP-SPLIT / SEP-INERT   order-0 separable reduction    sigma split/inert
  RAM(h), h odd           one side slope h/2: (2,h,1)    sigma ram
  2SIDED(w1,w2), w1<w2    two sides: roots at vals w1,w2 sigma split
  SPLITEQ(k)              e=1 side, residual sep-split   sigma split
  INERTDEEP(k)            e=1 side, residual irreducible sigma inert
  SPLIT-TAIL(w)           u >= N certified > 2w          sigma split
                          (sigma-decided, shape-truncated at the window)
  UNDECIDED               a0''=0 in window, w > (N-1)/2  (incl. squares)

  WINDOW-COUNT LAWS UNDER TEST (exact integers, per row, per center;
  q centers; note S2.5):
    RAM(h=2k-1):   (q-1) q^(2N-2k-1)        [k=1 row == THEOREM W-10]
    2SIDED(w1,w2): (q-1)^2 q^(2N-3-w1-w2)
    SPLITEQ(k):    (q-1)(q-2)/2 q^(2N-2k-3)
    INERTDEEP(k):  q(q-1)/2 q^(2N-3k-2) q^(k-1) = (q-1)/2 q^(2N-2k-2)
    SPLIT-TAIL(w): (q-1) q^(N-2)             [independent of w]
    UNDECIDED:     q^(N-1)                   [THE EXACT DRAINAGE LAW]
    SEP-SPLIT = SEP-INERT = (q^2-q)/2 q^(2N-2)  [whole space, no center]
    SUM of everything = q^(2N)               [EXHAUSTIVENESS]
    split-decided == inert-decided           [the sigma symmetry]
    sandwich: dec_sigma <= classical_sigma * q^(2N) <= dec_sigma + undec
      with classical split = inert = q/(2(q+1)), ram = 1/(q+1).

WHAT IS KEYED (note section in brackets):

  W11-PIN     md5 pins of the frozen imports (violation if moved);
              includes w10_checks.py -- W-10's instrument consumed at
              its sealed bytes.
  W11-CENSUS  [S2.5]  per row: EVERY (leaf,params) count == the closed
              form (predictions generated by an independent implementa-
              tion of the node recursion, not by the classifier);
              exhaustiveness sum == q^(2N); refinement-history census
              reported (max depth must reach floor((N-1)/2)).
  W11-W10TIE  [S1]  pointwise per polynomial: leaf == RAM(1) (empty
              history forced) <=> w10_checks.classify bucket '211' --
              THEOREM W-10 consumed at pin as the RAM(1) row.
  W11-EXHAUST [S2.5] undecided == q^(N-1) per center and q^N per row
              EXACTLY; split-decided == inert-decided EXACTLY; the
              classical-density sandwich as exact rationals.
  W11-TOWER   [S2.6] frozen-roster realization leg, WIDENED from W-10's
              (2,1,1)-only to the full RAM family (e=2, g=1, h odd):
              endpoints (0,gam),(2,0), gam odd == e*wPhi + h, interior
              strictly above; >= 1 wild realization AND >= 1 realized
              level NOT of the (2,1,1) shape (C3E's (2,3,1) at p=2).
  W11-ORACLE  [S2.6] the INDEPENDENT engine (PARI/GP): per polynomial
              at the Zp oracle rows -- factorpadic/nfinit sigma + (e,f)
              + v(disc) MUST match the decided leaf's prediction
              (RAM(h): vd = h at p odd, h+1/h+2 by the w rule at p = 2;
              2SIDED/SPLIT-TAIL: vd = 2w; SPLITEQ/INERTDEEP: vd = 2k;
              SEP: vd = 0); degenerate disc = 0 must be UNDECIDED;
              undecided members unscored (sigma not determined by the
              window -- recorded only).  DOUBLE-LIFT leg: on decided
              members of the small rows, the lift and lift + p^N agree
              in PARI (decidedness is well-posed).

  TEETH (each must fire >= 1 GLOBALLY or the battery is RED):
  W11-T-MISSING   exhaustiveness sum with the RAM family DELETED must
                  show a deficit on every census row (a dropped menu
                  family cannot hide).
  W11-T-SHADOW    sum with the RAM(1) row DOUBLE-COUNTED must exceed
                  q^(2N) on every row (an overlapping menu row cannot
                  hide).
  W11-T-DRAIN     the drainage law corrupted to q^N per center must
                  mismatch the observed undecided count on every row.
  W11-T-SIGMA     the menu with INERTDEEP/SEP-INERT mis-keyed to sigma
                  = split must be caught by the PARI oracle on every
                  inert member of every oracle row.
  W11-T-TAMEDISC  the tame disc prediction v(disc) = e-1 = 1 must FAIL
                  on every p = 2 RAM member (every wild row is
                  genuinely wild; the counts are unchanged anyway).

CENSUS ROWS (30).  Zp: (p,N) in {(2,2),(2,3),(2,4),(2,6),(2,8),(3,2),
(3,3),(3,4),(5,2),(5,3),(7,2),(7,3)}; Fqt: (q,N) in {2,3,4,5,7,8,9} x
{2,3} + (2,4),(2,6),(2,8),(3,4) -- ~1.24M polynomials, exact
arithmetic, no floats.  Deep rows (N = 6, 8) realize multi-step
refinement histories (depths up to 3) and menu rows through RAM(7),
SPLITEQ/INERTDEEP(3), 2SIDED(2,5).  DISCLOSED LIMITS (same as W-10):
no mixed-characteristic prime-power rows (no frozen unramified-base
ring) -- prime-power q is carried by the eq-char rows; the oracle leg
is mixed-char only (PARI factorpadic is Q_p-only), so eq-char rows are
SAME-class evidence.

ORACLE ROWS: full per-polynomial at (p,N) in {(2,3),(2,4),(2,6),(3,2),
(3,3),(5,2),(7,2)} (~8.3k polynomials); double-lift on the decided
members of {(2,3),(3,2),(3,3),(2,4)}.

TOWER SUBSET (frozen rosters by md5-pinned import): W-10's seven (C2A,
C2C, C2E, C2F, P3A, J7A, P1B) + C3E (reads (2,1,2),(1,1,1),(2,3,1):
the wild h = 3 realization at p = 2).

FROZEN-IMPORT PINS (W11-PIN; violation if a pinned file's md5 moved):
  iterlawn_pe_reimpl.py  cae45db2318b89520dd5484466ef3604
  grt_jc_probe.py        03811b695cf7aa1bd5b52d5b0cd8bcd6
  jd0_checks.py          d3a5e13df97d3768573800960a0ec509
  w10_checks.py          a9c34244a3af19f5fa864375b494380b

Exact arithmetic throughout; deterministic; oracle = PARI/GP subprocess.
"""

import sys, os, json, time, hashlib, subprocess, itertools
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import iterlawn_pe_reimpl as ITL
import grt_jc_probe as JCP
import jd0_checks as JD0
import w10_checks as W10

PINS = {
    'iterlawn_pe_reimpl.py': 'cae45db2318b89520dd5484466ef3604',
    'grt_jc_probe.py':       '03811b695cf7aa1bd5b52d5b0cd8bcd6',
    'jd0_checks.py':         'd3a5e13df97d3768573800960a0ec509',
    'w10_checks.py':         'a9c34244a3af19f5fa864375b494380b',
}

FAMILIES = ['W11-PIN', 'W11-CENSUS', 'W11-W10TIE', 'W11-EXHAUST',
            'W11-TOWER', 'W11-ORACLE']
TEETH = ['W11-T-MISSING', 'W11-T-SHADOW', 'W11-T-DRAIN', 'W11-T-SIGMA',
         'W11-T-TAMEDISC']

VIOL = {f: [] for f in FAMILIES}
NCHK = {f: 0 for f in FAMILIES}
FIRE = {t: 0 for t in TEETH}


def note(fam, n=1):
    NCHK[fam] += n


def viol(fam, tag, detail):
    VIOL[fam].append((tag, detail))
    print('  VIOLATION [%s] %s: %s' % (fam, tag, detail))


# ---------------------------------------------------------- field helpers
def is_square(K, q, z):
    """z in K^*: is z a square?  (odd q only)."""
    r = K.one()
    for _ in range((q - 1) // 2):
        r = K.mul(r, z)
    return r == K.one()


def abs_trace2(K, k, z):
    """absolute trace F_{2^k} -> F_2 as 0/1: sum z^(2^i)."""
    t, cur = K.zero(), z
    for _ in range(k):
        t = K.add(t, cur)
        cur = K.mul(cur, cur)
    return not K.is_zero(t)      # True <=> Tr = 1


# ---------------------------------------------------------- the classifier
def sep_sigma(R, q, a0b, a1b):
    """fbar separable: 'split' (two roots in F_q) or 'inert'."""
    K = R.K
    if R.p == 2:
        # char 2, a1b != 0: Artin-Schreier: split iff Tr(a0b/a1b^2) = 0
        d = K.mul(a0b, K.inv(K.mul(a1b, a1b)))
        return 'inert' if abs_trace2(K, R.k, d) else 'split'
    four = K.add(K.add(K.one(), K.one()), K.add(K.one(), K.one()))
    disc = K.add(K.mul(a1b, a1b), K.neg(K.mul(four, a0b)))
    return 'split' if is_square(K, q, disc) else 'inert'


def classify_full(R, q, a0, a1):
    """The full recursive n=2 read of f = x^2 + a1 x + a0 over R = O/pi^N.
    Returns dict: kind, params, hist, center (repr), sigma, vd
    (predicted v(disc) for Zp rows; None when not determined/needed)."""
    K, k, N = R.K, R.k, R.N
    a0b, a1b = R.res(a0, 0), R.res(a1, 0)
    # ---- level 0
    if R.p == 2:
        if not K.is_zero(a1b):
            return {'kind': 'SEP-' + sep_sigma(R, q, a0b, a1b).upper(),
                    'params': (), 'hist': (), 'center': None,
                    'sigma': sep_sigma(R, q, a0b, a1b), 'vd': 0}
        cb = W10.sqrt_char2(K, a0b, k)
    else:
        four = K.add(K.add(K.one(), K.one()), K.add(K.one(), K.one()))
        disc = K.add(K.mul(a1b, a1b), K.neg(K.mul(four, a0b)))
        if not K.is_zero(disc):
            sg = sep_sigma(R, q, a0b, a1b)
            return {'kind': 'SEP-' + sg.upper(), 'params': (), 'hist': (),
                    'center': None, 'sigma': sg, 'vd': 0}
        cb = K.neg(K.mul(a1b, K.inv(K.add(K.one(), K.one()))))
    c = R.lift(cb)
    two_c = R.add(c, c)
    A1 = R.add(a1, two_c)
    A0 = R.add(R.add(R.mul(c, c), R.mul(a1, c)), a0)
    hist = []
    # pi powers for refinement shifts
    piw = R.pi()

    def pipow(m):
        r = None
        for _ in range(m):
            r = piw if r is None else R.mul(r, piw)
        return r

    while True:
        u, w = R.val(A0), R.val(A1)
        base = {'hist': tuple(hist), 'center': repr(cb)}
        if u is not None:
            if u % 2 == 1 and (w is None or 2 * w >= u + 1):
                kk = (u + 1) // 2
                if R.kind == 'Zp':
                    if R.p != 2:
                        vd = u
                    else:
                        vd = u + 1 if w == kk else u + 2
                else:
                    vd = None
                base.update({'kind': 'RAM', 'params': (u,), 'sigma': 'ram',
                             'vd': vd, 'w': w})
                return base
            if w is not None and 2 * w < u:
                base.update({'kind': '2SIDED', 'params': (w, u - w),
                             'sigma': 'split',
                             'vd': 2 * w if R.kind == 'Zp' else None})
                return base
            # u = 2k even, w >= k (or None): the e=1 residual read
            kk = u // 2
            c1 = R.res(A1, kk) if (w is not None and w == kk) else K.zero()
            c0 = R.res(A0, u)
            assert not K.is_zero(c0)
            if R.p == 2:
                if not K.is_zero(c1):
                    d = K.mul(c0, K.inv(K.mul(c1, c1)))
                    sg = 'inert' if abs_trace2(K, R.k, d) else 'split'
                    zb = None
                else:
                    sg, zb = None, W10.sqrt_char2(K, c0, k)
            else:
                four = K.add(K.add(K.one(), K.one()),
                             K.add(K.one(), K.one()))
                dR = K.add(K.mul(c1, c1), K.neg(K.mul(four, c0)))
                if not K.is_zero(dR):
                    sg, zb = ('split' if is_square(K, q, dR) else 'inert'), \
                             None
                else:
                    sg, zb = None, K.neg(K.mul(c1, K.inv(K.add(K.one(),
                                                               K.one()))))
            if sg is not None:
                base.update({'kind': 'SPLITEQ' if sg == 'split'
                             else 'INERTDEEP', 'params': (kk,),
                             'sigma': sg,
                             'vd': u if R.kind == 'Zp' else None})
                return base
            # refinement at depth kk with letter zb != 0
            assert not K.is_zero(zb)
            s = R.mul(R.lift(zb), pipow(kk))
            A0 = R.add(R.add(R.mul(s, s), R.mul(A1, s)), A0)
            A1 = R.add(A1, R.add(s, s))
            hist.append(kk)
            continue
        # u = None: a0-part vanishes in the window
        if w is not None and 2 * w + 1 <= N:
            base.update({'kind': 'SPLIT-TAIL', 'params': (w,),
                         'sigma': 'split',
                         'vd': 2 * w if R.kind == 'Zp' else None})
            return base
        base.update({'kind': 'UNDECIDED', 'params': (), 'sigma': None,
                     'vd': None, 'w': w})
        return base


# ---------------------------------------------------------- predictions
def predict(q, N):
    """Closed-form window-N counts per (kind, params), PER CENTER for the
    deep families and WHOLE-SPACE for SEP-*; an independent implementation
    of the node recursion (S2.5), NOT the classifier."""
    out = {}

    def add(key, cnt):
        if cnt:
            out[key] = out.get(key, 0) + cnt

    def node(lo0, lo1, mult):
        # space C(lo0, lo1) inside (O/pi^N)^2, arriving multiplicity mult
        for u in range(lo0, N):
            if u % 2 == 1:
                kk = (u + 1) // 2
                add(('RAM', (u,)),
                    mult * (q - 1) * q ** (N - 1 - u)
                    * q ** (N - max(lo1, kk)))
                # two-sided part with w < kk handled below
                for w in range(lo1, kk):
                    add(('2SIDED', (w, u - w)),
                        mult * (q - 1) ** 2 * q ** (2 * N - 2 - u - w))
            else:
                kk = u // 2
                assert kk >= lo1, 'node invariant k >= lo1 broken'
                for w in range(lo1, kk):
                    add(('2SIDED', (w, u - w)),
                        mult * (q - 1) ** 2 * q ** (2 * N - 2 - u - w))
                cell = q ** (N - u - 1) * q ** (N - kk - 1)
                add(('SPLITEQ', (kk,)),
                    mult * ((q - 1) * (q - 2) // 2) * cell)
                add(('INERTDEEP', (kk,)),
                    mult * (q * (q - 1) // 2) * cell)
                # refinement: q-1 letters, each a full C(2k+1, k+1)
                node(u + 1, kk + 1, mult * (q - 1))
        # u >= N (A0 = 0 in the window)
        for w in range(lo1, N):
            if 2 * w + 1 <= N:
                add(('SPLIT-TAIL', (w,)),
                    mult * (q - 1) * q ** (N - 1 - w))
            else:
                add(('UNDECIDED', ()), mult * (q - 1) * q ** (N - 1 - w))
        add(('UNDECIDED', ()), mult)      # A1 = 0 too

    node(1, 1, 1)
    return out


# ---------------------------------------------------------- census rows
CENSUS_ROWS = [('Zp', 2, 2), ('Zp', 2, 3), ('Zp', 2, 4), ('Zp', 2, 6),
               ('Zp', 2, 8),
               ('Zp', 3, 2), ('Zp', 3, 3), ('Zp', 3, 4),
               ('Zp', 5, 2), ('Zp', 5, 3),
               ('Zp', 7, 2), ('Zp', 7, 3),
               ('Fqt', 2, 2), ('Fqt', 2, 3), ('Fqt', 2, 4), ('Fqt', 2, 6),
               ('Fqt', 2, 8),
               ('Fqt', 3, 2), ('Fqt', 3, 3), ('Fqt', 3, 4),
               ('Fqt', 4, 2), ('Fqt', 4, 3),
               ('Fqt', 5, 2), ('Fqt', 5, 3),
               ('Fqt', 7, 2), ('Fqt', 7, 3),
               ('Fqt', 8, 2), ('Fqt', 8, 3),
               ('Fqt', 9, 2), ('Fqt', 9, 3)]

SMOKE_CENSUS = [('Zp', 2, 3), ('Zp', 2, 4), ('Zp', 3, 2), ('Fqt', 4, 2),
                ('Fqt', 9, 3)]


def run_census_row(kind, q, N):
    R = W10.ZpWin(q, N) if kind == 'Zp' else W10.FqtWin(q, N)
    t1 = time.time()
    els = list(R.elems())
    total = 0
    counts = {}                    # (kind, params) -> count
    hist_census = {}               # len(hist) -> count
    max_depth_seen = 0
    sig = {'split': 0, 'inert': 0, 'ram': 0, None: 0}
    w10tie_bad = 0
    for a0 in els:
        for a1 in els:
            total += 1
            rec = classify_full(R, q, a0, a1)
            key = (rec['kind'], rec['params'])
            counts[key] = counts.get(key, 0) + 1
            sig[rec['sigma']] += 1
            h = len(rec['hist'])
            hist_census[h] = hist_census.get(h, 0) + 1
            if h > max_depth_seen:
                max_depth_seen = h
            # W-10 tie, pointwise: leaf RAM(1) <=> w10 bucket '211'
            is211 = W10.classify(R, a0, a1)[0] == '211'
            if is211 != (rec['kind'] == 'RAM' and rec['params'] == (1,)):
                w10tie_bad += 1
    note('W11-W10TIE', total)
    if w10tie_bad:
        viol('W11-W10TIE', 'pointwise', '%s q=%d N=%d: %d mismatches'
             % (kind, q, N, w10tie_bad))
    # ---- census vs closed forms (deep families predicted per center)
    pred = predict(q, N)
    pred_all = {}
    for (knd, prm), cnt in pred.items():
        pred_all[(knd, prm)] = cnt * q          # q centers
    nsep = (q * q - q) // 2 * q ** (2 * N - 2)
    pred_all[('SEP-SPLIT', ())] = nsep
    pred_all[('SEP-INERT', ())] = nsep
    keys = set(counts) | set(pred_all)
    note('W11-CENSUS', len(keys))
    for key in sorted(keys):
        if counts.get(key, 0) != pred_all.get(key, 0):
            viol('W11-CENSUS', 'count', '%s q=%d N=%d %s: obs %d pred %d'
                 % (kind, q, N, key, counts.get(key, 0),
                    pred_all.get(key, 0)))
    note('W11-CENSUS')
    if sum(counts.values()) != q ** (2 * N) or total != q ** (2 * N):
        viol('W11-CENSUS', 'sum', '%s q=%d N=%d: %d != %d'
             % (kind, q, N, sum(counts.values()), q ** (2 * N)))
    note('W11-CENSUS')
    # deepest chained history 1,2,...,m needs 2m <= N-1: m = (N-1)//2;
    # every chained history has positive closed-form count (q-1 >= 1
    # letters per step), so the max observed depth must hit it exactly.
    if max_depth_seen != (N - 1) // 2:
        viol('W11-CENSUS', 'depth', '%s q=%d N=%d: max hist %d != %d'
             % (kind, q, N, max_depth_seen, (N - 1) // 2))
    # ---- exhaustiveness / drainage / symmetry / sandwich
    undec = counts.get(('UNDECIDED', ()), 0)
    note('W11-EXHAUST', 2)
    if undec != q ** N:
        viol('W11-EXHAUST', 'drain', '%s q=%d N=%d: undecided %d != q^N=%d'
             % (kind, q, N, undec, q ** N))
    if sig['split'] != sig['inert']:
        viol('W11-EXHAUST', 'symmetry', '%s q=%d N=%d: split %d inert %d'
             % (kind, q, N, sig['split'], sig['inert']))
    tot = Fraction(q ** (2 * N))
    classical = {'split': Fraction(q, 2 * (q + 1)),
                 'inert': Fraction(q, 2 * (q + 1)),
                 'ram': Fraction(1, q + 1)}
    for sg, cl in classical.items():
        note('W11-EXHAUST')
        lo = Fraction(sig[sg]) / tot
        hi = Fraction(sig[sg] + undec) / tot
        if not (lo <= cl <= hi):
            viol('W11-EXHAUST', 'sandwich', '%s q=%d N=%d %s: %s !<= %s !<= %s'
                 % (kind, q, N, sg, lo, cl, hi))
    # ---- teeth on the checker
    ram_tot = sum(c for (kd, _), c in counts.items() if kd == 'RAM')
    ram1 = counts.get(('RAM', (1,)), 0)
    note('W11-CENSUS', 3)
    if sum(counts.values()) - ram_tot != q ** (2 * N) and ram_tot > 0:
        FIRE['W11-T-MISSING'] += 1
    else:
        viol('W11-CENSUS', 'tooth-missing-dead', '%s q=%d N=%d'
             % (kind, q, N))
    if sum(counts.values()) + ram1 != q ** (2 * N) and ram1 > 0:
        FIRE['W11-T-SHADOW'] += 1
    else:
        viol('W11-CENSUS', 'tooth-shadow-dead', '%s q=%d N=%d'
             % (kind, q, N))
    if undec != q ** (N + 1):                  # corrupted law q^N/center
        FIRE['W11-T-DRAIN'] += 1
    else:
        viol('W11-CENSUS', 'tooth-drain-dead', '%s q=%d N=%d' % (kind, q, N))
    rec = {'kind': kind, 'q': q, 'N': N, 'total': total,
           'counts': {repr(k): v for k, v in sorted(counts.items())},
           'sigma': {str(k): v for k, v in sig.items()},
           'undecided': undec, 'hist_census': hist_census,
           'max_depth': max_depth_seen,
           'elapsed_s': round(time.time() - t1, 1)}
    print('  [census %s q=%d N=%d] %d keys, undec=%d, maxdepth=%d (%.1fs)'
          % (kind, q, N, len(counts), undec, max_depth_seen,
             rec['elapsed_s']))
    return rec


# ---------------------------------------------------------- tower leg
TOWER_IDS = ['C2A', 'C2C', 'C2E', 'C2F', 'P3A', 'J7A', 'P1B', 'C3E']
SMOKE_TOWER_IDS = ['C2A', 'C3E']


def run_towers(ids):
    pool = {s['id']: dict(s) for s in JCP.ROSTER}
    pool.update({s['id']: dict(s) for s in JD0.P7_GENRE})
    pool.update({s['id']: dict(s) for s in JD0.PAIR_MEMBERS})
    out, wild_hits, non211 = [], 0, 0
    for tid in ids:
        spec = pool[tid]
        T = ITL.build_tower(spec)
        p = spec['p']
        for j in range(T.NR):
            e, h, g = spec['reads'][j]
            if e != 2 or g != 1:
                continue
            Phi_next = T.Phi[j + 1] if j + 1 <= T.n else T._build_lift(T.n)
            dv = T.P.dev(Phi_next, T.Phi[j])
            pts = [[i, T.wlev(j, A)] for i, A in enumerate(dv) if A]
            gam = T.gam[j + 1]
            wild = (p % e == 0)
            wild_hits += 1 if wild else 0
            non211 += 1 if h != 1 else 0
            out.append({'id': tid, 'level': j, 'p': p, 'ring': spec['ring'],
                        'read': (e, h, g), 'pts': pts, 'gam': gam,
                        'wPhi_j': T.wPhi[j], 'wild': wild})
            note('W11-TOWER', 4)
            if pts[0] != [0, gam] or pts[-1] != [2, 0]:
                viol('W11-TOWER', 'endpoints', '%s lvl %d: %s'
                     % (tid, j, pts))
            if gam % 2 != 1:
                viol('W11-TOWER', 'gam-parity', '%s lvl %d: gam=%d'
                     % (tid, j, gam))
            if len(pts) == 3 and 2 * pts[1][1] <= gam:
                viol('W11-TOWER', 'interior', '%s lvl %d: %s' % (tid, j, pts))
            if gam != e * T.wPhi[j] + h:
                viol('W11-TOWER', 'grid-tie', '%s lvl %d: gam=%d != %d'
                     % (tid, j, gam, e * T.wPhi[j] + h))
    note('W11-TOWER', 2)
    if wild_hits < 1:
        viol('W11-TOWER', 'no-wild', 'no wild (2,h,1) realization')
    if non211 < 1:
        viol('W11-TOWER', 'no-non211', 'no realized (2,h,1) with h != 1')
    print('  [towers] %d (2,h,1) levels, %d wild, %d beyond (2,1,1)'
          % (len(out), wild_hits, non211))
    return out, wild_hits, non211


# ---------------------------------------------------------- oracle leg
ORACLE_ROWS = [(2, 3), (2, 4), (2, 6), (3, 2), (3, 3), (5, 2), (7, 2)]
DLIFT_ROWS = [(2, 3), (2, 4), (3, 2), (3, 3)]
SMOKE_ORACLE = ([(2, 3), (3, 2)], [(3, 2)])

GP_FUN = r"""
t2(a1,a0,p) = {
  my(f = x^2+a1*x+a0, d = poldisc(f), vd, F, nf, dec);
  if (d == 0, return([-1, 0, 0, -1]));
  vd = valuation(d, p);
  F = factorpadic(f, p, 80);
  if (matsize(F)[1] == 2, return([2, 1, 1, vd]));
  nf = nfinit([f, [p]]); dec = idealprimedec(nf, p);
  [1, dec[1].e, dec[1].f, vd]
}
"""


def leaf_expect(rec):
    """(nprimes, e, f, vd) the decided leaf demands of PARI; None if
    undecided (no prediction)."""
    kd = rec['kind']
    if kd == 'UNDECIDED':
        return None
    if rec['sigma'] == 'split':
        return (2, 1, 1, rec['vd'])
    if rec['sigma'] == 'inert':
        return (1, 1, 2, rec['vd'])
    return (1, 2, 1, rec['vd'])


def oracle_leg(rows, dlift_rows):
    recs = []
    for (p, N) in rows:
        R = W10.ZpWin(p, N)
        M = p ** N
        cls = {}
        for a0 in range(M):
            for a1 in range(M):
                cls[(a1, a0)] = classify_full(R, p, a0, a1)
        allf = sorted(cls)
        script = GP_FUN + '\n'.join(
            'print("R ",%d," ",%d," ",t2(%d,%d,%d))' % (a1, a0, a1, a0, p)
            for (a1, a0) in allf) + '\nquit\n'
        outp = W10.gp_run(script)
        got = {}
        for line in outp.splitlines():
            if not line.startswith('R '):
                continue
            parts = line[2:].replace('[', '').replace(']', '') \
                            .replace(',', ' ').split()
            a1, a0, nd, e, f, vd = [int(x) for x in parts]
            got[(a1, a0)] = (nd, e, f, vd)
        nbad, nundec, nram2 = 0, 0, 0
        note('W11-ORACLE')
        if len(got) != len(allf):
            viol('W11-ORACLE', 'truncated', 'p=%d N=%d: %d of %d'
                 % (p, N, len(got), len(allf)))
        for key in allf:
            rec = cls[key]
            g = got.get(key)
            exp = leaf_expect(rec)
            note('W11-ORACLE')
            if exp is None:
                # undecided: PARI unconstrained -- but a degenerate disc=0
                # member MUST be undecided (checked from the other side)
                nundec += 1
                continue
            if g is None or g[:3] != exp[:3] or g[3] != exp[3]:
                nbad += 1
                viol('W11-ORACLE', 'leaf', 'p=%d N=%d f=(%d,%d) %s%s: '
                     'oracle %s expect %s' % (p, N, key[0], key[1],
                                              rec['kind'], rec['params'],
                                              g, exp))
            # degenerate cross-check
            if g is not None and g[0] == -1:
                note('W11-ORACLE')
                viol('W11-ORACLE', 'degenerate-decided',
                     'p=%d N=%d f=(%d,%d): disc=0 but leaf %s'
                     % (p, N, key[0], key[1], rec['kind']))
            # TOOTH T-SIGMA: inert leaves mis-keyed to split must be caught
            if rec['sigma'] == 'inert':
                note('W11-ORACLE')
                if g is not None and (2, 1, 1) != g[:3]:
                    FIRE['W11-T-SIGMA'] += 1
                else:
                    viol('W11-ORACLE', 'tooth-sigma-dead',
                         'p=%d N=%d f=(%d,%d)' % (p, N, key[0], key[1]))
            # TOOTH T-TAMEDISC: p=2 RAM members are wild
            if p == 2 and rec['kind'] == 'RAM':
                nram2 += 1
                note('W11-ORACLE')
                if g is not None and g[3] != 1:
                    FIRE['W11-T-TAMEDISC'] += 1
                else:
                    viol('W11-ORACLE', 'tooth-tamedisc-dead',
                         'p=2 N=%d f=(%d,%d)' % (N, key[0], key[1]))
        # degenerate members must be window-undecided
        for key in allf:
            g = got.get(key)
            if g is not None and g[0] == -1:
                note('W11-ORACLE')
                if cls[key]['kind'] != 'UNDECIDED':
                    viol('W11-ORACLE', 'disc0-not-undecided',
                         'p=%d N=%d f=%s: %s' % (p, N, key,
                                                 cls[key]['kind']))
        recs.append({'p': p, 'N': N, 'polys': len(allf), 'bad': nbad,
                     'undecided': nundec, 'p2_ram_members': nram2})
        print('  [oracle p=%d N=%d] %d polys, %d bad, %d undecided'
              % (p, N, len(allf), nbad, nundec))
        # ---- double-lift well-posedness
        if (p, N) in dlift_rows:
            dec = [key for key in allf
                   if cls[key]['kind'] != 'UNDECIDED']
            script = GP_FUN + '\n'.join(
                'print("R ",%d," ",%d," ",t2(%d,%d,%d),t2(%d,%d,%d))'
                % (a1, a0, a1, a0, p, a1 + M, a0 + M, p)
                for (a1, a0) in dec) + '\nquit\n'
            outp = W10.gp_run(script)
            nlift_bad, nparsed = 0, 0
            for line in outp.splitlines():
                if not line.startswith('R '):
                    continue
                nparsed += 1
                parts = line[2:].replace('[', ' ').replace(']', ' ') \
                                .replace(',', ' ').split()
                vals = [int(x) for x in parts]
                a1, a0 = vals[0], vals[1]
                note('W11-ORACLE')
                if vals[2:6] != vals[6:10]:
                    nlift_bad += 1
                    viol('W11-ORACLE', 'double-lift',
                         'p=%d N=%d f=(%d,%d): %s vs %s'
                         % (p, N, a1, a0, vals[2:6], vals[6:10]))
            note('W11-ORACLE')
            if nparsed != len(dec):
                viol('W11-ORACLE', 'dlift-truncated', 'p=%d N=%d: %d of %d'
                     % (p, N, nparsed, len(dec)))
            recs[-1]['double_lift'] = {'decided': len(dec),
                                       'bad': nlift_bad}
            print('  [dlift p=%d N=%d] %d decided members, %d bad'
                  % (p, N, len(dec), nlift_bad))
    return recs


# ---------------------------------------------------------- main
def main(smoke=False):
    t0 = time.time()
    print('W11 SEALED BATTERY -- %s mode' % ('SMOKE' if smoke else 'FULL'))
    for fn, want in PINS.items():
        note('W11-PIN')
        got = hashlib.md5(open(os.path.join(HERE, fn), 'rb').read()
                          ).hexdigest()
        if got != want:
            viol('W11-PIN', fn, '%s != %s' % (got, want))
    census_rows = SMOKE_CENSUS if smoke else CENSUS_ROWS
    census_recs = [run_census_row(*row) for row in census_rows]
    tower_recs, wild_hits, non211 = run_towers(
        SMOKE_TOWER_IDS if smoke else TOWER_IDS)
    orows, drows = (SMOKE_ORACLE if smoke else (ORACLE_ROWS, DLIFT_ROWS))
    try:
        oracle_recs = oracle_leg(orows, drows)
    except Exception as ex:
        viol('W11-ORACLE', 'gp', '%s: %s' % (type(ex).__name__, ex))
        oracle_recs = [{'error': repr(ex)}]

    nviol = sum(len(v) for v in VIOL.values())
    teeth_ok = all(FIRE[t] >= 1 for t in TEETH)
    verdict = 'GREEN' if (nviol == 0 and teeth_ok) else 'RED'
    summary = {
        'mode': 'smoke' if smoke else 'full',
        'verdict': verdict,
        'census_rows': len(census_recs),
        'checks': NCHK, 'violations': {f: len(VIOL[f]) for f in FAMILIES},
        'violation_detail': {f: VIOL[f][:50] for f in FAMILIES},
        'teeth_fires': FIRE,
        'census': census_recs,
        'towers': {'levels': tower_recs, 'wild_hits': wild_hits,
                   'non211': non211},
        'oracle': oracle_recs,
        'elapsed_s': round(time.time() - t0, 1),
    }
    tag = '_smoke' if smoke else ''
    with open(os.path.join(HERE, 'w11_checks_results%s.json' % tag),
              'w') as fh:
        json.dump(summary, fh, indent=1, default=repr)
    lines = ['W11 BATTERY VERDICT: %s' % verdict,
             'census rows: %d   tower (2,h,1) levels: %d (wild %d, '
             'beyond-211 %d)   checks: %d'
             % (len(census_recs), len(tower_recs), wild_hits, non211,
                sum(NCHK.values())),
             'violations: ' + ' '.join('%s=%d' % (f, len(VIOL[f]))
                                       for f in FAMILIES),
             'teeth: ' + ' '.join('%s=%d' % (t, FIRE[t]) for t in TEETH),
             'oracle: ' + ' '.join(
                 '(%s,%s):%s/%sbad' % (r.get('p'), r.get('N'),
                                       r.get('polys'), r.get('bad'))
                 for r in oracle_recs),
             'elapsed: %.1fs' % (time.time() - t0)]
    print('\n'.join(lines))
    if not smoke:
        with open(os.path.join(HERE, 'w11_checks_output.txt'), 'w') as fh:
            fh.write('\n'.join(lines) + '\n')
    return 0 if verdict == 'GREEN' else 1


if __name__ == '__main__':
    sys.exit(main(smoke='--smoke' in sys.argv))
