/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import Mathlib
import LeanUrat.Scaffold.DictIII.GMNReader
import LeanUrat.MovesT.Defs
-- ^ pins the probe context for the BLOCKED(III-S2) record below:
--   `MovesT.accE`/`MovesT.accF` resolve under this import, so the recorded
--   type-mismatch errors are reproducible verbatim at this pin.

/-!
# Scaffold/DictIII/CU2t — the terminal seam (BP_III §1.9)

E-phase transcription of `lean/blueprints/BP_III.md` §1.9 (Step 11's CU-2t,
VERIFIED-at-scope leaf #9).  This file currently holds unit III-S1a (the
decidedness predicates `DecIrr` and `DecHen`, transcribed VERBATIM; source of
record: CUC §9.2; `DecIrr` intentionally carries no unused polynomial `f`,
REV2 finding 21), unit III-S5a (the Mathlib Hensel probe, below), unit
III-S2 PARTIAL (the `TerminalDatum` carrier landed verbatim; the
`terminalDatum` def is BLOCKED on the accE/accF carrier seam — record at the
end of this file), and unit III-S6 PARTIAL (the `ThetaTauData` carrier landed
verbatim modulo the keyword-escape note at its docstring; the `ThetaTau` def,
its well-definedness, and `thetaTau_truncation` are BLOCKED downstream of
III-S2 — record at the end of this file, with validated provability notes for
the eventual re-land), and unit III-S5c PARTIAL (the τ-hen engine
`cu2t_tauHen_lift` landed — `Lit3Hensel` with every binder instantiated at the
corpus carrier, per the row's sketch; the verdict-shaped half is BLOCKED
downstream of III-S2/III-S3 — record mid-file).

Display adjustment (III-S1a; the same sanctioned convention as the
Carriers.lean header): the §1.9 display writes the node lookup as
`H.nodes.get? k`, but `List.get?` was REMOVED from the Lean-4.31/Mathlib
environment pinned here; the surviving spelling of the SAME function is
`H.nodes[k]?` (`getElem?`, of which `List.get?` was the deprecated alias).
The proposition is unchanged; no other token differs from the display.

Display adjustment (III-S1c `j0_le_one`; same sanctioned convention, but
FLAGGED for architect ratification since it substitutes a constant rather
than respelling one): the §1.9 display writes the mod-p reduction of `f` as
`Polynomial.map (ZMod.intCastRingHom p) f`, which cannot compile in this pin.
Exact errors: (a) "Unknown constant `ZMod.intCastRingHom`" — the name does
not exist in the pinned Mathlib; (b) its surviving renaming
`Int.castRingHom (ZMod p)` has domain `ℤ`, so the display's application fails
with "Application type mismatch: The argument f has type Polynomial ℤ_[p]
but is expected to have type Polynomial ℤ".  The unique well-typed reading
of "reduce the coefficients of `f : Polynomial ℤ_[p]` into `ZMod p`" is
`Polynomial.map PadicInt.toZMod f`: a ring hom `ℤ_[p] →+* ZMod p` is unique
(its image is the prime field generated by 1, its kernel a maximal ideal =
the unique maximal ideal `pℤ_[p]`, and the induced map `F_p → F_p` is the
identity), and `PadicInt.toZMod` is that hom — also the standing corpus
spelling of the mod-p reduction (O2aOrder1.lean; cited as the convention in
Locality.lean).  No other token differs from the display.  NOTE: the same
adjustment will be forced on III-S1b (`sq_not_dvd_reduction_of_disc_unit`)
and on the `hsq` row of `cu2t_readForcing`, which share this spelling.
-/

namespace LeanUrat.Scaffold.DictIII

variable {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]

/-- CU-2t decidedness, branch (i): some node at index ≥ 1 selects residual
    multiplicity μ = 1 (the terminal "irreducible read" verdict). -/
def DecIrr (H : EHist p F) : Prop :=
  ∃ k ν g, 1 ≤ k ∧ H.nodes[k]? = some ν ∧ ν.sel = some (g, 1)
  -- `.get?` → `[k]?`: header note

/-- CU-2t decidedness, branch (ii): a length-1 history decided at the root —
    either a₀ = 1 outright, or some semantic datum reads root order 1. -/
def DecHen (f : Polynomial ℤ_[p]) (H : EHist p F) : Prop :=
  H.nodes.length = 1 ∧
    (H.a0 = 1 ∨
      ∃ D : GMNData f (Theta H), D.rootOrder = 1)

/-- Unit III-S1c (BP_III §1.9, CUC §9.2): if `φ²` does not divide the mod-p
    reduction of `f`, then any `φ`-power dividing that reduction has exponent
    `j₀ ≤ 1`.  The `¬φ² ∣ f̄` premise is EXPLICIT (REV2 finding 16 — no bare
    characteristic-zero discriminant claim; III-S1b supplies it from the
    discriminant p-unit premise).  `Polynomial.map PadicInt.toZMod f` renders
    the display's mod-p reduction: header note (III-S1c). -/
theorem j0_le_one (f : Polynomial ℤ_[p]) (hf : f.Monic)
    (φ : Polynomial (ZMod p)) (hφ : Irreducible φ)
    (hsq : ¬φ ^ 2 ∣ Polynomial.map PadicInt.toZMod f)
    (j₀ : ℕ)
    (hj₀ : φ ^ j₀ ∣ Polynomial.map PadicInt.toZMod f) :
    j₀ ≤ 1 := by
  by_contra h
  exact hsq ((pow_dvd_pow φ (by omega : 2 ≤ j₀)).trans hj₀)

/-! ## Unit III-S5a — probe of the installed Mathlib Hensel declaration

MECH probe (BP_III §2 row III-S5a; src CUC §9.3 (ii)): record the fully
qualified name and type of the Hensel declaration actually installed in the
pinned Mathlib (`v4.31.0`), without assuming `Polynomial.hensels_lemma`
exists.  Findings, anchored by the `#check`s and the `run_cmd` below:

* THE declaration is **`hensels_lemma`** — TOP-LEVEL, no namespace.
  `Polynomial.hensels_lemma` does NOT exist in this pin (the `Hensel`
  namespace of its file closes before the theorem; machine-checked by the
  `run_cmd` environment probe below).  Location:
  `Mathlib/NumberTheory/Padics/Hensel.lean` (line 458 in the pin).
  Type as printed by `#check @hensels_lemma`:

  ```
  ∀ {p : ℕ} [inst : Fact (Nat.Prime p)] {R : Type u_1} [inst_1 : CommSemiring R]
    [inst_2 : Algebra R ℤ_[p]] {F : Polynomial R} {a : ℤ_[p]},
    ‖(Polynomial.aeval a) F‖ < ‖(Polynomial.aeval a) (Polynomial.derivative F)‖ ^ 2 →
      ∃ z, (Polynomial.aeval z) F = 0 ∧
        ‖z - a‖ < ‖(Polynomial.aeval a) (Polynomial.derivative F)‖ ∧
        ‖(Polynomial.aeval z) (Polynomial.derivative F)‖
          = ‖(Polynomial.aeval a) (Polynomial.derivative F)‖ ∧
        ∀ (z' : ℤ_[p]), (Polynomial.aeval z') F = 0 →
          ‖z' - a‖ < ‖(Polynomial.aeval a) (Polynomial.derivative F)‖ → z' = z
  ```

  I.e. the NEWTON ROOT-LIFTING form over `ℤ_[p]` (norm condition
  `‖F(a)‖ < ‖F′(a)‖²` ⇒ unique nearby root), NOT a factorization lift.

* Companion class-level forms (`Mathlib/RingTheory/Henselian.lean`):
  `HenselianRing : (R : Type u_1) → [inst : CommRing R] → Ideal R → Prop` and
  `HenselianLocalRing : (R : Type u_1) → [CommRing R] → Prop`, whose field
  `is_henselian` is again SIMPLE-ROOT lifting (monic `f`, root of `f` mod the
  (maximal) ideal with unit derivative, lifts to a root of `f`).  The only
  instance route in the pin is `IsAdicComplete.henselianRing`; no
  `HenselianLocalRing ℤ_[p]` instance is pre-declared anywhere in the pin.

* NEGATIVE finding, load-bearing for III-S5c: the pinned Mathlib has NO
  monic-coprime-FACTORIZATION-lifting Hensel (the `Lit3Hensel` shape of
  BP_III §1.3 / III-H9).  Hence III-S5c must consume the NAMED literature
  row `Lit3Hensel` (structure hypothesis, per the [M]-row discipline), not a
  Mathlib declaration. -/

section IIIS5aProbe

#check @hensels_lemma            -- top-level FQN; type displayed above
#check @HenselianRing            -- class, ideal-relative simple-root form
#check @HenselianLocalRing       -- class, maximal-ideal simple-root form
#check @HenselianLocalRing.is_henselian
#check @IsAdicComplete.henselianRing

-- info-anchor: the environment probe backing the two name claims above.
open Lean Elab Command in
run_cmd do
  let env ← getEnv
  unless env.contains `hensels_lemma do
    throwError "III-S5a probe failed: `hensels_lemma` not found"
  if env.contains `Polynomial.hensels_lemma then
    throwError "III-S5a probe failed: `Polynomial.hensels_lemma` unexpectedly exists"

end IIIS5aProbe

/-- T(f, 𝐇°): the forced terminal datum — read entry λ_{k′+1} ∈ ℚ<0 ∪ {−∞} +
    verdict pair (accE, accF) resp. (1, f₀). -/
structure TerminalDatum where
  slope : Option (ℕ × ℕ)
  verdict : ℕ × ℕ

/- BLOCKED(III-S2): `terminalDatum` (BP_III §1.9, displayed verbatim below)
does NOT elaborate as written, so the def is NOT landed (statement changes are
fenced).  The `TerminalDatum` carrier above IS landed (it compiles verbatim).
Grounds, machine-checked at this pin (Lean 4.31, 2026-08-01, under the header
import `LeanUrat.MovesT.Defs`):

(1) NOT curable by dependency landing — the accE/accF carrier seam, IDENTICAL
    to the one blocking III-H9 (`Hyps.lean` record) and III-A7
    (`O2aOrder1.lean` record): the verdict branch applies the corpus functions
    `MovesT.accE`/`MovesT.accF : MovesC.History p F → ℕ` to
    `H.nodes : List ENodeData`.  Exact errors (probed verbatim in this file):
      error: Application type mismatch: The argument
        H.nodes
      has type
        List ENodeData
      but is expected to have type
        MovesC.History ?m.28 ?m.30
      in the application
        MovesT.accE H.nodes
    (and the same at `MovesT.accF H.nodes`).  No coercion exists; a
    list-domain overload or an `ENodeData → MovesC.Node` dressing would be a
    NEW definition changing the row's meaning — architect ruling needed
    (same seam, same cure point as III-H9/III-A7).

(2) Curable by ambience once (1) is ruled: the verdict branch discriminates
    on the (undecidable-as-stated) Prop `DecIrr H` —
      error(lean.synthInstanceFailed): failed to synthesize instance of type
      class
        Decidable (DecIrr H)
    Cure: `open Classical in` before the def (elaboration ambience only; no
    statement token changes) — noted here so the eventual re-land applies it
    together with the seam ruling.

The blocked display, for the record (BP_III §1.9):

  def terminalDatum (f : Polynomial ℤ_[p]) (H : EHist p F) : TerminalDatum :=
    { slope := H.nodes.getLast?.bind fun ν => some (ν.e, ν.h)
      verdict :=
        if DecIrr H then (MovesT.accE H.nodes, MovesT.accF H.nodes)
        else (1, H.psi0.natDegree) }

Downstream inheritors (do not attempt before the ruling): III-S3
(`RCConsistent` references both `(terminalDatum f H).slope` and `.verdict`),
III-S5d (`cu2t_verdict`, record below), III-S6 (`ThetaTau` copies both
fields), III-S7. -/

/- BLOCKED(III-S5d): `cu2t_verdict` (BP_III §1.9, display at blueprint lines
639–644) does NOT elaborate as written — statement changes are fenced, so the
unit is NOT landed.  Two independent grounds (Lean 4.31, this pin, 2026-08-01):

(1) NOT curable by dependency landing: the hypothesis row
    `(hcor : GMNCor120_38 p F)` names the §1.3 literature structure that is
    itself BLOCKED at III-H9 (record in `Hyps.lean`): its display applies the
    corpus functions `MovesT.accE`/`accF : MovesC.History p F → ℕ` to
    `H.nodes : List ENodeData`.  Exact error at the verbatim statement:
      Unknown identifier `GMNCor120_38`
    and the root obstruction (probed, this pin):
      Application type mismatch: The argument H.nodes has type
        List ENodeData
      but is expected to have type
        MovesC.History ?p ?F
      in the application MovesT.accE H.nodes
    Needs the same architect ruling as III-H9.

(2) Dependency-shaped but NOT curable by verbatim transcription: `terminalDatum`
    (III-S2) and `RCConsistent` (III-S3) are not in the corpus ("Unknown
    identifier" at the statement's conclusion and `hrc` row), and III-S2's OWN
    §1.9 display fails with the SAME `MovesT.accE H.nodes` type mismatch
    (probed verbatim, 2026-08-01; see the BLOCKED(III-S2) record ABOVE and the
    BLOCKED(III-S3) record BELOW in this file) — so the missing deps cannot be
    landed without the ruling either.  Deps III-S5b/III-S5c are likewise
    unlanded (III-S5b sits downstream of the BLOCKED III-A7; record in
    `O2aOrder1.lean`).

The blocked display, for the record (BP_III §1.9):

  theorem cu2t_verdict (f : Polynomial ℤ_[p]) (H : EHist p F)
      (ν : ENodeData) (EF : ℕ × ℕ)
      (hdec : DecIrr H ∨ DecHen f H)
      (hcor : GMNCor120_38 p F) (hhen : Lit3Hensel p)
      (hrc : RCConsistent f H ν EF) :
      EF = (terminalDatum f H).verdict
-/

/- BLOCKED(III-S3): `RCConsistent` (BP_III §1.9, displayed verbatim below) can
NOT land — its dependency III-S2 (`terminalDatum`) is not in the corpus, so the
verbatim statement fails with "Unknown identifier `terminalDatum`", and III-S2
is itself unlandable as displayed (accE/accF carrier seam + `Decidable
(DecIrr H)`; independently probed 2026-08-01 in a scratch compile, since
deleted, with exactly the errors of the BLOCKED(III-S2) record above — see
that record for the exact error text and the pending III-H9 architect ruling).
Statement changes are fenced; nothing is weakened; the row is NOT landed.

Unique III-S3 finding: the unit is otherwise CLEAN.  Against a signature-only
stub `terminalDatum (f : Polynomial ℤ_[p]) (H : EHist p F) : TerminalDatum`
(with `TerminalDatum` as displayed — now landed above), the `RCConsistent`
display below compiled VERBATIM with zero errors (2026-08-01, this pin).  The
block is entirely inherited from III-S2; once III-S2 lands, III-S3 is a
mechanical transcription with no display adjustment needed.

The blocked display, for the record (BP_III §1.9, CUC §9.2a — (RC-read) is
the slope clause, (RC-verd) the verdict clause):

  def RCConsistent (f : Polynomial ℤ_[p]) (H : EHist p F)
      (ν : ENodeData) (EF : ℕ × ℕ) : Prop :=
    ν.sel = none ∧
    some (ν.e, ν.h) = (terminalDatum f H).slope ∧
    EF = (terminalDatum f H).verdict
-/

/- BLOCKED(III-S5b): the τ-irr verdict from `GMNCor120_38` ("instantiate the
displayed local literature row"; deps III-S4, III-H9, III-A7; src CUC §9.3
(ii)) can NOT land — statement fence.  Machine-checked 2026-08-01 by a probe
file compiled at exactly this import state and then deleted:

(1) The row to be instantiated does not exist and cannot be stated: the §1.3
    `GMNCor120_38` is BLOCKED at III-H9 (record in `Hyps.lean`) on the
    accE/accF carrier seam.  The probe re-elaborated the §1.3 display HERE,
    with `DecIrr` landed above — III-H9's other ground ("Unknown identifier
    `DecIrr`") is thereby CURED, and the seam is the SOLE surviving error:
      error: Application type mismatch: The argument
        H.nodes
      has type
        List ENodeData
      but is expected to have type
        MovesC.History ?m.36 ?m.38
      in the application
        MovesT.accE H.nodes
    (and the same at `MovesT.accF H.nodes`).  Same architect ruling as the
    III-H9/III-A7/III-S2 records.

(2) The τ-irr verdict VALUE carries the seam independently of (1): BP_III
    displays no standalone III-S5b lemma — its content is the `DecIrr` branch
    of `cu2t_verdict` (BLOCKED(III-S5d) record above) through `terminalDatum`'s
    verdict pair.  The probe's second leg,
      example (H : EHist p F) : ℕ × ℕ :=
        (MovesT.accE H.nodes, MovesT.accF H.nodes)
    fails with the identical mismatch, so NO faithful S5b statement (row
    instantiation or standalone conclusion) elaborates at this pin.

(3) Deps unlanded: III-A7 BLOCKED (same seam; record in `O2aOrder1.lean`);
    III-S4 (`cu2t_readForcing`) absent from the corpus at S5b time (its
    display is seam-free — a separate unit, not repaired here).

Unblock path: architect ruling on the carrier seam → land III-H9's
`GMNCor120_38` → land III-S2/III-S4 → transcribe the τ-irr branch here and
prove by firing `GMNCor120_38.irrationalBranch`.  Nothing was weakened; no
display token was altered. -/

/-! ## Unit III-S6 — `ThetaTauData` (landed) + `ThetaTau`/well-definedness/
`thetaTau_truncation` (BLOCKED downstream of III-S2; record below).
Source of record: CUC §9.3 (iii). -/

/-- Θ_τ carrier: the continuing-prefix chain Θ(𝐇°) + the terminal read entry +
    the verdict pair (unit III-S6, transcribed VERBATIM from BP_III §1.9
    modulo the keyword escape below).

    Display adjustment (III-S6; the same sanctioned convention as the header
    notes): the §1.9 display names the first field `prefix`, but `prefix` is
    a reserved KEYWORD token in Lean 4 (it opens the notation command
    `prefix:… => …`), so the field declaration cannot parse — exact error at
    the display's field row: "unexpected identifier; expected prec".  The
    guillemet spelling `«prefix»` declares the IDENTICAL field name (the
    projection is `ThetaTauData.prefix`, and use-site dot access
    `.prefix.take k` — the spelling in `thetaTau_truncation`'s display —
    parses UNESCAPED; both machine-checked at this pin).  No other token
    differs from the display. -/
structure ThetaTauData (p : ℕ) [Fact p.Prime]
    (F : Type*) [Field F] [Finite F] where
  «prefix» : ChainData p F
  terminalSlope : Option (ℕ × ℕ)
  verdict : ℕ × ℕ

/- BLOCKED(III-S6, remaining halves): the `ThetaTau` def, its
well-definedness, and `thetaTau_truncation` (BP_III §1.9, displayed verbatim
below) canNOT land — the displayed `ThetaTau` body copies both fields of
`(terminalDatum f H)`, and dep unit III-S2 (`terminalDatum`) is not in the
corpus and is not landable as displayed (accE/accF carrier seam, pending the
III-H9 architect ruling — see the BLOCKED(III-S2) record above for the exact
error text).  At the verbatim `ThetaTau` display the errors are
"Unknown identifier `terminalDatum`" (twice, at `.slope` and `.verdict`);
`thetaTau_truncation` then fails "Unknown identifier `ThetaTau`".  Statement
changes are fenced; nothing is weakened; the two declarations are NOT landed.

Unique III-S6 findings — the block is ENTIRELY inherited from III-S2, and the
remaining halves are validated MECHANICAL once it lands (probe record
2026-08-01, this pin, scratch compile since deleted, against a locally
repaired III-S2 stub of the displayed `TerminalDatum` codomain):

(1) the `ThetaTau` display below then compiles VERBATIM (with the `«prefix»`
    escape above; `noncomputable` may be forced by the stub's classical `if`
    — elaboration ambience, not a statement token);
(2) well-definedness: the blueprint displays NO separate statement — the DEC
    witness `hdec` does not occur in the displayed body, so `ThetaTau` is
    LITERALLY constant in it; the probe
      example (h₁ h₂ : DecIrr H ∨ DecHen f H) :
          ThetaTau f H h₁ = ThetaTau f H h₂ := rfl
    compiled against the stub (definitional — not even proof irrelevance);
(3) `thetaTau_truncation` is the Carriers.lean one-liner
      theta_truncation H.continuingPart k
    (`(ThetaTau f H hdec).prefix` is definitionally `Theta H.continuingPart`,
    and III-C7b's `theta_truncation` instantiated at `H.continuingPart` is
    EXACTLY the displayed goal); compiled against the stub.

The blocked displays, for the record (BP_III §1.9):

  def ThetaTau (f : Polynomial ℤ_[p]) (H : EHist p F)
      (hdec : DecIrr H ∨ DecHen f H) : ThetaTauData p F :=
    { prefix := Theta H.continuingPart
      terminalSlope := (terminalDatum f H).slope
      verdict := (terminalDatum f H).verdict }

  theorem thetaTau_truncation (f : Polynomial ℤ_[p]) (H : EHist p F)
      (hdec : DecIrr H ∨ DecHen f H) (k : ℕ) :
      (ThetaTau f H hdec).prefix.take k = Theta (H.continuingPart.take k)

Downstream inheritor: III-S7 (`thetaTau_injective` binds `ThetaTau` in its
`hEq` row at both displayed granularities). -/

end LeanUrat.Scaffold.DictIII
