/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import LeanUrat.MovesT.Defs

/-! # TV-B8 — `History.snoc_induction`, the last-node decomposition eliminator

BRIDGE CAMPAIGN unit **TV-B8** (area BP3, cluster B; blueprint
`lean/notes/BRIDGE_BP3_TV_2026-07-30.md` §3.B [REV 2, finding 6] + §4). E-PHASE
SKELETON — statement pinned, body `sorry`. Additive ("MovesT Defs vicinity" —
landed in a NEW file per the E-phase rules; declared in the `History` namespace
so consumers get dot-notation, the `History.lastNode` precedent, Defs.lean:402).

INFORMAL STATEMENT: every `History` is reached from a one-node history by
`snoc` steps — a motive-based eliminator. `TreeModel.mem` is GENERATED by
`child` through `mem_single` (one-node histories) and `mem_snoc` (extensions),
so TV-B3 (`mem_cyl_of_child_cyl`: (S-child) ⟹ (S-mem)) consumes exactly this
eliminator; it was flagged by the adversarial review as a genuinely NEW
prerequisite, hence its own unit.

PROOF SKETCH (feasibility verified in blueprint §3.B, by strong induction on
`H.nodes.length`):
* singleton case: the node is root-species by `History.root_iff` at j = 0,
  giving the `ChildRoot none ν` witness; `H = oneNode ν h` via the PROVED ext
  lemma `history_eq_of_nodes_eq` (E5_rootSplit.lean:171, private — re-derive or
  de-privatize at prover time; the G1 `hist_ext` twin is the same content);
* ≥ 2-node case: the LAST node has species ≠ root by `root_iff` (index ≠ 0) —
  exactly the snoc side condition (`NodeExtends`, MovesT/Defs.lean:77); the
  prefix `H.nodes.dropLast` carries `root_iff` by restriction and is shorter;
  the reconstruction equality `H = H₀.snoc ν hν` follows from
  `history_eq_of_nodes_eq` + `List.dropLast_append_getLast`. The G1
  ToyPinHelpers `snoc_eq_*` lemmas are the concrete pattern.

deps: none. Consumed by: TV-B3. difficulty: hard-fable, ~50 lines. -/

set_option linter.style.longLine false
set_option linter.unusedVariables false

namespace LeanUrat.MovesT

open Polynomial LeanUrat.Moves LeanUrat.MovesC LeanUrat.MovesD

variable {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]

/-- **TV-B8 `History.snoc_induction`** — the last-node decomposition eliminator
(blueprint §3.B display, verbatim): a motive holding at every one-node history
and preserved by `snoc` extension holds at every history. The `oneNode` case's
witness is `ChildRoot none ν` (= root species, MovesT/Defs.lean:88); the `snoc`
case's side condition is the built `History.snoc` guard
`ν.species ≠ ReadSpecies.root` (= `NodeExtends`, MovesT/Defs.lean:77). -/
theorem _root_.LeanUrat.MovesC.History.snoc_induction
    {motive : History p F → Prop}
    (hone : ∀ (ν : Node p F) (h : ChildRoot none ν), motive (oneNode ν h))
    (hsnoc : ∀ (H₀ : History p F) (ν : Node p F)
      (hν : ν.species ≠ ReadSpecies.root), motive H₀ → motive (H₀.snoc ν hν))
    (H : History p F) : motive H := by
  sorry

end LeanUrat.MovesT
