/-
Copyright (c) 2026 Asvin G. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Asvin G
-/
import LeanUrat.MovesT.TV_B2
import LeanUrat.MovesT.TV_B8

/-! # TV-B3 — `mem_cyl_of_child_cyl`: (S-child) ⟹ (S-mem)

BRIDGE CAMPAIGN unit **TV-B3** (area BP3, cluster B; blueprint
`lean/notes/BRIDGE_BP3_TV_2026-07-30.md` §3.B + §4). E-PHASE SKELETON —
statements pinned, bodies `sorry`.

INFORMAL STATEMENT: `TreeModel.mem` is GENERATED by `child` through
`mem_single` (one-node histories) and `mem_snoc` (extensions), so the child
transfer law (S-child) = `StableInputs.child_cyl` implies the mem transfer
(S-mem) at every history, by induction on the history's node list via the
TV-B8 eliminator `History.snoc_induction`.

STATEMENT RESOLUTION (recorded): the unit is stated in TWO layers —
* `tv_b3_mem_transfer_of_child_transfer`, the SINGLE-MODEL CORE at one fixed
  box pair (x, x'): pointwise child transfer at (x, x') gives mem transfer at
  (x, x') for every H. This is the actual induction content (the tower/
  threshold quantifiers play no role in it) and the E5-helper genre the
  blueprint's sketch describes;
* `mem_cyl_of_child_cyl`, the blueprint-named TOWER FORM (S-mem) verbatim:
  from `SI : StableInputs` (TV-B2), at every threshold-passing pair N ≤ N'
  and every level-<n·N-agreeing box pair. Its proof = the core lemma at
  `hchild := fun o ν => SI.child_cyl N hN N' h' hNN' o ν x x' hagree`.

PROOF SKETCH (core lemma): `History.snoc_induction` (TV-B8) on H — singleton
case: `mem_single` rewrites both sides to `child none ν ·`, close by `hchild`;
snoc case: `mem_snoc` rewrites both sides to `mem (some H₀) · ∧ child (some H₀)
ν ·`, close by the IH And-congruent with `hchild`. NOTE: `mem_single`'s carrier
is the raw `⟨[ν], h1.1, h1.2⟩` constructor (MovesD/Defs.lean:638) while TV-B8's
singleton case produces `oneNode ν h` — the prover bridges via the `oneNode`
unfolding (the E5 `mem_oneNode_iff` helper is the in-corpus precedent,
E5_rootSplit.lean:131-193 vicinity).

E-PHASE FINDING carried from TV-B1/TV-B2 (recorded, affects the TOWER form
only): the unguarded tower chart carrier `χat : ∀ N', Fin n → Fin (n * N')` is
uninhabited at n ≥ 1, so `mem_cyl_of_child_cyl` (which binds a `StableInputs`
over such a χat) is vacuously derivable at n ≥ 1 until the Q2/B7 guard repair;
the CORE lemma is χat-free and carries the honest content either way.

deps: B2 (the bundle), B8 (the eliminator, prover-time). Consumed by: TV-B5,
TV-B6. difficulty: hard-fable, ~40 lines. -/

set_option linter.style.longLine false
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false

namespace LeanUrat.MovesT

open Polynomial LeanUrat.Moves LeanUrat.MovesC LeanUrat.MovesD

variable {p : ℕ} [Fact p.Prime] {F : Type*} [Field F] [Finite F]
variable {n N m : ℕ} {pol : CanonPolicy p F}

/-- realizing the one-node history IS realizing the root child (`mem_single`
keyed to the closed `oneNode`; the E5 `mem_oneNode_iff` twin, re-derived
locally — the in-corpus original is `private`, module docstring note). -/
private lemma mem_oneNode_iff' (T : TreeModel p F n N m pol) (ν : Node p F)
    (h : ChildRoot none ν) (x : Box p m) :
    T.mem (some (oneNode ν h)) x ↔ T.child none ν x := by
  have h1 : (([ν] : List (Node p F)) ≠ [] ∧
      ∀ (j : ℕ) (hj : j < ([ν] : List (Node p F)).length),
        ((([ν] : List (Node p F))[j]'hj).species = ReadSpecies.root ↔ j = 0)) := by
    refine ⟨by simp, ?_⟩
    intro j hj
    have hj0 : j = 0 := by simpa using Nat.lt_one_iff.mp (by simpa using hj)
    subst hj0
    simpa using (show ν.species = ReadSpecies.root from h)
  exact T.mem_single ν h1 x

/-- **TV-B3, the single-model core** — pointwise child transfer at a fixed box
pair gives mem transfer at every history (mem is GENERATED by child through
`mem_single`/`mem_snoc`; induction via `History.snoc_induction`, TV-B8). -/
theorem tv_b3_mem_transfer_of_child_transfer (T : TreeModel p F n N m pol)
    (x x' : Box p m)
    (hchild : ∀ (o : Option (History p F)) (ν : Node p F),
      T.child o ν x ↔ T.child o ν x')
    (H : History p F) :
    T.mem (some H) x ↔ T.mem (some H) x' := by
  induction H using History.snoc_induction with
  | hone ν h =>
    exact (mem_oneNode_iff' T ν h x).trans
      ((hchild none ν).trans (mem_oneNode_iff' T ν h x').symm)
  | hsnoc H₀ ν hν ih =>
    rw [T.mem_snoc H₀ ν hν x, T.mem_snoc H₀ ν hν x']
    exact and_congr ih (hchild (some H₀) ν)

/-- **TV-B3 `mem_cyl_of_child_cyl`** — (S-child) ⟹ (S-mem), the blueprint's
tower form verbatim: under the TV-B2 bundle, at every threshold-passing pair
N ≤ N' and every box pair agreeing on the level-<N block (the first n·N
coordinates), membership transfers at EVERY history — the arbitrary-H
determinacy `fiberAt` clause (i)'s backward direction needs (quantifier option
α, TV-B2's R8 flag). -/
theorem mem_cyl_of_child_cyl {N₀ : ℕ}
    (Tat : ∀ N', N₀ ≤ N' → TreeModel p F n N' (n * N') pol)
    (χat : ∀ N', Fin n → Fin (n * N')) (Tr : VTree p F)
    (SI : StableInputs Tat χat Tr)
    (N : ℕ) (hN : Tr.thr n ≤ N)
    (N' : ℕ) (h' : N₀ ≤ N') (hNN' : N ≤ N')
    (H : History p F) (x x' : Box p (n * N'))
    (hagree : ∀ c : Fin (n * N'), (c : ℕ) < n * N → x c = x' c) :
    (Tat N' h').mem (some H) x ↔ (Tat N' h').mem (some H) x' := by
  exact tv_b3_mem_transfer_of_child_transfer (Tat N' h') x x'
    (fun o ν => SI.child_cyl N hN N' h' hNN' o ν x x' hagree) H

end LeanUrat.MovesT
